# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import enum
import uuid
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, String, Uuid, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


class OtherEnum(enum.Enum):
    A = "a"


class Other(Base):
    __tablename__ = "other"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    weirds: Mapped[list["Weird"]] = relationship(
        back_populates="other",
        passive_deletes=True,
    )


class Weird(Base):
    __tablename__ = "weird"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    a_b: Mapped[str] = mapped_column(String, server_default="x;y")
    quote: Mapped[str] = mapped_column(String, server_default="say \"hi\"")
    tick: Mapped[str] = mapped_column(String, server_default="a`b")
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    self_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid,
        ForeignKey("weird.id", ondelete="SET NULL"),
    )
    other_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("other.id", ondelete="CASCADE"),
    )

    self_: Mapped[Optional["Weird"]] = relationship(
        back_populates="weirds",
        remote_side="Weird.id",
    )
    other: Mapped["Other"] = relationship(back_populates="weirds")
    weirds: Mapped[list["Weird"]] = relationship(
        back_populates="self_",
        passive_deletes=True,
    )
