# Generated by ormbridge. Review the output before creating tables or migrations.

import enum
from typing import Optional

from sqlalchemy import ForeignKey, Integer, String
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


class OtherEnum(enum.Enum):
    A = "a"


class Other(Base):
    __tablename__ = "others"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    weirds: Mapped[list["Weird"]] = relationship(
        back_populates="other",
        passive_deletes=True,
    )


class Weird(Base):
    __tablename__ = "weird"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    a_b: Mapped[str] = mapped_column("a;b", String, server_default="x;y")
    quote: Mapped[str] = mapped_column(String, server_default="say \"hi\"")
    tick: Mapped[str] = mapped_column(String, server_default="a`b")
    self_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("weird.id", ondelete="SET NULL"),
    )
    other_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("others.id", ondelete="CASCADE"),
    )

    self_: Mapped[Optional["Weird"]] = relationship(
        back_populates="weirds",
        remote_side="Weird.id",
    )
    other: Mapped["Other"] = relationship(back_populates="weirds")
    weirds: Mapped[list["Weird"]] = relationship(
        back_populates="self_",
        passive_deletes=True,
    )
