# Generated by ormbridge. Review the output before creating tables or migrations.

import enum
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


class OtherEnum(enum.Enum):
    A = "a"


class Other(SQLModel, table=True):
    __tablename__ = "others"

    id: Optional[int] = Field(default=None, primary_key=True)

    weirds: list["Weird"] = Relationship(
        back_populates="other",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Weird(SQLModel, table=True):
    __tablename__ = "weird"

    id: Optional[int] = Field(default=None, primary_key=True)
    a_b: str = Field(
        default="x;y",
        sa_column_kwargs={"name": "a;b", "server_default": "x;y"},
    )
    quote: str = Field(
        default="say \"hi\"",
        sa_column_kwargs={"server_default": "say \"hi\""},
    )
    tick: str = Field(default="a`b", sa_column_kwargs={"server_default": "a`b"})
    self_id: Optional[int] = Field(
        default=None,
        foreign_key="weird.id",
        ondelete="SET NULL",
    )
    other_id: int = Field(foreign_key="others.id", ondelete="CASCADE")

    self_: Optional["Weird"] = Relationship(
        back_populates="weirds",
        sa_relationship_kwargs={"remote_side": "Weird.id"},
    )
    other: "Other" = Relationship(back_populates="weirds")
    weirds: list["Weird"] = Relationship(
        back_populates="self_",
        sa_relationship_kwargs={"passive_deletes": True},
    )
