# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    false,
    func,
    text,
)
from sqlmodel import Field, Relationship, SQLModel


class PostStatus(enum.Enum):
    DRAFT = "draft"
    PUBLISHED = "published"


blog_post_tags = Table(
    "blog_post_tags",
    SQLModel.metadata,
    Column(
        "blog_post_id",
        ForeignKey("blog_post.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "blog_tag_id",
        ForeignKey("blog_tag.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)


class BlogUser(SQLModel, table=True):
    __tablename__ = "blog_user"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    author_blog_posts: list["BlogPost"] = Relationship(
        back_populates="author",
        sa_relationship_kwargs={
            "foreign_keys": "[BlogPost.author_id]",
            "passive_deletes": True,
        },
    )
    editor_blog_posts: list["BlogPost"] = Relationship(
        back_populates="editor",
        sa_relationship_kwargs={
            "foreign_keys": "[BlogPost.editor_id]",
            "passive_deletes": True,
        },
    )
    blog_profile: Optional["BlogProfile"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class BlogCategory(SQLModel, table=True):
    __tablename__ = "blog_category"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: datetime.datetime = Field(sa_type=DateTime(timezone=True))
    name: str = Field(unique=True, max_length=100)
    slug: str = Field(max_length=50)
    parent_id: Optional[uuid.UUID] = Field(
        default=None,
        foreign_key="blog_category.id",
        ondelete="SET NULL",
    )

    parent: Optional["BlogCategory"] = Relationship(
        back_populates="blog_categories",
        sa_relationship_kwargs={"remote_side": "BlogCategory.id"},
    )
    blog_categories: list["BlogCategory"] = Relationship(
        back_populates="parent",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    blog_posts: list["BlogPost"] = Relationship(back_populates="category")


class BlogTag(SQLModel, table=True):
    __tablename__ = "blog_tag"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    label: str = Field(max_length=50)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    blog_posts: list["BlogPost"] = Relationship(
        back_populates="tags",
        sa_relationship_kwargs={"secondary": blog_post_tags},
    )


class BlogPost(SQLModel, table=True):
    __tablename__ = "blog_post"
    __table_args__ = (
        UniqueConstraint("author_id", "title", name="blog_post_author_id_title_key"),
        Index("blog_post_title_idx", "title"),
        Index("post_pub_status_idx", "published_at", "status"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: datetime.datetime = Field(sa_type=DateTime(timezone=True))
    public_id: uuid.UUID = Field(default_factory=uuid.uuid4, unique=True)
    title: str = Field(max_length=200)
    body: str = Field(sa_type=Text)
    status: PostStatus = Field(
        default=PostStatus.DRAFT,
        sa_type=Enum(
            PostStatus,
            name="post_status",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "draft"},
    )
    rating: Optional[decimal.Decimal] = Field(
        default=None,
        max_digits=4,
        decimal_places=2,
    )
    view_count: int = Field(default=0, sa_column_kwargs={"server_default": text("0")})
    is_featured: bool = Field(
        default=False,
        sa_column_kwargs={"server_default": false()},
    )
    published_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    metadata_: Any = Field(
        default_factory=dict,
        sa_type=JSON,
        sa_column_kwargs={"name": "metadata", "server_default": text("'{}'")},
    )
    author_id: uuid.UUID = Field(foreign_key="blog_user.id", ondelete="CASCADE")
    editor_id: Optional[uuid.UUID] = Field(
        default=None,
        foreign_key="blog_user.id",
        ondelete="SET NULL",
    )
    category_id: uuid.UUID = Field(
        sa_column=Column(
            "category_id",
            Uuid,
            ForeignKey(
                "blog_category.id",
                ondelete="RESTRICT",
                name="blog_post_category_id_fkey",
            ),
            nullable=False,
        ),
    )

    author: "BlogUser" = Relationship(
        back_populates="author_blog_posts",
        sa_relationship_kwargs={"foreign_keys": "[BlogPost.author_id]"},
    )
    editor: Optional["BlogUser"] = Relationship(
        back_populates="editor_blog_posts",
        sa_relationship_kwargs={"foreign_keys": "[BlogPost.editor_id]"},
    )
    category: "BlogCategory" = Relationship(back_populates="blog_posts")
    tags: list["BlogTag"] = Relationship(
        back_populates="blog_posts",
        sa_relationship_kwargs={"secondary": blog_post_tags},
    )


class BlogProfile(SQLModel, table=True):
    __tablename__ = "blog_profile"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    bio: Optional[str] = Field(default=None, sa_type=Text)
    avatar: Optional[str] = Field(default=None, max_length=100)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    user_id: uuid.UUID = Field(
        foreign_key="blog_user.id",
        ondelete="CASCADE",
        unique=True,
    )

    user: "BlogUser" = Relationship(back_populates="blog_profile")
