-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE series (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  handle VARCHAR(20) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  parent_id CHAR(36),
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE book (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  title VARCHAR(120) NOT NULL,
  tags JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  grid JSON, -- an array stored as JSON
  colors JSON, -- an array stored as JSON
  color ENUM('red', 'green') NOT NULL DEFAULT 'red',
  price DECIMAL(8, 2) NOT NULL DEFAULT 9.99,
  settings JSON NOT NULL DEFAULT ('{"theme":"dark","tabs":[1,2]}'),
  published_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  opens_at TIME(6),
  released_at DATETIME(6) DEFAULT '2020-01-02 03:04:05',
  pages INT NOT NULL DEFAULT 100,
  ratio DOUBLE NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT TRUE,
  notes LONGTEXT,
  `window` VARCHAR(255), -- range stored as text
  extra JSON, -- hstore stored as JSON
  read_time BIGINT, -- duration in microseconds
  cover LONGBLOB,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  author_id CHAR(36) NOT NULL,
  editor_id CHAR(36),
  series_handle VARCHAR(20),
  CONSTRAINT book_pkey PRIMARY KEY (id),
  CONSTRAINT book_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX book_title_author_id_key ON book (title, author_id);
CREATE INDEX books_published_idx ON book (published_on);

CREATE TABLE author (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  latest_book_id CHAR(36),
  CONSTRAINT author_pkey PRIMARY KEY (id),
  CONSTRAINT author_handle_key UNIQUE (handle),
  CONSTRAINT author_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES book (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audiobook (
  minutes INT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  book_ptr_id CHAR(36) NOT NULL,
  CONSTRAINT audiobook_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobook_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES book (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `index` (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  `sql` VARCHAR(255),
  class VARCHAR(255),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `table` CHAR(36),
  CONSTRAINT index_pkey PRIMARY KEY (id),
  CONSTRAINT index_table_fkey FOREIGN KEY (`table`) REFERENCES series (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tagged (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tagged_book (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  tagged_id CHAR(36) NOT NULL,
  book_id CHAR(36) NOT NULL,
  CONSTRAINT tagged_book_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_book_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_book_book_id_fkey FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX tagged_book_tagged_id_book_id_key ON tagged_book (tagged_id, book_id);

-- These foreign keys close a reference cycle, so they are added once every table exists.

ALTER TABLE book ADD CONSTRAINT book_author_id_fkey FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE book ADD CONSTRAINT book_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES author (id) ON DELETE SET NULL;
