-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE series (
  id INT NOT NULL AUTO_INCREMENT,
  handle VARCHAR(20) NOT NULL,
  parent_id INT,
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE books (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(120) NOT NULL,
  tags JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  grid JSON, -- an array stored as JSON
  colors JSON, -- an array stored as JSON
  color ENUM('red', 'green') NOT NULL DEFAULT 'red',
  price DECIMAL(8, 2) NOT NULL DEFAULT 9.99,
  settings JSON NOT NULL DEFAULT ('{"theme":"dark","tabs":[1,2]}'),
  published_on DATE NOT NULL DEFAULT (CURRENT_DATE),
  opens_at TIME(6),
  released_at DATETIME(6) DEFAULT '2020-01-02 03:04:05',
  pages INT NOT NULL DEFAULT 100,
  ratio DOUBLE NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT TRUE,
  notes LONGTEXT,
  `window` VARCHAR(255), -- range stored as text
  extra JSON, -- hstore stored as JSON
  read_time BIGINT, -- duration in microseconds
  cover LONGBLOB,
  author_id CHAR(36) NOT NULL,
  editor_id CHAR(36),
  series_handle VARCHAR(20),
  CONSTRAINT books_pkey PRIMARY KEY (id),
  CONSTRAINT books_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX books_title_author_id_key ON books (title, author_id);
CREATE INDEX books_published_idx ON books (published_on);

CREATE TABLE authors (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INT,
  latest_book_id BIGINT,
  CONSTRAINT authors_pkey PRIMARY KEY (id),
  CONSTRAINT authors_handle_key UNIQUE (handle),
  CONSTRAINT authors_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES books (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE audiobooks (
  minutes INT NOT NULL,
  book_ptr_id BIGINT NOT NULL,
  CONSTRAINT audiobooks_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobooks_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES books (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE index_rows (
  id INT NOT NULL AUTO_INCREMENT,
  `sql` VARCHAR(255),
  class VARCHAR(255),
  `table` INT,
  CONSTRAINT index_rows_pkey PRIMARY KEY (id),
  CONSTRAINT index_rows_table_fkey FOREIGN KEY (`table`) REFERENCES series (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tagged (
  id BIGINT NOT NULL AUTO_INCREMENT,
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE tagged_books (
  id INT NOT NULL AUTO_INCREMENT,
  tagged_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  CONSTRAINT tagged_books_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_books_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_books_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX tagged_books_tagged_id_book_id_key ON tagged_books (tagged_id, book_id);

-- These foreign keys close a reference cycle, so they are added once every table exists.

ALTER TABLE books ADD CONSTRAINT books_author_id_fkey FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE books ADD CONSTRAINT books_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES authors (id) ON DELETE SET NULL;
