import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { convertText } from '../src/convert.js';
import {
  emitSqlAlchemy,
  isSqlAlchemyStyle,
  SQLALCHEMY_STYLES,
  type SqlAlchemyStyle,
} from '../src/emitters/sqlalchemy.js';
import type { EmitOutput } from '../src/emitters/prisma.js';
import { describeFormats, getFormat, listFormats } from '../src/formats.js';
import type {
  IrCompositeForeignKey,
  IrEnum,
  IrField,
  IrModel,
  IrSchema,
} from '../src/ir.js';
import type { NamingMode } from '../src/transforms.js';
import { constructsSchema } from './drizzleFixtures.js';
import {
  STATUS,
  field,
  idField,
  index,
  kitchenSinkSchema,
  model,
  relation,
  schemaOf,
  stressSchema,
} from './gormFixtures.js';
import { checkSqlAlchemyOutput } from './sqlalchemyCoverage.js';
import {
  SQLALCHEMY_IR_FIXTURES,
  sqlalchemyPython,
} from './sqlalchemySupport.js';
import { DEFAULT_OPTIONS, expectOk } from './helpers.js';
import { CANONICAL_FIXTURES } from './fixtures/canonical.js';
import { convertCanonical, expectFilesMatchGolden } from './harness.js';
import { EXTRA_SOURCES, parseSource } from './realToolSupport.js';

function emit(
  schema: IrSchema,
  style: SqlAlchemyStyle = 'sqlalchemy',
  naming: NamingMode = 'preserve'
): EmitOutput {
  return emitSqlAlchemy(schema, { naming, style });
}

/** Joins the lines of wrapped calls, so assertions do not depend on where a line was broken. */
function squash(text: string): string {
  return text
    .replace(/\(\n\s+/g, '(')
    .replace(/\{\n\s+/g, '{')
    .replace(/\[\n\s+/g, '[')
    .replace(/,\n\s*\)/g, ')')
    .replace(/,\n\s+\}/g, '}')
    .replace(/,\n\s+\]/g, ']')
    .replace(/,\n\s+(?=[A-Za-z_"'{[(])/g, ', ');
}

function code(
  schema: IrSchema,
  style: SqlAlchemyStyle = 'sqlalchemy',
  naming: NamingMode = 'preserve'
): string {
  return squash(emit(schema, style, naming).text);
}

/** The squashed text of one class. */
function classOf(text: string, name: string): string {
  const match: RegExpExecArray | null = new RegExp(
    `^class ${name}\\([^\\n]*\\n(?:(?!\\n\\n\\nclass |\\n\\n\\n[a-z_]+ = ).)*`,
    'ms'
  ).exec(text);
  if (match === null) {
    throw new Error(`No class ${name} in:\n${text}`);
  }
  return match[0];
}

/** A one-model schema. */
function thing(fields: IrField[], extra: Partial<IrModel> = {}): IrSchema {
  return schemaOf([model('Thing', { tableName: 'things', fields, ...extra })]);
}

const STYLES: readonly SqlAlchemyStyle[] = ['sqlalchemy', 'sqlmodel'];

describe('sqlalchemy emitter: module layout', () => {
  it('writes a header, only the imports it uses, Base and the model', () => {
    const output: EmitOutput = emit(thing([idField(), field('name')]));
    expect(output.warnings).toEqual([]);
    expect(output.text).toBe(
      [
        '# Generated by ormbridge. Review the output before creating tables or migrations.',
        '',
        'from sqlalchemy import Integer, String',
        'from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column',
        '',
        '',
        'class Base(DeclarativeBase):',
        '    pass',
        '',
        '',
        'class Thing(Base):',
        '    __tablename__ = "things"',
        '',
        '    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)',
        '    name: Mapped[str] = mapped_column(String)',
        '',
      ].join('\n')
    );
  });

  it('writes SQLModel classes for the sqlmodel style', () => {
    const output: EmitOutput = emit(
      thing([idField(), field('name', { maxLength: 40 })]),
      'sqlmodel'
    );
    expect(output.text).toBe(
      [
        '# Generated by ormbridge. Review the output before creating tables or migrations.',
        '',
        'from typing import Optional',
        '',
        'from sqlmodel import Field, SQLModel',
        '',
        '',
        'class Thing(SQLModel, table=True):',
        '    __tablename__ = "things"',
        '',
        '    id: Optional[int] = Field(default=None, primary_key=True)',
        '    name: str = Field(max_length=40)',
        '',
      ].join('\n')
    );
  });

  it.each(STYLES)('writes an empty schema without models (%s)', (style) => {
    const output: EmitOutput = emit(schemaOf([]), style);
    expect(output.warnings).toEqual([]);
    expect(output.text).not.toContain('class Thing');
  });

  it('imports datetime, decimal, enum, uuid and typing only when used', () => {
    const text: string = emit(
      thing([
        idField(),
        field('at', { type: 'dateTime' }),
        field('amount', { type: 'decimal' }),
        field('uid', { type: 'uuid' }),
        field('blob', { type: 'json', isNullable: true }),
      ])
    ).text;
    expect(text).toContain('import datetime\nimport decimal\nimport uuid\n');
    expect(text).toContain('from typing import Any, Optional\n');
    expect(text).not.toContain('import enum');
    const plain: string = emit(thing([idField()])).text;
    expect(plain).not.toContain('import datetime');
    expect(plain).not.toContain('typing');
  });

  it('sorts the sqlalchemy imports constants first, then classes, then functions', () => {
    const text: string = emit(
      thing([
        idField(),
        field('at', { type: 'dateTime', default: { kind: 'now' } }),
        field('data', { type: 'json' }),
      ])
    ).text;
    expect(text).toContain(
      'from sqlalchemy import JSON, DateTime, Integer, func\n'
    );
  });

  it('wraps long imports and long calls to 88 columns', () => {
    const output: string = emit(kitchenSinkSchema()).text;
    expect(output).toMatch(/from sqlalchemy import \(\n {4}ARRAY,\n/);
    for (const line of output.split('\n')) {
      // Only an array of enums with a variant is allowed to run past the limit.
      expect(line.length, line).toBeLessThanOrEqual(88);
    }
  });
});

describe('sqlalchemy emitter: column types', () => {
  const cases: [string, Partial<IrField>, string, string, string][] = [
    ['string', { type: 'string' }, 'Mapped[str]', 'String', 'str'],
    [
      'string with a length',
      { type: 'string', maxLength: 30 },
      'Mapped[str]',
      'String(30)',
      'str',
    ],
    ['text', { type: 'text' }, 'Mapped[str]', 'Text', 'str'],
    ['int', { type: 'int' }, 'Mapped[int]', 'Integer', 'int'],
    ['bigInt', { type: 'bigInt' }, 'Mapped[int]', 'BigInteger', 'int'],
    ['float', { type: 'float' }, 'Mapped[float]', 'Float', 'float'],
    [
      'decimal with precision',
      { type: 'decimal', maxDigits: 8, decimalPlaces: 2 },
      'Mapped[decimal.Decimal]',
      'Numeric(8, 2)',
      'decimal.Decimal',
    ],
    [
      'decimal without precision',
      { type: 'decimal' },
      'Mapped[decimal.Decimal]',
      'Numeric',
      'decimal.Decimal',
    ],
    ['boolean', { type: 'boolean' }, 'Mapped[bool]', 'Boolean', 'bool'],
    [
      'dateTime',
      { type: 'dateTime' },
      'Mapped[datetime.datetime]',
      'DateTime(timezone=True)',
      'datetime.datetime',
    ],
    [
      'date',
      { type: 'date' },
      'Mapped[datetime.date]',
      'Date',
      'datetime.date',
    ],
    [
      'time',
      { type: 'time' },
      'Mapped[datetime.time]',
      'Time',
      'datetime.time',
    ],
    [
      'duration',
      { type: 'duration' },
      'Mapped[datetime.timedelta]',
      'Interval',
      'datetime.timedelta',
    ],
    ['uuid', { type: 'uuid' }, 'Mapped[uuid.UUID]', 'Uuid', 'uuid.UUID'],
    ['json', { type: 'json' }, 'Mapped[Any]', 'JSON', 'Any'],
    ['bytes', { type: 'bytes' }, 'Mapped[bytes]', 'LargeBinary', 'bytes'],
    [
      'unsupported',
      { type: 'unsupported', unsupportedType: 'circle' },
      'Mapped[str]',
      'String',
      'str',
    ],
  ];

  it.each(cases)(
    'maps %s (sqlalchemy)',
    (_label, overrides, annotation, saType) => {
      const text: string = code(thing([idField(), field('value', overrides)]));
      expect(text).toContain(
        `    value: ${annotation} = mapped_column(${saType})`
      );
    }
  );

  it.each(cases)('maps %s (sqlmodel)', (_label, overrides, _a, saType, py) => {
    const text: string = code(
      thing([idField(), field('value', overrides)]),
      'sqlmodel'
    );
    const line: string =
      text
        .split('\n')
        .find((candidate: string) => candidate.startsWith('    value: ')) ?? '';
    expect(line.startsWith(`    value: ${py}`)).toBe(true);
    if (overrides.type === 'string' && overrides.maxLength !== undefined) {
      expect(line).toContain('max_length=30');
    } else if (
      overrides.type === 'decimal' &&
      overrides.maxDigits !== undefined
    ) {
      expect(line).toContain('max_digits=8, decimal_places=2');
    } else if (
      ['text', 'bigInt', 'dateTime', 'json'].includes(overrides.type ?? '')
    ) {
      expect(line).toContain(`sa_type=${saType}`);
    } else {
      expect(line).not.toContain('sa_type');
    }
  });

  it('marks a nullable column Optional in both styles', () => {
    const schema: IrSchema = thing([
      idField(),
      field('note', { type: 'text', isNullable: true }),
    ]);
    expect(code(schema)).toContain(
      '    note: Mapped[Optional[str]] = mapped_column(Text)'
    );
    expect(code(schema, 'sqlmodel')).toContain(
      '    note: Optional[str] = Field(default=None, sa_type=Text)'
    );
  });

  it('stores a nullable JSON column as SQL NULL, not as the JSON value null', () => {
    const schema: IrSchema = thing([
      idField(),
      field('data', { type: 'json', isNullable: true }),
    ]);
    expect(code(schema)).toContain(
      'data: Mapped[Optional[Any]] = mapped_column(JSON(none_as_null=True))'
    );
  });

  it('writes PostgreSQL types with a fallback for SQLite and warns', () => {
    const schema: IrSchema = thing([
      idField(),
      field('labels', { arrayDepth: 1 }),
      field('grid', { type: 'int', arrayDepth: 2, isNullable: true }),
      field('extra', { type: 'hstore' }),
      field('window', { type: 'range', rangeOf: 'int' }),
      field('span', { type: 'range', rangeOf: 'dateTime' }),
      field('cost', { type: 'range', rangeOf: 'decimal' }),
      field('day', { type: 'range', rangeOf: 'date' }),
      field('big', { type: 'range', rangeOf: 'bigInt' }),
      field('ip', { type: 'ipAddress' }),
    ]);
    const output: EmitOutput = emit(schema);
    const text: string = squash(output.text);
    expect(text).toContain(
      'labels: Mapped[list[str]] = mapped_column(ARRAY(String).with_variant(JSON(), "sqlite"))'
    );
    expect(text).toContain(
      'grid: Mapped[Optional[list[list[int]]]] = mapped_column(ARRAY(Integer, dimensions=2).with_variant(JSON(), "sqlite"))'
    );
    expect(text).toContain(
      'extra: Mapped[dict[str, str]] = mapped_column(HSTORE().with_variant(JSON(), "sqlite"))'
    );
    expect(text).toContain('Mapped[Range[int]] = mapped_column(INT4RANGE()');
    expect(text).toContain(
      'Mapped[Range[datetime.datetime]] = mapped_column(TSTZRANGE()'
    );
    expect(text).toContain(
      'Mapped[Range[decimal.Decimal]] = mapped_column(NUMRANGE()'
    );
    expect(text).toContain(
      'Mapped[Range[datetime.date]] = mapped_column(DATERANGE()'
    );
    expect(text).toContain('Mapped[Range[int]] = mapped_column(INT8RANGE()');
    expect(text).toContain(
      'ip: Mapped[str] = mapped_column(INET().with_variant(String(45), "sqlite"))'
    );
    expect(output.text).toContain(
      'from sqlalchemy.dialects.postgresql import (\n    DATERANGE,'
    );
    expect(output.warnings).toEqual([
      'Thing.labels, grid, extra, window, span, cost, day, big, ip: array, HSTORE, range and IP address columns are PostgreSQL types; they fall back to JSON (or a string) on SQLite.',
    ]);
  });

  it('warns about a range column without an element type', () => {
    const output: EmitOutput = emit(
      thing([idField(), field('window', { type: 'range' })])
    );
    expect(output.text).toContain('INT4RANGE()');
    expect(output.warnings).toContain(
      'Thing.window: the range field has no element type; it was written as INT4RANGE.'
    );
  });

  it('writes SQLModel PostgreSQL columns with sa_type', () => {
    const text: string = code(
      thing([idField(), field('labels', { arrayDepth: 1 })]),
      'sqlmodel'
    );
    expect(text).toContain(
      'labels: list[str] = Field(sa_type=ARRAY(String).with_variant(JSON(), "sqlite"))'
    );
  });

  it('warns about an unsupported column type and a computed column', () => {
    const output: EmitOutput = emit(
      thing([
        idField(),
        field('area', {
          type: 'unsupported',
          unsupportedType: 'circle',
          isNullable: true,
        }),
        field('total', {
          type: 'int',
          generated: { expression: 'F("a") + F("b")', isStored: true },
        }),
      ])
    );
    expect(output.warnings).toEqual([
      'Thing.area: the database type "circle" (Prisma Unsupported) has no equivalent here; the column was written as a plain string.',
      'Thing.total: the computed column expression F("a") + F("b") is not SQL and was dropped; the column was written as a plain column.',
    ]);
  });
});

describe('sqlalchemy emitter: primary keys', () => {
  it('marks an auto-increment key', () => {
    expect(code(thing([idField()]))).toContain(
      'id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)'
    );
  });

  it('lets SQLite count up a big integer key', () => {
    const schema: IrSchema = thing([idField({ type: 'bigInt' })]);
    expect(code(schema)).toContain(
      'id: Mapped[int] = mapped_column(BigInteger().with_variant(Integer, "sqlite"), primary_key=True, autoincrement=True)'
    );
    expect(code(schema, 'sqlmodel')).toContain(
      'id: Optional[int] = Field(default=None, primary_key=True, sa_type=BigInteger().with_variant(Integer, "sqlite"))'
    );
  });

  it('switches autoincrement off for an integer key without a default', () => {
    const schema: IrSchema = thing([
      field('code', { type: 'int', isPrimaryKey: true }),
    ]);
    expect(code(schema)).toContain(
      'code: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)'
    );
    expect(code(schema, 'sqlmodel')).toContain(
      'code: int = Field(primary_key=True, sa_column_kwargs={"autoincrement": False})'
    );
  });

  it('gives a UUID key a Python default', () => {
    const schema: IrSchema = thing([
      field('id', {
        type: 'uuid',
        isPrimaryKey: true,
        default: { kind: 'uuid' },
      }),
    ]);
    expect(code(schema)).toContain(
      'id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)'
    );
    expect(code(schema, 'sqlmodel')).toContain(
      'id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)'
    );
  });

  it('writes a composite primary key as a PrimaryKeyConstraint', () => {
    const schema: IrSchema = schemaOf([
      model('Pair', {
        tableName: 'pairs',
        fields: [
          field('region', { maxLength: 8 }),
          field('number', { type: 'int' }),
        ],
        compositePrimaryKey: ['region', 'number'],
      }),
    ]);
    const text: string = emit(schema).text;
    expect(text).toContain(
      '    __table_args__ = (\n        PrimaryKeyConstraint("region", "number"),\n    )'
    );
    expect(code(schema)).not.toContain('primary_key=True');
    expect(code(schema, 'sqlmodel')).not.toContain('primary_key=True');
  });

  it('names a primary key constraint', () => {
    const schema: IrSchema = thing([idField()], {
      primaryKeyName: 'things_pk',
    });
    expect(code(schema)).toContain(
      'PrimaryKeyConstraint("id", name="things_pk")'
    );
  });

  it('writes a key that is a relation as primary_key on the foreign key', () => {
    const schema: IrSchema = schemaOf([
      model('Parent', { tableName: 'parents' }),
      model('Child', {
        tableName: 'children',
        fields: [field('extra', { type: 'int' })],
        relations: [
          relation('parent', 'Parent', {
            kind: 'oneToOne',
            columnName: 'parent_ptr_id',
            isPrimaryKey: true,
          }),
        ],
      }),
    ]);
    const child: string = classOf(code(schema), 'Child');
    expect(child).toContain(
      'parent_ptr_id: Mapped[int] = mapped_column(Integer, ForeignKey("parents.id", ondelete="CASCADE"), primary_key=True)'
    );
    expect(child).not.toContain('unique=True');
    const sqlmodel: string = classOf(code(schema, 'sqlmodel'), 'Child');
    expect(sqlmodel).toContain(
      'parent_ptr_id: int = Field(primary_key=True, foreign_key="parents.id", ondelete="CASCADE")'
    );
  });

  it('maps a table without a primary key on its required columns', () => {
    const schema: IrSchema = thing([
      field('a', { type: 'int' }),
      field('b', { isNullable: true }),
    ]);
    const sqlalchemy: EmitOutput = emit(schema);
    expect(sqlalchemy.text).toContain(
      '    __mapper_args__ = {"primary_key": [a]}'
    );
    expect(sqlalchemy.warnings).toEqual([
      'Thing: the table has no primary key, which the SQLAlchemy ORM requires; every required column was declared as the mapper key (the table itself keeps no primary key).',
    ]);
    const sqlmodel: EmitOutput = emit(schema, 'sqlmodel');
    expect(squash(sqlmodel.text)).toContain('a: int = Field(primary_key=True)');
    expect(sqlmodel.warnings).toEqual([
      'Thing: the table has no primary key, which SQLModel requires; the first column was marked as the primary key.',
    ]);
  });
});

describe('sqlalchemy emitter: defaults', () => {
  const defaults: [string, Partial<IrField>, string, string][] = [
    [
      'string literal',
      { default: { kind: 'literal', value: "it's" } },
      'server_default="it\'s"',
      'default="it\'s"',
    ],
    [
      'number literal',
      { type: 'int', default: { kind: 'literal', value: 5 } },
      'server_default=text("5")',
      'default=5',
    ],
    [
      'decimal literal',
      { type: 'decimal', default: { kind: 'literal', value: 9.99 } },
      'server_default=text("9.99")',
      'default=None',
    ],
    [
      'true',
      { type: 'boolean', default: { kind: 'literal', value: true } },
      'server_default=true()',
      'default=True',
    ],
    [
      'false',
      { type: 'boolean', default: { kind: 'literal', value: false } },
      'server_default=false()',
      'default=False',
    ],
    [
      'now',
      { type: 'dateTime', default: { kind: 'now' } },
      'server_default=func.now()',
      'default=None',
    ],
    [
      'now on a date',
      { type: 'date', default: { kind: 'now' } },
      'server_default=func.current_date()',
      'default=None',
    ],
    [
      'now on a time',
      { type: 'time', default: { kind: 'now' } },
      'server_default=func.current_time()',
      'default=None',
    ],
    [
      'uuid',
      { type: 'uuid', default: { kind: 'uuid' } },
      'default=uuid.uuid4',
      'default_factory=uuid.uuid4',
    ],
    [
      'database expression',
      {
        type: 'uuid',
        default: { kind: 'dbExpression', expression: 'gen_random_uuid()' },
      },
      'server_default=text("gen_random_uuid()")',
      'default=None',
    ],
    [
      'json object',
      {
        type: 'json',
        default: { kind: 'literal', value: '{"a": [1, true, null]}' },
      },
      'server_default=text("\'{\\"a\\": [1, true, null]}\'")',
      'default_factory=lambda: {"a": [1, True, None]}',
    ],
    [
      'empty json list',
      { type: 'json', default: { kind: 'literal', value: '[]' } },
      'server_default=text("\'[]\'")',
      'default_factory=list',
    ],
    [
      'empty json object',
      { type: 'json', default: { kind: 'literal', value: '{}' } },
      'server_default=text("\'{}\'")',
      'default_factory=dict',
    ],
    [
      'empty array',
      { arrayDepth: 1, default: { kind: 'literal', value: '[]' } },
      'default=list',
      'default_factory=list',
    ],
    [
      'auto-updated',
      { type: 'dateTime', isAutoUpdated: true },
      'default=func.now(), onupdate=func.now()',
      'sa_column_kwargs={"default": func.now(), "onupdate": func.now()}',
    ],
    [
      'now and auto-updated',
      { type: 'dateTime', isAutoUpdated: true, default: { kind: 'now' } },
      'server_default=func.now(), onupdate=func.now()',
      'sa_column_kwargs={"server_default": func.now(), "onupdate": func.now()}',
    ],
  ];

  it.each(defaults)(
    'writes a %s default (sqlalchemy)',
    (_label, overrides, expected) => {
      const text: string = code(thing([idField(), field('value', overrides)]));
      const line: string =
        text
          .split('\n')
          .find((candidate: string) => candidate.startsWith('    value: ')) ??
        '';
      expect(line).toContain(expected);
    }
  );

  it.each(defaults)(
    'writes a %s default (sqlmodel)',
    (_label, overrides, expected, sqlmodel) => {
      const text: string = code(
        thing([idField(), field('value', overrides)]),
        'sqlmodel'
      );
      const line: string =
        text
          .split('\n')
          .find((candidate: string) => candidate.startsWith('    value: ')) ??
        '';
      expect(line).toContain(sqlmodel);
    }
  );

  it('writes an enum default as the stored value', () => {
    const schema: IrSchema = schemaOf(
      [
        model('Thing', {
          tableName: 'things',
          fields: [
            idField(),
            field('status', {
              enumName: 'Status',
              default: { kind: 'enumValue', value: 'LIVE' },
            }),
          ],
        }),
      ],
      [STATUS]
    );
    expect(code(schema)).toContain('server_default="live"');
    expect(code(schema, 'sqlmodel')).toContain('default=Status.LIVE');
  });

  it('warns about defaults it cannot write', () => {
    const output: EmitOutput = emit(
      thing([
        idField(),
        field('id2', {
          type: 'uuid',
          default: { kind: 'uuid', version: 7 },
        }),
        field('seq', {
          type: 'int',
          default: { kind: 'autoIncrement' },
        }),
        field('fn', {
          default: {
            kind: 'dbExpression',
            expression: 'auto()',
            isFunction: true,
          },
        }),
        field('cuid', {
          default: { kind: 'clientGenerated', generator: 'cuid' },
        }),
        field('bad', {
          enumName: 'Status',
          default: { kind: 'enumValue', value: 'GONE' },
        }),
        field('tags', {
          arrayDepth: 1,
          default: { kind: 'literal', value: 'a,b' },
        }),
      ])
    );
    expect(output.warnings).toContain(
      'Thing.id2: the UUID version 7 default was written as uuid.uuid4.'
    );
    expect(output.warnings).toContain(
      'Thing.seq: an auto-increment default on a column that is not the primary key has no equivalent here and was dropped.'
    );
    expect(output.warnings).toContain(
      'Thing.fn: the Prisma default function auto() has no equivalent here and was dropped.'
    );
    expect(output.warnings).toContain(
      'Thing.cuid: the cuid() default is generated by Prisma Client and was dropped.'
    );
    expect(output.warnings).toContain(
      'Thing.bad: the enum default GONE is not a member of the enum and was dropped.'
    );
    expect(output.warnings).toContain(
      'Thing.tags: the array default "a,b" has no portable form and was dropped.'
    );
  });
});

describe('sqlalchemy emitter: uniqueness and indexes', () => {
  it('writes unique=True for a unique column', () => {
    const schema: IrSchema = thing([
      idField(),
      field('email', { maxLength: 50, isUnique: true }),
    ]);
    expect(code(schema)).toContain(
      'email: Mapped[str] = mapped_column(String(50), unique=True)'
    );
    expect(code(schema, 'sqlmodel')).toContain(
      'email: str = Field(unique=True, max_length=50)'
    );
  });

  it('writes a named unique constraint in __table_args__', () => {
    const schema: IrSchema = thing([
      idField(),
      field('email', { isUnique: true, uniqueName: 'uq_things_email' }),
    ]);
    const text: string = code(schema);
    expect(text).toContain('UniqueConstraint("email", name="uq_things_email")');
    expect(text).not.toContain('unique=True');
  });

  it.each(STYLES)('writes indexes and unique indexes (%s)', (style) => {
    const schema: IrSchema = thing([idField(), field('a'), field('b')], {
      indexes: [
        index(['a']),
        index(['a', 'b'], { isUnique: true }),
        index(['b'], { name: 'custom_idx' }),
        index(['b', 'a'], { name: 'custom_uq', isUnique: true }),
      ],
    });
    const text: string = code(schema, style);
    expect(text).toContain('Index("ix_things_a", "a")');
    expect(text).toContain('UniqueConstraint("a", "b", name="uq_things_a_b")');
    expect(text).toContain('Index("custom_idx", "b")');
    expect(text).toContain('UniqueConstraint("b", "a", name="custom_uq")');
  });

  it('maps relation names in an index to their columns and keeps names unique', () => {
    const schema: IrSchema = schemaOf([
      model('Owner', { tableName: 'owners' }),
      model('Thing', {
        tableName: 'things',
        relations: [relation('owner', 'Owner', { relatedName: 'things' })],
        indexes: [index(['owner']), index(['owner'])],
      }),
    ]);
    const text: string = code(schema);
    expect(text).toContain('Index("ix_things_owner_id", "owner_id")');
    expect(text).toContain('Index("ix_things_owner_id2", "owner_id")');
  });

  it('shortens a long generated index name', () => {
    const long: string = 'c'.repeat(40);
    const schema: IrSchema = thing(
      [idField(), field(long), field(`${long}2`)],
      { indexes: [index([long, `${long}2`])] }
    );
    const match: RegExpExecArray | null = /Index\("([^"]+)"/.exec(code(schema));
    expect(match?.[1]?.length).toBeLessThanOrEqual(63);
  });

  it('warns about index options it drops', () => {
    const output: EmitOutput = emit(
      thing([idField(), field('a')], {
        indexes: [
          index(['a'], { method: 'Gin' }),
          index(['a'], { kind: 'fulltext' }),
        ],
      })
    );
    expect(output.warnings).toEqual([
      'Thing index (a): the index type, clustering, sort order, prefix length and operator class options were dropped.',
      'Thing index (a): full-text indexes are not supported here; it was written as an ordinary index.',
    ]);
  });
});

describe('sqlalchemy emitter: foreign keys', () => {
  const parent: IrModel = model('Parent', { tableName: 'parents' });

  it.each([
    ['cascade', 'CASCADE'],
    ['setNull', 'SET NULL'],
    ['restrict', 'RESTRICT'],
    ['noAction', 'NO ACTION'],
    ['setDefault', 'SET DEFAULT'],
  ] as const)('writes ondelete for %s', (onDelete, sql) => {
    const schema: IrSchema = schemaOf([
      parent,
      model('Child', {
        tableName: 'children',
        relations: [
          relation('parent', 'Parent', {
            isNullable: true,
            onDelete,
            onUpdate: 'cascade',
            relatedName: 'children',
          }),
        ],
      }),
    ]);
    expect(classOf(code(schema), 'Child')).toContain(
      `parent_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("parents.id", ondelete="${sql}", onupdate="CASCADE"))`
    );
  });

  it.each(STYLES)(
    'writes the foreign key of a nullable relation (%s)',
    (style) => {
      const schema: IrSchema = schemaOf([
        parent,
        model('Child', {
          tableName: 'children',
          relations: [
            relation('parent', 'Parent', {
              isNullable: true,
              onDelete: 'setNull',
              relatedName: 'children',
            }),
          ],
        }),
      ]);
      const child: string = classOf(code(schema, style), 'Child');
      if (style === 'sqlalchemy') {
        expect(child).toContain(
          'parent_id: Mapped[Optional[int]] = mapped_column(Integer, ForeignKey("parents.id", ondelete="SET NULL"))'
        );
      } else {
        expect(child).toContain(
          'parent_id: Optional[int] = Field(default=None, foreign_key="parents.id", ondelete="SET NULL")'
        );
      }
    }
  );

  it('keeps onupdate, NO ACTION and a constraint name in a SQLModel sa_column', () => {
    const schema: IrSchema = schemaOf([
      parent,
      model('Child', {
        tableName: 'children',
        relations: [
          relation('parent', 'Parent', {
            onDelete: 'noAction',
            onUpdate: 'restrict',
            constraintName: 'fk_child_parent',
            relatedName: 'children',
          }),
        ],
      }),
    ]);
    const child: string = classOf(code(schema, 'sqlmodel'), 'Child');
    expect(child).toContain(
      'parent_id: int = Field(sa_column=Column("parent_id", Integer, ForeignKey("parents.id", ondelete="NO ACTION", onupdate="RESTRICT", name="fk_child_parent"), nullable=False))'
    );
    expect(code(schema)).toContain(
      'ForeignKey("parents.id", ondelete="NO ACTION", onupdate="RESTRICT", name="fk_child_parent")'
    );
  });

  it('writes SET NULL on a column that cannot be null as RESTRICT and warns', () => {
    const output: EmitOutput = emit(
      schemaOf([
        parent,
        model('Child', {
          tableName: 'children',
          relations: [
            relation('parent', 'Parent', {
              onDelete: 'setNull',
              relatedName: 'children',
            }),
          ],
        }),
      ])
    );
    expect(output.text).toContain('ondelete="RESTRICT"');
    expect(output.warnings).toEqual([
      'Child.parent: onDelete SetNull needs a nullable column; it was written as RESTRICT.',
    ]);
  });

  it('takes the column type from the key it references', () => {
    const schema: IrSchema = schemaOf([
      model('Org', {
        tableName: 'orgs',
        fields: [
          field('id', {
            type: 'uuid',
            isPrimaryKey: true,
            default: { kind: 'uuid' },
          }),
          field('slug', { maxLength: 12, isUnique: true }),
          field('serial', { type: 'bigInt', isUnique: true }),
        ],
      }),
      model('Member', {
        tableName: 'members',
        relations: [
          relation('org', 'Org', { relatedName: 'members' }),
          relation('by_slug', 'Org', {
            columnName: 'org_slug',
            toField: 'slug',
            relatedName: 'slug_members',
          }),
          relation('by_serial', 'Org', {
            columnName: 'org_serial',
            toField: 'serial',
            relatedName: 'serial_members',
          }),
        ],
      }),
    ]);
    const member: string = classOf(code(schema), 'Member');
    expect(member).toContain(
      'org_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("orgs.id", ondelete="CASCADE"))'
    );
    expect(member).toContain(
      'org_slug: Mapped[str] = mapped_column(String(12), ForeignKey("orgs.slug", ondelete="CASCADE"))'
    );
    expect(member).toContain(
      'org_serial: Mapped[int] = mapped_column(BigInteger, ForeignKey("orgs.serial", ondelete="CASCADE"))'
    );
  });

  it('follows a key that is itself a relation', () => {
    const schema: IrSchema = schemaOf([
      model('A', {
        tableName: 'a_rows',
        fields: [idField({ type: 'bigInt' })],
      }),
      model('B', {
        tableName: 'b_rows',
        fields: [],
        relations: [
          relation('a', 'A', {
            kind: 'oneToOne',
            columnName: 'a_ptr_id',
            isPrimaryKey: true,
            relatedName: 'b',
          }),
        ],
      }),
      model('C', {
        tableName: 'c_rows',
        relations: [relation('b', 'B', { relatedName: 'cs' })],
      }),
    ]);
    expect(classOf(code(schema), 'C')).toContain(
      'b_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("b_rows.a_ptr_id", ondelete="CASCADE"))'
    );
  });

  it('writes a composite foreign key as a ForeignKeyConstraint with its relationship', () => {
    const key: IrCompositeForeignKey = {
      name: 'order',
      targetModel: 'Order',
      fields: ['order_region', 'order_number'],
      references: ['region', 'number'],
      kind: 'foreignKey',
      isNullable: false,
      onDelete: 'cascade',
      onUpdate: 'restrict',
      relatedName: 'lines',
      constraintName: 'fk_line_order',
    };
    const schema: IrSchema = schemaOf([
      model('Order', {
        tableName: 'orders',
        fields: [
          field('region', { maxLength: 4 }),
          field('number', { type: 'int' }),
        ],
        compositePrimaryKey: ['region', 'number'],
      }),
      model('Line', {
        tableName: 'lines',
        fields: [
          idField(),
          field('order_region', { maxLength: 4 }),
          field('order_number', { type: 'int' }),
        ],
        compositeForeignKeys: [key],
      }),
    ]);
    const output: EmitOutput = emit(schema);
    const text: string = squash(output.text);
    expect(output.warnings).toEqual([]);
    expect(classOf(text, 'Line')).toContain(
      'ForeignKeyConstraint(["order_region", "order_number"], ["orders.region", "orders.number"], name="fk_line_order", ondelete="CASCADE", onupdate="RESTRICT")'
    );
    expect(classOf(text, 'Line')).toContain(
      'order: Mapped["Order"] = relationship(back_populates="lines")'
    );
    expect(classOf(text, 'Order')).toContain(
      'lines: Mapped[list["Line"]] = relationship(back_populates="order", passive_deletes=True)'
    );
    const sqlmodel: string = code(schema, 'sqlmodel');
    expect(classOf(sqlmodel, 'Line')).toContain('ForeignKeyConstraint(');
    expect(classOf(sqlmodel, 'Line')).toContain(
      'order: "Order" = Relationship(back_populates="lines")'
    );
  });

  it('keeps the columns of a composite key whose target is not a table', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Line', {
          tableName: 'lines',
          fields: [idField(), field('a'), field('b')],
          compositeForeignKeys: [
            {
              name: 'order',
              targetModel: 'Missing',
              fields: ['a', 'b'],
              references: ['x', 'y'],
              kind: 'foreignKey',
              isNullable: false,
              onDelete: 'cascade',
            },
          ],
        }),
      ])
    );
    expect(output.text).not.toContain('ForeignKeyConstraint');
    expect(output.warnings).toEqual([
      'Line.order: the target model Missing is not a mapped table; the composite foreign key was dropped and its columns kept as plain columns.',
    ]);
  });
});

describe('sqlalchemy emitter: relationships', () => {
  const owner: IrModel = model('Owner', { tableName: 'owners' });

  it.each(STYLES)('writes both sides of a foreign key (%s)', (style) => {
    const schema: IrSchema = schemaOf([
      owner,
      model('Thing', {
        tableName: 'things',
        relations: [relation('owner', 'Owner', { relatedName: 'things' })],
      }),
    ]);
    const text: string = code(schema, style);
    if (style === 'sqlalchemy') {
      expect(classOf(text, 'Thing')).toContain(
        'owner: Mapped["Owner"] = relationship(back_populates="things")'
      );
      expect(classOf(text, 'Owner')).toContain(
        'things: Mapped[list["Thing"]] = relationship(back_populates="owner", passive_deletes=True)'
      );
    } else {
      expect(classOf(text, 'Thing')).toContain(
        'owner: "Owner" = Relationship(back_populates="things")'
      );
      expect(classOf(text, 'Owner')).toContain(
        'things: list["Thing"] = Relationship(back_populates="owner", sa_relationship_kwargs={"passive_deletes": True})'
      );
    }
  });

  it('marks a nullable forward side and a one-to-one reverse side Optional', () => {
    const schema: IrSchema = schemaOf([
      owner,
      model('Profile', {
        tableName: 'profiles',
        relations: [
          relation('owner', 'Owner', {
            kind: 'oneToOne',
            isNullable: true,
            onDelete: 'setNull',
            relatedName: 'profile',
          }),
        ],
      }),
    ]);
    const text: string = code(schema);
    expect(classOf(text, 'Profile')).toContain(
      'owner: Mapped[Optional["Owner"]] = relationship(back_populates="profile")'
    );
    expect(classOf(text, 'Profile')).toContain('unique=True');
    expect(classOf(text, 'Owner')).toContain(
      'profile: Mapped[Optional["Profile"]] = relationship(back_populates="owner", passive_deletes=True)'
    );
  });

  it('names an unnamed reverse side after the plural of the model', () => {
    const schema: IrSchema = schemaOf([
      owner,
      model('Category', { tableName: 'categories' }),
      model('Box', {
        tableName: 'boxes',
        relations: [relation('owner', 'Owner'), relation('cat', 'Category')],
      }),
      model('Passport', {
        tableName: 'passports',
        relations: [relation('owner', 'Owner', { kind: 'oneToOne' })],
      }),
    ]);
    const text: string = code(schema);
    expect(classOf(text, 'Owner')).toContain('boxes: Mapped[list["Box"]]');
    expect(classOf(text, 'Owner')).toContain(
      'passport: Mapped[Optional["Passport"]]'
    );
    expect(classOf(text, 'Category')).toContain('boxes: Mapped[list["Box"]]');
  });

  it('tells apart two relations from one model to the same target', () => {
    const schema: IrSchema = schemaOf([
      owner,
      model('Post', {
        tableName: 'posts',
        relations: [
          relation('author', 'Owner'),
          relation('editor', 'Owner', {
            isNullable: true,
            onDelete: 'setNull',
          }),
        ],
      }),
    ]);
    const text: string = code(schema);
    expect(classOf(text, 'Owner')).toContain(
      'posts_author: Mapped[list["Post"]] = relationship(back_populates="author", foreign_keys="[Post.author_id]", passive_deletes=True)'
    );
    expect(classOf(text, 'Owner')).toContain(
      'posts_editor: Mapped[list["Post"]] = relationship(back_populates="editor", foreign_keys="[Post.editor_id]", passive_deletes=True)'
    );
    expect(classOf(text, 'Post')).toContain(
      'author: Mapped["Owner"] = relationship(back_populates="posts_author", foreign_keys="[Post.author_id]")'
    );
  });

  it('names foreign_keys when two tables point at each other', () => {
    const schema: IrSchema = schemaOf([
      model('A', {
        tableName: 'a_rows',
        relations: [
          relation('b', 'B', { isNullable: true, relatedName: 'a_back' }),
        ],
      }),
      model('B', {
        tableName: 'b_rows',
        relations: [
          relation('a', 'A', { isNullable: true, relatedName: 'b_back' }),
        ],
      }),
    ]);
    const text: string = code(schema);
    expect(classOf(text, 'A')).toContain('foreign_keys="[A.b_id]"');
    expect(classOf(text, 'A')).toContain('foreign_keys="[B.a_id]"');
  });

  it.each(STYLES)(
    'marks the many-to-one side of a self reference (%s)',
    (style) => {
      const schema: IrSchema = schemaOf([
        model('Node', {
          tableName: 'nodes',
          relations: [
            relation('parent', 'Node', {
              isNullable: true,
              onDelete: 'setNull',
              relatedName: 'children',
            }),
          ],
        }),
      ]);
      const node: string = classOf(code(schema, style), 'Node');
      if (style === 'sqlalchemy') {
        expect(node).toContain(
          'parent: Mapped[Optional["Node"]] = relationship(back_populates="children", remote_side="Node.id")'
        );
        expect(node).toContain(
          'children: Mapped[list["Node"]] = relationship(back_populates="parent", passive_deletes=True)'
        );
      } else {
        expect(node).toContain(
          'parent: Optional["Node"] = Relationship(back_populates="children", sa_relationship_kwargs={"remote_side": "Node.id"})'
        );
      }
    }
  );

  it('lets the database act on cascading and nulling keys only', () => {
    const schema: IrSchema = schemaOf([
      owner,
      model('Soft', {
        tableName: 'softs',
        relations: [
          relation('owner', 'Owner', {
            isNullable: true,
            onDelete: 'setNull',
            relatedName: 'softs',
          }),
        ],
      }),
      model('Hard', {
        tableName: 'hards',
        relations: [
          relation('owner', 'Owner', {
            onDelete: 'restrict',
            relatedName: 'hards',
          }),
        ],
      }),
    ]);
    const text: string = classOf(code(schema), 'Owner');
    expect(text).toContain(
      'softs: Mapped[list["Soft"]] = relationship(back_populates="owner", passive_deletes=True)'
    );
    expect(text).toContain(
      'hards: Mapped[list["Hard"]] = relationship(back_populates="owner")'
    );
  });

  it('does not write a relationship to a view or a missing model', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Report', { tableName: 'reports', isView: true }),
        model('Thing', {
          tableName: 'things',
          relations: [
            relation('report', 'Report'),
            relation('ghost', 'Ghost'),
            relation('others', 'Ghost', { kind: 'manyToMany' }),
          ],
        }),
      ])
    );
    expect(output.text).not.toContain('ForeignKey');
    expect(output.text).not.toContain('relationship(');
    expect(squash(output.text)).toContain(
      'report_id: Mapped[int] = mapped_column(Integer)'
    );
    expect(output.warnings).toEqual(
      expect.arrayContaining([
        'Thing.report: the target model Report is not a mapped table (it is missing or a view); the foreign key column was written without a ForeignKey or a relationship.',
        'Thing.ghost: the target model Ghost is not a mapped table (it is missing or a view); the foreign key column was written without a ForeignKey or a relationship.',
        'Thing.others: the target model Ghost is not a mapped table (it is missing or a view); the relation was dropped.',
      ])
    );
  });

  it('names a reverse side that collides with a column', () => {
    const schema: IrSchema = schemaOf([
      model('Owner', {
        tableName: 'owners',
        fields: [idField(), field('things')],
      }),
      model('Thing', {
        tableName: 'things',
        relations: [relation('owner', 'Owner', { relatedName: 'things' })],
      }),
    ]);
    expect(classOf(code(schema), 'Owner')).toContain(
      'things_: Mapped[list["Thing"]]'
    );
  });
});

describe('sqlalchemy emitter: many-to-many', () => {
  const tag: IrModel = model('Tag', { tableName: 'tags' });
  const post: IrModel = model('Post', {
    tableName: 'posts',
    relations: [
      relation('tags', 'Tag', {
        kind: 'manyToMany',
        columnName: 'tags_id',
        relatedName: 'posts',
      }),
    ],
  });

  it.each(STYLES)(
    'writes an association table and both sides (%s)',
    (style) => {
      const text: string = code(schemaOf([post, tag]), style);
      const metadata: string =
        style === 'sqlalchemy' ? 'Base.metadata' : 'SQLModel.metadata';
      expect(text).toContain(
        `posts_tags = Table("posts_tags", ${metadata}, Column("post_id", ForeignKey("posts.id", ondelete="CASCADE"), primary_key=True), Column("tag_id", ForeignKey("tags.id", ondelete="CASCADE"), primary_key=True))`
      );
      if (style === 'sqlalchemy') {
        expect(classOf(text, 'Post')).toContain(
          'tags: Mapped[list["Tag"]] = relationship(back_populates="posts", secondary=posts_tags)'
        );
        expect(classOf(text, 'Tag')).toContain(
          'posts: Mapped[list["Post"]] = relationship(back_populates="tags", secondary=posts_tags)'
        );
      } else {
        expect(classOf(text, 'Post')).toContain(
          'tags: list["Tag"] = Relationship(back_populates="posts", sa_relationship_kwargs={"secondary": posts_tags})'
        );
      }
    }
  );

  it('defines the association table before the classes that use it', () => {
    const text: string = emit(schemaOf([post, tag])).text;
    expect(text.indexOf('posts_tags = Table(')).toBeLessThan(
      text.indexOf('class Post(')
    );
  });

  it('names the reverse side after the plural of the model when there is no related name', () => {
    const text: string = code(
      schemaOf([
        model('Post', {
          tableName: 'posts',
          relations: [relation('tags', 'Tag', { kind: 'manyToMany' })],
        }),
        tag,
      ])
    );
    expect(classOf(text, 'Tag')).toContain('posts: Mapped[list["Post"]]');
  });

  it('joins a self reference through primaryjoin and secondaryjoin', () => {
    const schema: IrSchema = schemaOf([
      model('Group', {
        tableName: 'groups',
        relations: [
          relation('friends', 'Group', {
            kind: 'manyToMany',
            relatedName: 'friend_of',
          }),
        ],
      }),
    ]);
    const text: string = code(schema);
    expect(text).toContain('Column("from_group_id"');
    expect(text).toContain('Column("to_group_id"');
    expect(classOf(text, 'Group')).toContain(
      'friends: Mapped[list["Group"]] = relationship(back_populates="friend_of", secondary=groups_friends, primaryjoin=lambda: Group.id == groups_friends.c.from_group_id, secondaryjoin=lambda: Group.id == groups_friends.c.to_group_id)'
    );
    expect(classOf(text, 'Group')).toContain(
      'friend_of: Mapped[list["Group"]] = relationship(back_populates="friends", secondary=groups_friends, primaryjoin=lambda: Group.id == groups_friends.c.to_group_id, secondaryjoin=lambda: Group.id == groups_friends.c.from_group_id)'
    );
  });

  it('writes one table when both models list the relation', () => {
    const both: IrSchema = schemaOf([
      post,
      model('Tag', {
        tableName: 'tags',
        relations: [
          relation('posts', 'Post', {
            kind: 'manyToMany',
            relatedName: 'tags',
          }),
        ],
      }),
    ]);
    const output: EmitOutput = emit(both);
    expect(output.text.match(/= Table\(/g)).toHaveLength(1);
    expect(output.text.match(/secondary=/g)).toHaveLength(2);
    expect(output.warnings).toEqual([]);
  });

  it('references the type of a non-integer key', () => {
    const text: string = code(
      schemaOf([
        model('Post', {
          tableName: 'posts',
          fields: [
            field('id', {
              type: 'uuid',
              isPrimaryKey: true,
              default: { kind: 'uuid' },
            }),
          ],
          relations: [relation('tags', 'Tag', { kind: 'manyToMany' })],
        }),
        model('Tag', {
          tableName: 'tags',
          fields: [field('slug', { isPrimaryKey: true, maxLength: 8 })],
        }),
      ])
    );
    expect(text).toContain('Column("post_id", ForeignKey("posts.id"');
    expect(text).toContain('Column("tag_id", ForeignKey("tags.slug"');
  });

  it('warns when a model has no key to reference', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Post', {
          tableName: 'posts',
          fields: [field('title')],
          relations: [relation('tags', 'Tag', { kind: 'manyToMany' })],
        }),
        tag,
      ])
    );
    expect(output.warnings).toContain(
      'Post.tags: Post has no single-column primary key; the association table column references posts.id.'
    );
  });
});

describe('sqlalchemy emitter: enums', () => {
  const schema = (): IrSchema =>
    schemaOf(
      [
        model('Thing', {
          tableName: 'things',
          fields: [idField(), field('status', { enumName: 'Status' })],
        }),
      ],
      [STATUS]
    );

  it('writes an enum.Enum class and binds it with the stored values', () => {
    const output: EmitOutput = emit(schema());
    expect(output.text).toContain(
      'class Status(enum.Enum):\n    DRAFT = "draft"\n    LIVE = "live"\n'
    );
    expect(squash(output.text)).toContain(
      'status: Mapped[Status] = mapped_column(Enum(Status, name="Status", values_callable=lambda members: [member.value for member in members]))'
    );
    expect(output.text).toContain('import enum\n');
    expect(output.warnings).toEqual([]);
  });

  it('writes the enum with sa_type in SQLModel', () => {
    expect(code(schema(), 'sqlmodel')).toContain(
      'status: Status = Field(sa_type=Enum(Status, name="Status", values_callable=lambda members: [member.value for member in members]))'
    );
  });

  it('names the database type after dbName, snake_case when normalizing', () => {
    const named: IrSchema = schema();
    named.enums = [{ ...STATUS, dbName: 'StatusType' }];
    expect(code(named)).toContain('name="StatusType"');
    expect(code(named, 'sqlalchemy', 'normalize')).toContain(
      'name="status_type"'
    );
  });

  it('repairs member names that are not Python identifiers', () => {
    const odd: IrEnum = {
      name: 'Odd',
      values: [
        { name: 'class', dbValue: 'a' },
        { name: '1st', dbValue: 'b' },
        { name: 'two words', dbValue: 'c' },
        { name: 'name', dbValue: 'd' },
        { name: '_hidden_', dbValue: 'e' },
        { name: 'dup', dbValue: 'f' },
        { name: 'dup', dbValue: 'g' },
        { name: 'ok', dbValue: 'it"s' },
      ],
    };
    const output: EmitOutput = emit(
      schemaOf(
        [
          model('Thing', {
            tableName: 'things',
            fields: [idField(), field('odd', { enumName: 'Odd' })],
          }),
        ],
        [odd]
      )
    );
    expect(output.text).toContain(
      [
        'class Odd(enum.Enum):',
        '    class_ = "a"',
        '    v_1st = "b"',
        '    two_words = "c"',
        '    name_ = "d"',
        '    v_hidden_ = "e"',
        '    dup = "f"',
        '    dup2 = "g"',
        '    ok = "it\\"s"',
      ].join('\n')
    );
    expect(output.warnings).toContain(
      'enum Odd: the member "class" was written as class_.'
    );
    expect(output.warnings).toContain(
      'enum Odd: the member "dup" was written as dup2.'
    );
  });

  it('renames an enum that collides with a model or an import', () => {
    const output: EmitOutput = emit(
      schemaOf(
        [
          model('Other', { tableName: 'others' }),
          model('Thing', {
            tableName: 'things',
            fields: [
              idField(),
              field('a', { enumName: 'Other' }),
              field('b', { enumName: 'Enum' }),
              field('c', { enumName: 'my enum' }),
            ],
          }),
        ],
        [
          { name: 'Other', values: [{ name: 'A', dbValue: 'a' }] },
          { name: 'Enum', values: [{ name: 'A', dbValue: 'a' }] },
          { name: 'my enum', values: [{ name: 'A', dbValue: 'a' }] },
        ]
      )
    );
    expect(output.text).toContain('class OtherEnum(enum.Enum):');
    expect(output.text).toContain('class EnumEnum(enum.Enum):');
    expect(output.text).toContain('class MyEnum(enum.Enum):');
    expect(output.warnings).toContain(
      'enum Other: the Python class was named OtherEnum.'
    );
  });

  it('writes a field of an enum without values as a string and warns', () => {
    const output: EmitOutput = emit(
      schemaOf(
        [
          model('Thing', {
            tableName: 'things',
            fields: [idField(), field('kind', { enumName: 'Empty' })],
          }),
        ],
        [{ name: 'Empty', values: [] }]
      )
    );
    expect(output.text).toContain('kind: Mapped[str] = mapped_column(String)');
    expect(output.warnings).toEqual([
      'enum Empty: an enum without values cannot be written; fields that use it became plain strings.',
    ]);
  });

  it('writes an array of enums', () => {
    const text: string = code(
      schemaOf(
        [
          model('Thing', {
            tableName: 'things',
            fields: [
              idField(),
              field('statuses', { enumName: 'Status', arrayDepth: 1 }),
            ],
          }),
        ],
        [STATUS]
      )
    );
    expect(text).toContain(
      'statuses: Mapped[list[Status]] = mapped_column(ARRAY(Enum(Status'
    );
  });
});

describe('sqlalchemy emitter: identifiers', () => {
  it('turns names into snake_case attributes and keeps the column name', () => {
    const output: EmitOutput = emit(
      thing([
        idField(),
        field('firstName', { columnName: 'FirstName' }),
        field('HTTPCode', { columnName: 'http_code', type: 'int' }),
        field('first-name', { columnName: 'first name', isNullable: true }),
      ])
    );
    expect(output.text).toContain(
      'first_name: Mapped[str] = mapped_column("FirstName", String)'
    );
    expect(output.text).toContain(
      'http_code: Mapped[int] = mapped_column(Integer)'
    );
    expect(output.text).toContain(
      'first_name_: Mapped[Optional[str]] = mapped_column("first name", String)'
    );
    expect(output.warnings).toEqual([
      'Thing.first-name: the name "first-name" collides with another attribute of the class or a name used by the module; it was written as first_name_.',
    ]);
  });

  it.each([
    ['class', 'class_'],
    ['from', 'from_'],
    ['None', 'none'],
    ['metadata', 'metadata_'],
    ['registry', 'registry_'],
    ['text', 'text_'],
    ['datetime', 'datetime_'],
    ['uuid', 'uuid_'],
    ['func', 'func_'],
    ['list', 'list_'],
    ['str', 'str_'],
    ['Mapped', 'mapped'],
  ])(
    'does not let the attribute %s shadow a name of the class body',
    (name, written) => {
      const output: EmitOutput = emit(thing([idField(), field(name)]));
      expect(output.text).toContain(`    ${written}: Mapped[str]`);
    }
  );

  it('keeps the original column name when an attribute is renamed', () => {
    expect(emit(thing([idField(), field('class')])).text).toContain(
      'class_: Mapped[str] = mapped_column("class", String)'
    );
    expect(emit(thing([idField(), field('class')]), 'sqlmodel').text).toContain(
      'class_: str = Field(sa_column_kwargs={"name": "class"})'
    );
  });

  it('avoids the names pydantic and SQLModel reserve', () => {
    const text: string = emit(
      thing([idField(), field('json'), field('copy'), field('schema')]),
      'sqlmodel'
    ).text;
    expect(text).toContain('    json_: str');
    expect(text).toContain('    copy_: str');
    expect(text).toContain('    schema_: str');
    expect(emit(thing([idField(), field('json')])).text).toContain(
      '    json: Mapped[str]'
    );
  });

  it('gives a name that is empty or starts with a digit a usable attribute', () => {
    const text: string = emit(
      thing([idField(), field('2fa'), field('$'), field('__x__')])
    ).text;
    expect(text).toContain('    field_2fa: Mapped[str]');
    expect(text).toContain(
      '    field: Mapped[str] = mapped_column("$", String)'
    );
    expect(text).toContain(
      '    x: Mapped[str] = mapped_column("__x__", String)'
    );
  });

  it('repairs class names', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Index', { tableName: 'indexes' }),
        model('String', { tableName: 'strings' }),
        model('Base', { tableName: 'bases' }),
        model('my model', { tableName: 'my_models' }),
        model('3d', { tableName: 'threed' }),
        model('list', { tableName: 'lists' }),
        model('legacy_order', { tableName: 'legacy' }),
      ])
    );
    for (const name of [
      'IndexModel',
      'StringModel',
      'BaseModel',
      'MyModel',
      'Model3d',
      'listModel',
      'legacy_order',
    ]) {
      expect(output.text).toContain(`class ${name}(Base):`);
    }
    expect(output.warnings).toContain(
      'Index: the name collides with a Python or SQLAlchemy name used by the module; the class was written as IndexModel.'
    );
    expect(output.warnings).toContain(
      'my model: not a valid Python class name; the class was written as MyModel.'
    );
  });

  it('refers to a renamed class in relationships', () => {
    const schema: IrSchema = schemaOf([
      model('Index', { tableName: 'indexes' }),
      model('Thing', {
        tableName: 'things',
        relations: [relation('index', 'Index', { relatedName: 'things' })],
      }),
    ]);
    const text: string = code(schema);
    expect(text).toContain(
      'index: Mapped["IndexModel"] = relationship(back_populates="things")'
    );
    expect(text).toContain(
      'things: Mapped[list["Thing"]] = relationship(back_populates="index", passive_deletes=True)'
    );
  });

  it('keeps a column attribute off the name of an enum class', () => {
    const output: EmitOutput = emit(
      schemaOf(
        [
          model('Thing', {
            tableName: 'things',
            fields: [idField(), field('color', { enumName: 'color' })],
          }),
        ],
        [{ name: 'color', values: [{ name: 'RED', dbValue: 'red' }] }]
      )
    );
    expect(squash(output.text)).toContain(
      '    color_: Mapped[color] = mapped_column("color", Enum(color'
    );
  });

  it('names the foreign-key column apart from a relationship of the same name', () => {
    const schema: IrSchema = schemaOf([
      model('Series', { tableName: 'series' }),
      model('Row', {
        tableName: 'rows',
        relations: [
          relation('table', 'Series', {
            columnName: 'table',
            relatedName: 'rows',
          }),
        ],
      }),
    ]);
    const row: string = classOf(code(schema), 'Row');
    expect(row).toContain(
      'table_id: Mapped[int] = mapped_column("table", Integer'
    );
    expect(row).toContain('table: Mapped["Series"] = relationship(');
  });

  it('keeps an association table variable off every attribute name', () => {
    const schema: IrSchema = schemaOf([
      model('Post', {
        tableName: 'posts',
        fields: [idField(), field('posts_tags')],
        relations: [relation('tags', 'Tag', { kind: 'manyToMany' })],
      }),
      model('Tag', { tableName: 'tags' }),
    ]);
    const text: string = code(schema);
    expect(text).toContain('posts_tags2 = Table("posts_tags"');
    expect(text).toContain('secondary=posts_tags2');
  });
});

describe('sqlalchemy emitter: ordering', () => {
  it('writes a class after the classes its foreign keys point at', () => {
    const schema: IrSchema = schemaOf([
      model('C', {
        tableName: 'c',
        relations: [relation('b', 'B', { relatedName: 'cs' })],
      }),
      model('B', {
        tableName: 'b',
        relations: [relation('a', 'A', { relatedName: 'bs' })],
      }),
      model('A', { tableName: 'a' }),
    ]);
    const text: string = emit(schema).text;
    const positions: number[] = ['A', 'B', 'C'].map((name: string) =>
      text.indexOf(`class ${name}(`)
    );
    expect(positions).toEqual([...positions].sort((x, y) => x - y));
    expect(positions.every((position: number) => position > 0)).toBe(true);
  });

  it('writes every class of a cycle once', () => {
    const schema: IrSchema = schemaOf([
      model('A', {
        tableName: 'a',
        relations: [
          relation('b', 'B', { isNullable: true, relatedName: 'as_' }),
        ],
      }),
      model('B', {
        tableName: 'b',
        relations: [
          relation('a', 'A', { isNullable: true, relatedName: 'bs' }),
        ],
      }),
    ]);
    const text: string = emit(schema).text;
    expect(text.match(/^class A\(/gm)).toHaveLength(1);
    expect(text.match(/^class B\(/gm)).toHaveLength(1);
  });

  it('writes enums, then association tables, then classes', () => {
    const text: string = emit(
      schemaOf(
        [
          model('Post', {
            tableName: 'posts',
            fields: [idField(), field('status', { enumName: 'Status' })],
            relations: [relation('tags', 'Tag', { kind: 'manyToMany' })],
          }),
          model('Tag', { tableName: 'tags' }),
        ],
        [STATUS]
      )
    ).text;
    expect(text.indexOf('class Base(')).toBeLessThan(
      text.indexOf('class Status(')
    );
    expect(text.indexOf('class Status(')).toBeLessThan(
      text.indexOf('posts_tags = Table(')
    );
    expect(text.indexOf('posts_tags = Table(')).toBeLessThan(
      text.indexOf('class Post(')
    );
  });
});

describe('sqlalchemy emitter: views and other constructs', () => {
  it.each(STYLES)('writes a view as a comment and warns (%s)', (style) => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Thing', { tableName: 'things' }),
        model('Summary', {
          tableName: 'summary_view',
          isView: true,
          fields: [field('id', { type: 'int' }), field('title')],
        }),
      ]),
      style
    );
    expect(output.text).toContain(
      '# View Summary (summary_view) is not mapped: SQLAlchemy has no declarative view construct.'
    );
    expect(output.text).toContain(
      `#     Table("summary_view", ${style === 'sqlalchemy' ? 'Base' : 'SQLModel'}.metadata, autoload_with=engine)`
    );
    expect(output.text).toContain('# Columns: id, title');
    expect(output.text).not.toContain('class Summary');
    expect(output.warnings).toEqual([
      `Summary: this is a database view; SQLAlchemy has no declarative view, so it was written as a comment. Create the view in the database and reflect it (Table("summary_view", ${style === 'sqlalchemy' ? 'Base' : 'SQLModel'}.metadata, autoload_with=engine)).`,
    ]);
  });

  it('keeps the Prisma-only warnings that still apply', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Thing', {
          tableName: 'things',
          schema: 'audit',
          isIgnored: true,
          fields: [
            idField(),
            field('internal', { isIgnored: true }),
            field('token', {
              default: {
                kind: 'dbExpression',
                expression: 'gen_random_uuid()',
              },
            }),
          ],
        }),
      ])
    );
    expect(output.warnings).toEqual([
      'Thing: @@ignore has no equivalent here; the model was written as a normal model.',
      'Thing: the database schema "audit" (@@schema) was ignored.',
      'Thing.internal: @ignore has no equivalent here; the field was written as a normal field.',
    ]);
    expect(squash(output.text)).toContain(
      'server_default=text("gen_random_uuid()")'
    );
  });

  it('writes the onUpdate action instead of dropping it', () => {
    const output: EmitOutput = emit(
      schemaOf([
        model('Owner', { tableName: 'owners' }),
        model('Thing', {
          tableName: 'things',
          relations: [
            relation('owner', 'Owner', {
              onUpdate: 'cascade',
              relatedName: 'things',
            }),
          ],
        }),
      ])
    );
    expect(output.warnings).toEqual([]);
    expect(squash(output.text)).toContain('onupdate="CASCADE"');
  });
});

describe('sqlalchemy emitter: naming modes', () => {
  const blog = (): IrSchema =>
    schemaOf(
      [
        model('Post', {
          tableName: 'blog_posts',
          fields: [
            idField(),
            field('Title', { columnName: 'Title', maxLength: 10 }),
            field('status', { enumName: 'Status' }),
          ],
          relations: [
            relation('author', 'Author', {
              columnName: 'AuthorId',
              relatedName: 'posts',
            }),
            relation('tags', 'Tag', { kind: 'manyToMany' }),
          ],
        }),
        model('Author', { tableName: 'blog_authors' }),
        model('Tag', { tableName: 'blog_tags' }),
      ],
      [STATUS]
    );

  it('preserve keeps table, column and enum type names', () => {
    const text: string = code(blog());
    expect(text).toContain('__tablename__ = "blog_posts"');
    expect(text).toContain('mapped_column("Title", String(10))');
    expect(text).toContain('name="Status"');
    expect(text).toContain('"blog_posts_tags"');
    expect(text).toContain('"AuthorId"');
    expect(text).not.toContain('created_at');
  });

  it('normalize uses singular snake_case tables, UUID keys, snake_case columns and timestamps', () => {
    const text: string = code(blog(), 'sqlalchemy', 'normalize');
    expect(text).toContain('__tablename__ = "post"');
    expect(text).toContain('__tablename__ = "author"');
    expect(text).toContain(
      'id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)'
    );
    expect(text).toContain('title: Mapped[str] = mapped_column(String(10))');
    expect(text).toContain('author_id: Mapped[uuid.UUID]');
    expect(text).toContain('ForeignKey("author.id"');
    expect(text).toContain('name="status"');
    expect(text).toContain('"post_tags"');
    expect(text).toContain('created_at: Mapped[datetime.datetime]');
    expect(text).toContain('onupdate=func.now()');
  });

  it('applies the naming mode to SQLModel too', () => {
    const text: string = code(blog(), 'sqlmodel', 'normalize');
    expect(text).toContain('__tablename__ = "post"');
    expect(text).toContain(
      'id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)'
    );
  });
});

describe('sqlalchemy emitter: the format adapter', () => {
  it('is registered for writing, without an extension', () => {
    const adapter = expectOk(getFormat('sqlalchemy'));
    expect(adapter.extensions).toEqual([]);
    expect(adapter.emit).toBeDefined();
    expect(adapter.description).toContain('SQLModel');
    expect(listFormats().map((format) => format.name)).toContain('sqlalchemy');
  });

  it('is listed by the formats command', () => {
    expect(describeFormats(listFormats())).toMatch(
      /sqlalchemy\s+extensions: \(none\)\s+(read \+ )?write\s+SQLAlchemy 2\.0/
    );
  });

  it('writes SQLAlchemy by default and SQLModel for the sqlmodel style', () => {
    const adapter = expectOk(getFormat('sqlalchemy'));
    const schema: IrSchema = thing([idField()]);
    const plain = expectOk(
      adapter.emit?.(schema, DEFAULT_OPTIONS) ?? {
        ok: false as const,
        error: { code: 'EMIT_FAILED' as const, message: 'no emit' },
      }
    );
    expect(plain.text).toContain('class Thing(Base):');
    const sqlmodel = expectOk(
      adapter.emit?.(schema, { ...DEFAULT_OPTIONS, style: 'sqlmodel' }) ?? {
        ok: false as const,
        error: { code: 'EMIT_FAILED' as const, message: 'no emit' },
      }
    );
    expect(sqlmodel.text).toContain('class Thing(SQLModel, table=True):');
  });

  it('rejects an unknown style with the valid values', () => {
    const adapter = expectOk(getFormat('sqlalchemy'));
    const result = adapter.emit?.(thing([idField()]), {
      ...DEFAULT_OPTIONS,
      style: 'peewee' as SqlAlchemyStyle,
    });
    expect(result?.ok).toBe(false);
    if (result !== undefined && !result.ok) {
      expect(result.error.code).toBe('INVALID_OPTION');
      expect(result.error.message).toBe(
        'Invalid style "peewee". Expected one of: sqlalchemy, sqlmodel.'
      );
    }
  });

  it('recognises the style names', () => {
    expect(SQLALCHEMY_STYLES).toEqual(['sqlalchemy', 'sqlmodel']);
    expect(isSqlAlchemyStyle('sqlmodel')).toBe(true);
    expect(isSqlAlchemyStyle('django')).toBe(false);
  });

  it('converts through convertText with and without --style', async () => {
    const source = {
      path: 'schema.prisma',
      text: 'model Note {\n  id Int @id @default(autoincrement())\n  body String\n}\n',
    };
    const plain = expectOk(
      await convertText([source], {
        ...DEFAULT_OPTIONS,
        from: 'prisma',
        to: 'sqlalchemy',
      })
    );
    expect(plain.output).toContain('class Note(Base):');
    const sqlmodel = expectOk(
      await convertText([source], {
        ...DEFAULT_OPTIONS,
        from: 'prisma',
        to: 'sqlalchemy',
        style: 'sqlmodel',
      })
    );
    expect(sqlmodel.output).toContain('class Note(SQLModel, table=True):');
    expect(sqlmodel.files).toBeUndefined();
  });
});

describe('sqlalchemy emitter: the structural coverage check', () => {
  const schema = (): IrSchema =>
    schemaOf(
      [
        model('Parent', { tableName: 'parents' }),
        model('Child', {
          tableName: 'children',
          fields: [idField(), field('name', { isUnique: false })],
          relations: [
            relation('parent', 'Parent', { relatedName: 'children' }),
            relation('tags', 'Tag', { kind: 'manyToMany' }),
          ],
          indexes: [
            index(['name']),
            index(['name', 'parent'], { isUnique: true }),
          ],
        }),
        model('Tag', { tableName: 'tags' }),
        model('Summary', { tableName: 'summaries', isView: true }),
      ],
      [STATUS]
    );

  it('finds nothing missing in the emitter output', () => {
    const text: string = emit(schema()).text;
    expect(checkSqlAlchemyOutput(schema(), { sqlalchemy: text })).toEqual([]);
  });

  it('lists what is missing', () => {
    const text: string = emit(schema()).text;
    const stripped: string = text
      .replace(/ForeignKey\([^)]*\)/g, '')
      .replace('secondary=', 'x=')
      .replace('__tablename__ = "tags"', '__tablename__ = "other"')
      .replace('Index(', 'Idx(')
      .replace('# View Summary (', '# View Summary [')
      .replace('class Status(enum.Enum)', 'class Gone(enum.Enum)');
    const missing: string[] = checkSqlAlchemyOutput(schema(), {
      sqlalchemy: stripped,
    });
    expect(missing).toEqual(
      expect.arrayContaining([
        'Child.parent: no ForeignKey to parents',
        'Child.tags: no relationship with secondary=',
        'Tag: no class for table tags',
        'Child index (name): no Index',
        'Summary: no view placeholder',
        'enum Status: no enum.Enum class',
      ])
    );
    expect(checkSqlAlchemyOutput(schema(), {})).toEqual(['no output']);
    expect(checkSqlAlchemyOutput(schema(), { sqlalchemy: 'x' })).toContain(
      'no Base(DeclarativeBase) class'
    );
  });
});

describe('sqlalchemy emitter: the output is valid Python', () => {
  const python: string = sqlalchemyPython();
  const check = spawnSync(python, ['-I', '-c', 'import ast'], {
    encoding: 'utf8',
  });
  const available: boolean = check.error === undefined && check.status === 0;

  const schemas: [string, () => IrSchema][] = [
    ['kitchen sink', kitchenSinkSchema],
    ['stress', stressSchema],
    ['constructs', constructsSchema],
  ];

  describe.each(schemas)('%s fixture', (_label, build) => {
    it
      .skipIf(!available)
      .each(
        STYLES.flatMap((style: SqlAlchemyStyle) =>
          (['preserve', 'normalize'] as const).map(
            (naming) => [style, naming] as const
          )
        )
      )(
      'parses as Python (%s, %s naming)',
      (style, naming) => {
        const text: string = emit(build(), style, naming).text;
        const run = spawnSync(
          python,
          ['-I', '-c', 'import ast, sys; ast.parse(sys.stdin.read())'],
          { encoding: 'utf8', input: text }
        );
        expect(run.stderr).toBe('');
        expect(run.status).toBe(0);
      },
      30_000
    );
  });
});

describe('sqlalchemy emitter: golden files', () => {
  const goldenRoot: string = fileURLToPath(
    new URL('./golden-extras/', import.meta.url)
  );

  // The default (sqlalchemy style) conversions live in test/golden/<format>-to-sqlalchemy.<naming>.txt
  // (conversion.test.ts). The SQLModel output of every canonical schema is checked here.
  describe.each(
    CANONICAL_FIXTURES.map((fixture) => fixture.format).filter(
      (format: string) => format !== 'sqlalchemy'
    )
  )('%s source as SQLModel', (format) => {
    it('matches the golden output', async () => {
      const files: Record<string, string> = {};
      for (const naming of ['preserve', 'normalize'] as const) {
        const result = await convertCanonical(format, 'sqlalchemy', {
          naming,
          style: 'sqlmodel',
        });
        files[`${naming}.py`] = result.output;
        files[`${naming}.warnings.txt`] = `${result.warnings.join('\n')}\n`;
      }
      expectFilesMatchGolden(
        `sqlmodel/${format}-to-sqlalchemy`,
        files,
        goldenRoot
      );
    });
  });

  const fixtures: [string, () => Promise<IrSchema>][] = [
    ...EXTRA_SOURCES.map((source): [string, () => Promise<IrSchema>] => [
      source.label,
      () => parseSource(source),
    ]),
    ...SQLALCHEMY_IR_FIXTURES.map(
      ([label, build]): [string, () => Promise<IrSchema>] => [
        label,
        () => Promise.resolve(build()),
      ]
    ),
  ];

  describe.each(fixtures)('%s fixture', (label, build) => {
    it('matches the golden output in both styles and naming modes', async () => {
      const schema: IrSchema = await build();
      const files: Record<string, string> = {};
      for (const style of STYLES) {
        for (const naming of ['preserve', 'normalize'] as const) {
          const output: EmitOutput = emit(
            structuredClone(schema),
            style,
            naming
          );
          files[`${style}.${naming}.py`] = output.text;
          files[`${style}.${naming}.warnings.txt`] =
            `${output.warnings.join('\n')}\n`;
        }
      }
      expectFilesMatchGolden(`sqlalchemy-fixtures/${label}`, files, goldenRoot);
    });
  });
});
