# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Table,
    Text,
    UniqueConstraint,
    false,
    func,
    text,
)
from sqlmodel import Field, Relationship, SQLModel


class PostStatus(enum.Enum):
    Draft = "draft"
    Published = "published"


blog_post_tags = Table(
    "blog_post_tags",
    SQLModel.metadata,
    Column("post_id", ForeignKey("blog_post.id", ondelete="CASCADE"), primary_key=True),
    Column("tag_id", ForeignKey("blog_tag.id", ondelete="CASCADE"), primary_key=True),
)


class Category(SQLModel, table=True):
    __tablename__ = "blog_category"

    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(unique=True, max_length=100)
    slug: str = Field(max_length=50)
    parent_id: Optional[int] = Field(
        default=None,
        foreign_key="blog_category.id",
        ondelete="SET NULL",
    )

    parent: Optional["Category"] = Relationship(
        back_populates="children",
        sa_relationship_kwargs={"remote_side": "Category.id"},
    )
    children: list["Category"] = Relationship(
        back_populates="parent",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    posts: list["Post"] = Relationship(back_populates="category")


class User(SQLModel, table=True):
    __tablename__ = "auth_user"

    id: Optional[int] = Field(default=None, primary_key=True)

    posts: list["Post"] = Relationship(
        back_populates="author",
        sa_relationship_kwargs={
            "foreign_keys": "[Post.author_id]",
            "passive_deletes": True,
        },
    )
    edited_posts: list["Post"] = Relationship(
        back_populates="editor",
        sa_relationship_kwargs={
            "foreign_keys": "[Post.editor_id]",
            "passive_deletes": True,
        },
    )
    profile: Optional["Profile"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Post(SQLModel, table=True):
    __tablename__ = "blog_post"
    __table_args__ = (
        Index("ix_blog_post_title", "title"),
        UniqueConstraint("author_id", "title", name="uniq_post_author_title"),
        Index("post_pub_status_idx", "published_at", "status"),
    )

    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    id: Optional[int] = Field(default=None, primary_key=True)
    public_id: uuid.UUID = Field(default_factory=uuid.uuid4, unique=True)
    title: str = Field(max_length=200)
    body: str = Field(sa_type=Text)
    status: PostStatus = Field(
        default=PostStatus.Draft,
        sa_type=Enum(
            PostStatus,
            name="PostStatus",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "draft"},
    )
    rating: Optional[decimal.Decimal] = Field(
        default=None,
        max_digits=4,
        decimal_places=2,
    )
    view_count: int = Field(default=0, sa_column_kwargs={"server_default": text("0")})
    is_featured: bool = Field(
        default=False,
        sa_column_kwargs={"server_default": false()},
    )
    published_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    metadata_: Any = Field(
        default_factory=dict,
        sa_type=JSON,
        sa_column_kwargs={"name": "metadata", "server_default": text("'{}'")},
    )
    author_id: int = Field(foreign_key="auth_user.id", ondelete="CASCADE")
    editor_id: Optional[int] = Field(
        default=None,
        foreign_key="auth_user.id",
        ondelete="SET NULL",
    )
    category_id: int = Field(foreign_key="blog_category.id", ondelete="RESTRICT")

    author: "User" = Relationship(
        back_populates="posts",
        sa_relationship_kwargs={"foreign_keys": "[Post.author_id]"},
    )
    editor: Optional["User"] = Relationship(
        back_populates="edited_posts",
        sa_relationship_kwargs={"foreign_keys": "[Post.editor_id]"},
    )
    category: "Category" = Relationship(back_populates="posts")
    tags: list["Tag"] = Relationship(
        back_populates="posts",
        sa_relationship_kwargs={"secondary": blog_post_tags},
    )


class Tag(SQLModel, table=True):
    __tablename__ = "blog_tag"

    id: Optional[int] = Field(default=None, primary_key=True)
    label: str = Field(max_length=50)

    posts: list["Post"] = Relationship(
        back_populates="tags",
        sa_relationship_kwargs={"secondary": blog_post_tags},
    )


class Profile(SQLModel, table=True):
    __tablename__ = "blog_profile"

    id: Optional[int] = Field(default=None, primary_key=True)
    bio: Optional[str] = Field(default=None, sa_type=Text)
    avatar: Optional[str] = Field(default=None, max_length=100)
    user_id: int = Field(foreign_key="auth_user.id", ondelete="CASCADE", unique=True)

    user: "User" = Relationship(back_populates="profile")
