-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TYPE color_t AS ENUM ('red', 'green');

CREATE TYPE status AS ENUM ('draft', 'live');

CREATE TABLE series (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  handle VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  parent_id UUID,
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
);

CREATE TABLE book (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  title VARCHAR(120) NOT NULL,
  tags TEXT[] NOT NULL DEFAULT '{}',
  grid INTEGER[][],
  colors color_t[],
  color color_t NOT NULL DEFAULT 'red',
  price NUMERIC(8, 2) NOT NULL DEFAULT 9.99,
  settings JSONB NOT NULL DEFAULT '{"theme":"dark","tabs":[1,2]}'::jsonb,
  published_on DATE NOT NULL DEFAULT CURRENT_DATE,
  opens_at TIME,
  released_at TIMESTAMPTZ DEFAULT '2020-01-02T03:04:05.000Z',
  pages INTEGER NOT NULL DEFAULT 100,
  ratio DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  "window" INT4RANGE,
  extra HSTORE,
  read_time INTERVAL,
  cover BYTEA,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  author_id UUID NOT NULL,
  editor_id UUID,
  series_handle VARCHAR(20),
  CONSTRAINT book_pkey PRIMARY KEY (id),
  CONSTRAINT book_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
);
CREATE UNIQUE INDEX book_title_author_id_key ON book (title, author_id);
CREATE INDEX books_published_idx ON book (published_on);

CREATE TABLE author (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  latest_book_id UUID,
  CONSTRAINT author_pkey PRIMARY KEY (id),
  CONSTRAINT author_handle_key UNIQUE (handle),
  CONSTRAINT author_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES book (id) ON DELETE SET NULL
);

CREATE TABLE audiobook (
  minutes INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  book_ptr_id UUID NOT NULL,
  CONSTRAINT audiobook_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobook_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES book (id) ON DELETE CASCADE
);

CREATE TABLE "index" (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  "sql" TEXT,
  class TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  "table" UUID,
  CONSTRAINT index_pkey PRIMARY KEY (id),
  CONSTRAINT index_table_fkey FOREIGN KEY ("table") REFERENCES series (id)
);

CREATE TABLE tagged (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
);

CREATE TABLE tagged_book (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  tagged_id UUID NOT NULL,
  book_id UUID NOT NULL,
  CONSTRAINT tagged_book_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_book_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_book_book_id_fkey FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX tagged_book_tagged_id_book_id_key ON tagged_book (tagged_id, book_id);

-- These foreign keys close a reference cycle, so they are added once every table exists.

ALTER TABLE book ADD CONSTRAINT book_author_id_fkey FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE book ADD CONSTRAINT book_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES author (id) ON DELETE SET NULL;
