-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TYPE color_t AS ENUM ('red', 'green');

CREATE TYPE "Status" AS ENUM ('draft', 'live');

CREATE TABLE series (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  handle VARCHAR(20) NOT NULL,
  parent_id INTEGER,
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
);

CREATE TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title VARCHAR(120) NOT NULL,
  tags TEXT[] NOT NULL DEFAULT '{}',
  grid INTEGER[][],
  colors color_t[],
  color color_t NOT NULL DEFAULT 'red',
  price NUMERIC(8, 2) NOT NULL DEFAULT 9.99,
  settings JSONB NOT NULL DEFAULT '{"theme":"dark","tabs":[1,2]}'::jsonb,
  published_on DATE NOT NULL DEFAULT CURRENT_DATE,
  opens_at TIME,
  released_at TIMESTAMPTZ DEFAULT '2020-01-02T03:04:05.000Z',
  pages INTEGER NOT NULL DEFAULT 100,
  ratio DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT TRUE,
  notes TEXT,
  "window" INT4RANGE,
  extra HSTORE,
  read_time INTERVAL,
  cover BYTEA,
  author_id UUID NOT NULL,
  editor_id UUID,
  series_handle VARCHAR(20),
  CONSTRAINT books_pkey PRIMARY KEY (id),
  CONSTRAINT books_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
);
CREATE UNIQUE INDEX books_title_author_id_key ON books (title, author_id);
CREATE INDEX books_published_idx ON books (published_on);

CREATE TABLE authors (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INTEGER,
  latest_book_id BIGINT,
  CONSTRAINT authors_pkey PRIMARY KEY (id),
  CONSTRAINT authors_handle_key UNIQUE (handle),
  CONSTRAINT authors_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES books (id) ON DELETE SET NULL
);

CREATE TABLE audiobooks (
  minutes INTEGER NOT NULL,
  book_ptr_id BIGINT NOT NULL,
  CONSTRAINT audiobooks_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobooks_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES books (id) ON DELETE CASCADE
);

CREATE TABLE index_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sql" TEXT,
  class TEXT,
  "table" INTEGER,
  CONSTRAINT index_rows_pkey PRIMARY KEY (id),
  CONSTRAINT index_rows_table_fkey FOREIGN KEY ("table") REFERENCES series (id)
);

CREATE TABLE tagged (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
);

CREATE TABLE tagged_books (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tagged_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  CONSTRAINT tagged_books_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_books_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_books_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX tagged_books_tagged_id_book_id_key ON tagged_books (tagged_id, book_id);

-- These foreign keys close a reference cycle, so they are added once every table exists.

ALTER TABLE books ADD CONSTRAINT books_author_id_fkey FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE books ADD CONSTRAINT books_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES authors (id) ON DELETE SET NULL;
