-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE item (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  first_name NVARCHAR(40) NOT NULL,
  last_name NVARCHAR(40) NOT NULL,
  full_name NVARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INT NOT NULL DEFAULT 1,
  total_cents INT NOT NULL, -- generated column written as a regular column
  tags NVARCHAR(MAX) NOT NULL DEFAULT N'[]', -- an array stored as JSON
  grid NVARCHAR(MAX) NULL, -- an array stored as JSON
  kinds NVARCHAR(MAX) NOT NULL DEFAULT N'[]', -- an array stored as JSON
  attributes NVARCHAR(MAX) NOT NULL DEFAULT N'{}', -- hstore stored as JSON
  stock_range NVARCHAR(255) NULL, -- range stored as text
  big_range NVARCHAR(255) NULL, -- range stored as text
  price_range NVARCHAR(255) NULL, -- range stored as text
  available NVARCHAR(255) NULL, -- range stored as text
  valid_during NVARCHAR(255) NULL, -- range stored as text
  last_ip VARCHAR(45) NULL,
  legacy_ip VARCHAR(45) NULL,
  shelf_life BIGINT NULL, -- duration in microseconds
  source_path NVARCHAR(100) NULL,
  manual NVARCHAR(100) NULL,
  photo NVARCHAR(100) NULL,
  small_count INT NOT NULL DEFAULT 0,
  tiny_count INT NOT NULL DEFAULT 0,
  is_active BIT NOT NULL DEFAULT 1,
  stocked_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  priority INT NOT NULL DEFAULT 5,
  note NVARCHAR(20) NOT NULL DEFAULT N'none',
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT item_pkey PRIMARY KEY (id),
  CONSTRAINT item_tags_check CHECK (ISJSON(tags) = 1),
  CONSTRAINT item_grid_check CHECK (ISJSON(grid) = 1),
  CONSTRAINT item_kinds_check CHECK (ISJSON(kinds) = 1),
  CONSTRAINT item_attributes_check CHECK (ISJSON(attributes) = 1)
);
CREATE UNIQUE INDEX item_legacy_ip_key ON item (legacy_ip) WHERE legacy_ip IS NOT NULL;

CREATE TABLE counter (
  small_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  label NVARCHAR(20) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT counter_pkey PRIMARY KEY (small_id)
);

CREATE TABLE content_type (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  email NVARCHAR(254) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
);

CREATE TABLE shipment (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  object_id INT NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  item_id UNIQUEIDENTIFIER NOT NULL,
  other_id UNIQUEIDENTIFIER NOT NULL,
  content_type_id UNIQUEIDENTIFIER NOT NULL,
  created_by_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT shipment_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES item (id),
  CONSTRAINT shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES content_type (id) ON DELETE CASCADE,
  CONSTRAINT shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE assignment (
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  item_id UNIQUEIDENTIFIER NOT NULL,
  account_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
