-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE status AS ENUM ('draft', 'live');

CREATE TYPE other_enum AS ENUM ('a');

CREATE TABLE other (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT other_pkey PRIMARY KEY (id)
);

CREATE TABLE weird (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  a_b TEXT NOT NULL DEFAULT 'x;y',
  quote TEXT NOT NULL DEFAULT 'say "hi"',
  tick TEXT NOT NULL DEFAULT 'a`b',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  self_id UUID,
  other_id UUID NOT NULL,
  CONSTRAINT weird_pkey PRIMARY KEY (id),
  CONSTRAINT weird_self_id_fkey FOREIGN KEY (self_id) REFERENCES weird (id) ON DELETE SET NULL,
  CONSTRAINT weird_other_id_fkey FOREIGN KEY (other_id) REFERENCES other (id) ON DELETE CASCADE
);
