-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE "Status" AS ENUM ('draft', 'live');

CREATE TYPE "Other" AS ENUM ('a');

CREATE TABLE "others" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT others_pkey PRIMARY KEY (id)
);

CREATE TABLE weird (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "a;b" TEXT NOT NULL DEFAULT 'x;y',
  quote TEXT NOT NULL DEFAULT 'say "hi"',
  tick TEXT NOT NULL DEFAULT 'a`b',
  self_id INTEGER,
  other_id INTEGER NOT NULL,
  CONSTRAINT weird_pkey PRIMARY KEY (id),
  CONSTRAINT weird_self_id_fkey FOREIGN KEY (self_id) REFERENCES weird (id) ON DELETE SET NULL,
  CONSTRAINT weird_other_id_fkey FOREIGN KEY (other_id) REFERENCES "others" (id) ON DELETE CASCADE
);
