# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    Interval,
    PrimaryKeyConstraint,
    String,
    Uuid,
    func,
    text,
    true,
)
from sqlalchemy.dialects.postgresql import (
    DATERANGE,
    HSTORE,
    INET,
    INT4RANGE,
    INT8RANGE,
    NUMRANGE,
    TSTZRANGE,
    Range,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class ItemKind(enum.Enum):
    TOOL = "tool"
    TOY = "toy"


class Item(Base):
    __tablename__ = "item"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    first_name: Mapped[str] = mapped_column(String(40))
    last_name: Mapped[str] = mapped_column(String(40))
    full_name: Mapped[str] = mapped_column(String(81))
    quantity: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    total_cents: Mapped[int] = mapped_column(Integer)
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(String(20)).with_variant(JSON(), "sqlite"),
        default=list,
    )
    grid: Mapped[Optional[list[list[int]]]] = mapped_column(
        ARRAY(Integer, dimensions=2).with_variant(JSON(), "sqlite"),
    )
    kinds: Mapped[list[ItemKind]] = mapped_column(
        ARRAY(Enum(ItemKind, name="item_kind", values_callable=lambda members: [member.value for member in members])).with_variant(
            JSON(),
            "sqlite",
        ),
        default=list,
    )
    attributes: Mapped[dict[str, str]] = mapped_column(
        HSTORE().with_variant(JSON(), "sqlite"),
        default=dict,
    )
    stock_range: Mapped[Optional[Range[int]]] = mapped_column(
        INT4RANGE().with_variant(JSON(), "sqlite"),
    )
    big_range: Mapped[Optional[Range[int]]] = mapped_column(
        INT8RANGE().with_variant(JSON(), "sqlite"),
    )
    price_range: Mapped[Optional[Range[decimal.Decimal]]] = mapped_column(
        NUMRANGE().with_variant(JSON(), "sqlite"),
    )
    available: Mapped[Optional[Range[datetime.date]]] = mapped_column(
        DATERANGE().with_variant(JSON(), "sqlite"),
    )
    valid_during: Mapped[Optional[Range[datetime.datetime]]] = mapped_column(
        TSTZRANGE().with_variant(JSON(), "sqlite"),
    )
    last_ip: Mapped[Optional[str]] = mapped_column(
        INET().with_variant(String(45), "sqlite"),
    )
    legacy_ip: Mapped[Optional[str]] = mapped_column(
        INET().with_variant(String(45), "sqlite"),
        unique=True,
    )
    shelf_life: Mapped[Optional[datetime.timedelta]] = mapped_column(Interval)
    source_path: Mapped[Optional[str]] = mapped_column(String(100))
    manual: Mapped[Optional[str]] = mapped_column(String(100))
    photo: Mapped[Optional[str]] = mapped_column(String(100))
    small_count: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    tiny_count: Mapped[int] = mapped_column(Integer, server_default=text("0"))
    is_active: Mapped[bool] = mapped_column(Boolean, server_default=true())
    stocked_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    priority: Mapped[int] = mapped_column(Integer, server_default=text("5"))
    note: Mapped[str] = mapped_column(String(20), server_default="none")
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    shipments: Mapped[list["Shipment"]] = relationship(
        back_populates="item",
        foreign_keys="[Shipment.item_id]",
        passive_deletes=True,
    )
    other_shipments: Mapped[list["Shipment"]] = relationship(
        back_populates="other",
        foreign_keys="[Shipment.other_id]",
        passive_deletes=True,
    )
    assignments: Mapped[list["Assignment"]] = relationship(
        back_populates="item",
        passive_deletes=True,
    )


class Counter(Base):
    __tablename__ = "counter"

    small_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
    )
    label: Mapped[str] = mapped_column(String(20))
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )


class ContentType(Base):
    __tablename__ = "content_type"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    shipments: Mapped[list["Shipment"]] = relationship(
        back_populates="content_type",
        passive_deletes=True,
    )


class Account(Base):
    __tablename__ = "account"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String(254), unique=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    shipments: Mapped[list["Shipment"]] = relationship(
        back_populates="created_by",
        passive_deletes=True,
    )
    assignments: Mapped[list["Assignment"]] = relationship(
        back_populates="account",
        passive_deletes=True,
    )


class Shipment(Base):
    __tablename__ = "shipment"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    object_id: Mapped[int] = mapped_column(Integer)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("item.id", ondelete="CASCADE"),
    )
    other_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("item.id", ondelete="CASCADE"),
    )
    content_type_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("content_type.id", ondelete="CASCADE"),
    )
    created_by_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("account.id", ondelete="CASCADE"),
    )

    item: Mapped["Item"] = relationship(
        back_populates="shipments",
        foreign_keys="[Shipment.item_id]",
    )
    other: Mapped["Item"] = relationship(
        back_populates="other_shipments",
        foreign_keys="[Shipment.other_id]",
    )
    content_type: Mapped["ContentType"] = relationship(back_populates="shipments")
    created_by: Mapped["Account"] = relationship(back_populates="shipments")


class Assignment(Base):
    __tablename__ = "assignment"
    __table_args__ = (
        PrimaryKeyConstraint("item_id", "account_id"),
    )

    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    item_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("item.id", ondelete="CASCADE"),
    )
    account_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("account.id", ondelete="CASCADE"),
    )

    item: Mapped["Item"] = relationship(back_populates="assignments")
    account: Mapped["Account"] = relationship(back_populates="assignments")
