# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
from typing import Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    DateTime,
    Enum,
    Integer,
    PrimaryKeyConstraint,
    String,
    func,
    text,
    true,
)
from sqlalchemy.dialects.postgresql import (
    DATERANGE,
    HSTORE,
    INET,
    INT4RANGE,
    INT8RANGE,
    NUMRANGE,
    TSTZRANGE,
    Range,
)
from sqlmodel import Field, Relationship, SQLModel


class ItemKind(enum.Enum):
    TOOL = "tool"
    TOY = "toy"


class Item(SQLModel, table=True):
    __tablename__ = "blog_item"

    id: Optional[int] = Field(default=None, primary_key=True)
    first_name: str = Field(max_length=40)
    last_name: str = Field(max_length=40)
    full_name: str = Field(max_length=81)
    quantity: int = Field(default=1, sa_column_kwargs={"server_default": text("1")})
    total_cents: int
    tags: list[str] = Field(
        default_factory=list,
        sa_type=ARRAY(String(20)).with_variant(JSON(), "sqlite"),
    )
    grid: Optional[list[list[int]]] = Field(
        default=None,
        sa_type=ARRAY(Integer, dimensions=2).with_variant(JSON(), "sqlite"),
    )
    kinds: list[ItemKind] = Field(
        default_factory=list,
        sa_type=ARRAY(Enum(ItemKind, name="ItemKind", values_callable=lambda members: [member.value for member in members])).with_variant(
            JSON(),
            "sqlite",
        ),
    )
    attributes: dict[str, str] = Field(
        default_factory=dict,
        sa_type=HSTORE().with_variant(JSON(), "sqlite"),
    )
    stock_range: Optional[Range[int]] = Field(
        default=None,
        sa_type=INT4RANGE().with_variant(JSON(), "sqlite"),
    )
    big_range: Optional[Range[int]] = Field(
        default=None,
        sa_type=INT8RANGE().with_variant(JSON(), "sqlite"),
    )
    price_range: Optional[Range[decimal.Decimal]] = Field(
        default=None,
        sa_type=NUMRANGE().with_variant(JSON(), "sqlite"),
    )
    available: Optional[Range[datetime.date]] = Field(
        default=None,
        sa_type=DATERANGE().with_variant(JSON(), "sqlite"),
    )
    valid_during: Optional[Range[datetime.datetime]] = Field(
        default=None,
        sa_type=TSTZRANGE().with_variant(JSON(), "sqlite"),
    )
    last_ip: Optional[str] = Field(
        default=None,
        sa_type=INET().with_variant(String(45), "sqlite"),
    )
    legacy_ip: Optional[str] = Field(
        default=None,
        unique=True,
        sa_type=INET().with_variant(String(45), "sqlite"),
    )
    shelf_life: Optional[datetime.timedelta] = Field(default=None)
    source_path: Optional[str] = Field(default=None, max_length=100)
    manual: Optional[str] = Field(default=None, max_length=100)
    photo: Optional[str] = Field(default=None, max_length=100)
    small_count: int = Field(default=0, sa_column_kwargs={"server_default": text("0")})
    tiny_count: int = Field(default=0, sa_column_kwargs={"server_default": text("0")})
    is_active: bool = Field(default=True, sa_column_kwargs={"server_default": true()})
    stocked_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    priority: int = Field(default=5, sa_column_kwargs={"server_default": text("5")})
    note: str = Field(
        default="none",
        max_length=20,
        sa_column_kwargs={"server_default": "none"},
    )

    shipments: list["Shipment"] = Relationship(
        back_populates="item",
        sa_relationship_kwargs={
            "foreign_keys": "[Shipment.item_id]",
            "passive_deletes": True,
        },
    )
    other_shipments: list["Shipment"] = Relationship(
        back_populates="other",
        sa_relationship_kwargs={
            "foreign_keys": "[Shipment.other_id]",
            "passive_deletes": True,
        },
    )
    assignments: list["Assignment"] = Relationship(
        back_populates="item",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Counter(SQLModel, table=True):
    __tablename__ = "blog_counter"

    small_id: Optional[int] = Field(default=None, primary_key=True)
    label: str = Field(max_length=20)


class ContentType(SQLModel, table=True):
    __tablename__ = "blog_contenttype"

    id: Optional[int] = Field(default=None, primary_key=True)

    shipments: list["Shipment"] = Relationship(
        back_populates="content_type",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Account(SQLModel, table=True):
    __tablename__ = "blog_account"

    id: Optional[int] = Field(default=None, primary_key=True)
    email: str = Field(unique=True, max_length=254)

    shipments: list["Shipment"] = Relationship(
        back_populates="created_by",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    assignments: list["Assignment"] = Relationship(
        back_populates="account",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Shipment(SQLModel, table=True):
    __tablename__ = "blog_shipment"

    id: Optional[int] = Field(default=None, primary_key=True)
    object_id: int
    item_id: int = Field(foreign_key="blog_item.id", ondelete="CASCADE")
    other_id: int = Field(foreign_key="blog_item.id", ondelete="CASCADE")
    content_type_id: int = Field(foreign_key="blog_contenttype.id", ondelete="CASCADE")
    created_by_id: int = Field(foreign_key="blog_account.id", ondelete="CASCADE")

    item: "Item" = Relationship(
        back_populates="shipments",
        sa_relationship_kwargs={"foreign_keys": "[Shipment.item_id]"},
    )
    other: "Item" = Relationship(
        back_populates="other_shipments",
        sa_relationship_kwargs={"foreign_keys": "[Shipment.other_id]"},
    )
    content_type: "ContentType" = Relationship(back_populates="shipments")
    created_by: "Account" = Relationship(back_populates="shipments")


class Assignment(SQLModel, table=True):
    __tablename__ = "blog_assignment"
    __table_args__ = (
        PrimaryKeyConstraint("item_id", "account_id"),
    )

    item_id: int = Field(foreign_key="blog_item.id", ondelete="CASCADE")
    account_id: int = Field(foreign_key="blog_account.id", ondelete="CASCADE")

    item: "Item" = Relationship(back_populates="assignments")
    account: "Account" = Relationship(back_populates="assignments")
