import { prismaOnlyWarnings } from '../prismaOnlyConstructs.js';
import type {
  IrDefault,
  IrEnum,
  IrField,
  IrGenerated,
  IrIndex,
  IrModel,
  IrOnDelete,
  IrRangeSubtype,
  IrRelation,
  IrSchema,
} from '../ir.js';
import { limitIdentifier, splitWords, toSnakeCase } from '../naming.js';
import type { EmitOutput } from './prisma.js';

const ON_DELETE_NAMES: Readonly<Record<IrOnDelete, string>> = {
  cascade: 'models.CASCADE',
  setNull: 'models.SET_NULL',
  restrict: 'models.PROTECT',
  noAction: 'models.DO_NOTHING',
  setDefault: 'models.SET_DEFAULT',
};

const DJANGO_INDEX_NAME_LIMIT: number = 30;
const IDENTIFIER_PATTERN: RegExp = /^[A-Za-z_][A-Za-z0-9_]*$/;

interface EmitContext {
  schema: IrSchema;
  warnings: string[];
  /** django.contrib.postgres field classes used, imported by name. */
  postgresFields: Set<string>;
  /** GeneratedField expressions, scanned for names that need importing. */
  expressions: string[];
}

const RANGE_FIELD_CLASSES: Readonly<Record<IrRangeSubtype, string>> = {
  int: 'IntegerRangeField',
  bigInt: 'BigIntegerRangeField',
  decimal: 'DecimalRangeField',
  date: 'DateRangeField',
  dateTime: 'DateTimeRangeField',
};

/** Names a GeneratedField expression may use without a module prefix, and where they come from. */
const EXPRESSION_MODEL_NAMES: readonly string[] = [
  'F',
  'Q',
  'Value',
  'Case',
  'When',
  'ExpressionWrapper',
  'Func',
  'Count',
  'Sum',
  'Avg',
  'Min',
  'Max',
];
const EXPRESSION_FUNCTION_NAMES: readonly string[] = [
  'Abs',
  'Cast',
  'Ceil',
  'Coalesce',
  'Concat',
  'Floor',
  'Greatest',
  'Least',
  'Left',
  'Length',
  'Lower',
  'LPad',
  'LTrim',
  'Mod',
  'Now',
  'Power',
  'Replace',
  'Right',
  'Round',
  'RPad',
  'RTrim',
  'Substr',
  'Trim',
  'Upper',
];

/** Writes the IR as a Django models.py file. */
export function emitDjango(schema: IrSchema): EmitOutput {
  const prepared: IrSchema = toDjangoNaming(schema);
  const context: EmitContext = {
    schema: prepared,
    warnings: prismaOnlyWarnings(schema),
    postgresFields: new Set(),
    expressions: [],
  };
  const blocks: string[] = [];

  for (const enumDefinition of prepared.enums) {
    blocks.push(emitEnum(enumDefinition));
  }
  for (const model of prepared.models) {
    blocks.push(emitModel(context, model));
  }

  const body: string = blocks.join('\n\n\n');
  const imports: string[] = [];
  if (body.includes('uuid.uuid4')) {
    imports.push('import uuid');
    imports.push('');
  }
  const postgresNames: string[] = [...context.postgresFields].sort();
  if (postgresNames.length > 0) {
    imports.push(
      `from django.contrib.postgres.fields import ${postgresNames.join(', ')}`
    );
  }
  if (body.includes('RandomUUID()')) {
    imports.push('from django.contrib.postgres.functions import RandomUUID');
  }
  imports.push('from django.db import models');
  const usedModelNames: string[] = usedExpressionNames(
    context.expressions,
    EXPRESSION_MODEL_NAMES
  );
  if (usedModelNames.length > 0) {
    imports.push(`from django.db.models import ${usedModelNames.join(', ')}`);
  }
  const functionNames: string[] = usedExpressionNames(
    context.expressions,
    EXPRESSION_FUNCTION_NAMES
  );
  if (/(^|[^.\w])Now\(\)/.test(body) && !functionNames.includes('Now')) {
    functionNames.push('Now');
    functionNames.sort();
  }
  if (functionNames.length > 0) {
    imports.push(
      `from django.db.models.functions import ${functionNames.join(', ')}`
    );
  }
  if (body.includes('timezone.now')) {
    imports.push('from django.utils import timezone');
  }

  const header: string =
    '# Generated by ormbridge. Review the output before running migrations.';
  const text: string = `${header}\n${imports.join('\n')}\n\n\n${body}\n`;
  return { text, warnings: context.warnings };
}

/** Returns the names from `candidates` that appear as unprefixed calls in any expression. */
function usedExpressionNames(
  expressions: string[],
  candidates: readonly string[]
): string[] {
  return candidates
    .filter((name: string) =>
      expressions.some((expression: string) =>
        new RegExp(`(^|[^.\\w])${name}\\(`).test(expression)
      )
    )
    .sort();
}

function pyString(value: string): string {
  return JSON.stringify(value);
}

/**
 * Django fields are conventionally snake_case, while Prisma fields are usually camelCase.
 * Renames every field and relation to snake_case; the original column name is kept, so a
 * db_column is emitted whenever it differs from the new field name.
 */
function toDjangoNaming(schema: IrSchema): IrSchema {
  const renames: Map<string, Map<string, string>> = new Map();
  for (const model of schema.models) {
    const modelRenames: Map<string, string> = new Map();
    for (const field of model.fields) {
      modelRenames.set(field.name, toSnakeCase(field.name) || field.name);
    }
    for (const relation of model.relations) {
      modelRenames.set(
        relation.name,
        toSnakeCase(relation.name) || relation.name
      );
    }
    renames.set(model.name, modelRenames);
  }
  const rename = (modelName: string, name: string): string =>
    renames.get(modelName)?.get(name) ?? name;

  const models: IrModel[] = schema.models.map((model: IrModel): IrModel => ({
    ...model,
    fields: model.fields.map((field: IrField): IrField => ({
      ...field,
      name: rename(model.name, field.name),
    })),
    relations: model.relations.map((relation: IrRelation): IrRelation => ({
      ...relation,
      name: rename(model.name, relation.name),
      ...(relation.toField === undefined
        ? {}
        : { toField: rename(relation.targetModel, relation.toField) }),
      ...(relation.relatedName === undefined
        ? {}
        : { relatedName: toSnakeCase(relation.relatedName) }),
    })),
    indexes: model.indexes.map((index: IrIndex): IrIndex => ({
      ...index,
      fields: index.fields.map((fieldName: string) =>
        rename(model.name, fieldName)
      ),
    })),
    ...(model.compositePrimaryKey === undefined
      ? {}
      : {
          compositePrimaryKey: model.compositePrimaryKey.map(
            (fieldName: string) => rename(model.name, fieldName)
          ),
        }),
  }));
  return { ...schema, models };
}

function labelFrom(memberName: string): string {
  return splitWords(memberName)
    .map(
      (word: string) =>
        word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    )
    .join(' ');
}

function emitEnum(enumDefinition: IrEnum): string {
  const lines: string[] = [`class ${enumDefinition.name}(models.TextChoices):`];
  if (enumDefinition.values.length === 0) {
    lines.push('    pass');
  }
  for (const value of enumDefinition.values) {
    const label: string = value.label ?? labelFrom(value.name);
    lines.push(
      `    ${value.name} = ${pyString(value.dbValue)}, ${pyString(label)}`
    );
  }
  return lines.join('\n');
}

/** Notes the fields that need a newer Django release or a specific database. */
function warnAboutVersionedFields(context: EmitContext, model: IrModel): void {
  const describe = (fields: IrField[]): string =>
    fields.map((field: IrField) => `${model.name}.${field.name}`).join(', ');
  const postgresFields: IrField[] = model.fields.filter(isPostgresOnly);
  if (postgresFields.length > 0) {
    context.warnings.push(
      `${describe(postgresFields)}: array, HStore and range fields come from django.contrib.postgres and only work on PostgreSQL.`
    );
  }
  const generatedFields: IrField[] = model.fields.filter(
    (field: IrField) => field.generated !== undefined
  );
  if (generatedFields.length > 0) {
    context.warnings.push(
      `${describe(generatedFields)}: models.GeneratedField requires Django 5.0 or newer; review the expression before running migrations.`
    );
  }
  const dbDefaultFields: IrField[] = model.fields.filter(
    (field: IrField) =>
      field.isDbDefault === true && field.default !== undefined
  );
  if (dbDefaultFields.length > 0) {
    context.warnings.push(
      `${describe(dbDefaultFields)}: db_default requires Django 5.0 or newer.`
    );
  }
}

function emitModel(context: EmitContext, model: IrModel): string {
  warnAboutVersionedFields(context, model);
  const lines: string[] = [`class ${model.name}(models.Model):`];
  const hasCompositeKey: boolean =
    model.compositePrimaryKey !== undefined &&
    model.compositePrimaryKey.length > 0;

  for (const field of model.fields) {
    lines.push(`    ${field.name} = ${buildFieldCall(context, model, field)}`);
  }
  for (const relation of model.relations) {
    lines.push(
      `    ${relation.name} = ${buildRelationCall(context, model, relation)}`
    );
  }
  if (hasCompositeKey && model.compositePrimaryKey !== undefined) {
    const keyNames: string = model.compositePrimaryKey.map(pyString).join(', ');
    lines.push(`    pk = models.CompositePrimaryKey(${keyNames})`);
    context.warnings.push(
      `${model.name}: the composite primary key (@@id) was emitted as models.CompositePrimaryKey, which requires Django 5.2 or newer.`
    );
  }
  if (model.fields.length === 0 && model.relations.length === 0) {
    lines.push('    pass');
  }

  const uniqueIndexes: IrIndex[] = model.indexes.filter(
    (index: IrIndex) => index.isUnique
  );
  const plainIndexes: IrIndex[] = model.indexes.filter(
    (index: IrIndex) => !index.isUnique
  );

  lines.push(
    '',
    '    class Meta:',
    `        db_table = ${pyString(model.tableName)}`
  );
  if (uniqueIndexes.length > 0) {
    lines.push('        constraints = [');
    for (const index of uniqueIndexes) {
      const name: string =
        index.name ?? `${model.tableName}_${index.fields.join('_')}_uniq`;
      lines.push(
        `            models.UniqueConstraint(fields=[${index.fields.map(pyString).join(', ')}], name=${pyString(limitIdentifier(name, 63))}),`
      );
    }
    lines.push('        ]');
  }
  if (plainIndexes.length > 0) {
    lines.push('        indexes = [');
    for (const index of plainIndexes) {
      const requested: string =
        index.name ??
        `${toSnakeCase(model.name)}_${index.fields.join('_')}_idx`;
      const name: string = limitIdentifier(requested, DJANGO_INDEX_NAME_LIMIT);
      if (name !== requested) {
        context.warnings.push(
          `${model.name}: the index name "${requested}" exceeds Django's ${DJANGO_INDEX_NAME_LIMIT}-character limit and was shortened to "${name}".`
        );
      }
      lines.push(
        `            models.Index(fields=[${index.fields.map(pyString).join(', ')}], name=${pyString(name)}),`
      );
    }
    lines.push('        ]');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Fields
// ---------------------------------------------------------------------------

function djangoFieldClass(field: IrField): string {
  const isAutoKey: boolean =
    field.isPrimaryKey &&
    field.default !== undefined &&
    field.default.kind === 'autoIncrement';
  switch (field.type) {
    case 'string':
      return 'CharField';
    case 'text':
      return 'TextField';
    case 'int':
      return isAutoKey ? 'AutoField' : 'IntegerField';
    case 'bigInt':
      return isAutoKey ? 'BigAutoField' : 'BigIntegerField';
    case 'float':
      return 'FloatField';
    case 'decimal':
      return 'DecimalField';
    case 'boolean':
      return 'BooleanField';
    case 'dateTime':
      return 'DateTimeField';
    case 'date':
      return 'DateField';
    case 'time':
      return 'TimeField';
    case 'uuid':
      return 'UUIDField';
    case 'json':
      return 'JSONField';
    case 'bytes':
      return 'BinaryField';
    case 'duration':
      return 'DurationField';
    case 'ipAddress':
      return 'GenericIPAddressField';
    case 'hstore':
      return 'HStoreField';
    case 'range':
      return RANGE_FIELD_CLASSES[field.rangeOf ?? 'int'];
    default:
      return 'CharField';
  }
}

/** True for the field types that live in django.contrib.postgres. */
function isPostgresOnly(field: IrField): boolean {
  return (
    (field.arrayDepth ?? 0) > 0 ||
    field.type === 'hstore' ||
    field.type === 'range'
  );
}

/**
 * Writes the column type with its type-specific arguments (length, precision, choices,
 * array element), without constraints such as null or unique.
 */
function buildTypeCall(
  context: EmitContext,
  model: IrModel,
  field: IrField
): string {
  const label: string = `${model.name}.${field.name}`;
  const depth: number = field.arrayDepth ?? 0;
  if (depth > 0) {
    const element: IrField = {
      ...field,
      arrayDepth: depth - 1 > 0 ? depth - 1 : undefined,
      isPrimaryKey: false,
      isUnique: false,
      isNullable: false,
      isAutoUpdated: false,
      default: undefined,
      generated: undefined,
      isDbDefault: undefined,
    };
    context.postgresFields.add('ArrayField');
    return `ArrayField(${buildTypeCall(context, model, element)})`;
  }

  const className: string = djangoFieldClass(field);
  const args: string[] = [];
  if (field.enumName !== undefined) {
    const enumDefinition: IrEnum | undefined = context.schema.enums.find(
      (candidate: IrEnum) => candidate.name === field.enumName
    );
    const longestValue: number = Math.max(
      32,
      ...(enumDefinition?.values ?? []).map((value) => value.dbValue.length)
    );
    args.push(
      `max_length=${longestValue}`,
      `choices=${field.enumName}.choices`
    );
  } else if (className === 'CharField') {
    args.push(`max_length=${field.maxLength ?? 255}`);
  } else if (className === 'DecimalField') {
    args.push(
      `max_digits=${field.maxDigits ?? 65}`,
      `decimal_places=${field.decimalPlaces ?? 30}`
    );
  }

  if (field.type === 'hstore' || field.type === 'range') {
    context.postgresFields.add(className);
    if (field.type === 'range' && field.rangeOf === undefined) {
      context.warnings.push(
        `${label}: the range field has no element type; it was written as IntegerRangeField.`
      );
    }
    return `${className}(${args.join(', ')})`;
  }
  return `models.${className}(${args.join(', ')})`;
}

function buildFieldCall(
  context: EmitContext,
  model: IrModel,
  field: IrField
): string {
  if (field.generated !== undefined) {
    return buildGeneratedCall(context, model, field, field.generated);
  }

  const typeCall: string = buildTypeCall(context, model, field);
  const args: string[] = [];
  const openIndex: number = typeCall.indexOf('(');
  const innerArgs: string = typeCall.slice(openIndex + 1, -1);
  if (innerArgs.length > 0) {
    args.push(innerArgs);
  }

  if (field.isPrimaryKey) {
    args.push('primary_key=True');
  }
  if (field.isUnique && !field.isPrimaryKey) {
    args.push('unique=True');
  }
  if (field.isNullable) {
    args.push('null=True', 'blank=True');
  }
  if (field.columnName !== field.name) {
    args.push(`db_column=${pyString(field.columnName)}`);
  }
  if (field.isAutoUpdated) {
    args.push('auto_now=True');
  } else {
    const defaultArgument: string | undefined = defaultArgumentOf(
      context,
      model,
      field
    );
    if (defaultArgument !== undefined) {
      args.push(defaultArgument);
    }
  }
  if (
    field.isPrimaryKey &&
    field.default !== undefined &&
    field.default.kind === 'uuid'
  ) {
    args.push('editable=False');
  }
  return `${typeCall.slice(0, openIndex)}(${args.join(', ')})`;
}

function buildGeneratedCall(
  context: EmitContext,
  model: IrModel,
  field: IrField,
  generated: IrGenerated
): string {
  const output: IrField = {
    ...field,
    columnName: field.name,
    isPrimaryKey: false,
    isUnique: false,
    isAutoUpdated: false,
    default: undefined,
    generated: undefined,
    isDbDefault: undefined,
  };
  context.expressions.push(generated.expression);
  const args: string[] = [
    `expression=${generated.expression}`,
    `output_field=${buildFieldCall(context, model, output)}`,
    `db_persist=${generated.isStored ? 'True' : 'False'}`,
  ];
  if (field.columnName !== field.name) {
    args.push(`db_column=${pyString(field.columnName)}`);
  }
  if (field.isUnique) {
    args.push('unique=True');
  }
  return `models.GeneratedField(${args.join(', ')})`;
}

function defaultArgumentOf(
  context: EmitContext,
  model: IrModel,
  field: IrField
): string | undefined {
  const argument: string | undefined = plainDefaultArgumentOf(
    context,
    model,
    field
  );
  if (argument === undefined || field.isDbDefault !== true) {
    return argument;
  }
  if (argument === 'default=timezone.now') {
    return 'db_default=Now()';
  }
  if (argument === 'default=uuid.uuid4') {
    return 'db_default=RandomUUID()';
  }
  if (argument === 'default=list' || argument === 'default=dict') {
    // db_default takes SQL expressions, which have no empty list or dict shorthand.
    return argument;
  }
  return argument.replace(/^default=/, 'db_default=');
}

function plainDefaultArgumentOf(
  context: EmitContext,
  model: IrModel,
  field: IrField
): string | undefined {
  const defaultValue: IrDefault | undefined = field.default;
  if (defaultValue === undefined) {
    return undefined;
  }
  switch (defaultValue.kind) {
    case 'autoIncrement':
      return undefined;
    case 'now':
      return 'default=timezone.now';
    case 'uuid':
      return 'default=uuid.uuid4';
    case 'enumValue':
      return field.enumName === undefined
        ? undefined
        : `default=${field.enumName}.${defaultValue.value}`;
    case 'literal': {
      const literal: string | number | boolean = defaultValue.value;
      if (typeof literal === 'boolean') {
        return `default=${literal ? 'True' : 'False'}`;
      }
      if (typeof literal === 'number') {
        return `default=${String(literal)}`;
      }
      if (
        (field.type === 'json' || (field.arrayDepth ?? 0) > 0) &&
        literal === '[]'
      ) {
        return 'default=list';
      }
      if (
        (field.type === 'json' || field.type === 'hstore') &&
        literal === '{}'
      ) {
        return 'default=dict';
      }
      if (field.type === 'json') {
        context.warnings.push(
          `${model.name}.${field.name}: the JSON default ${pyString(literal)} was emitted as a string; adjust it if a dict or list was intended.`
        );
      }
      return `default=${pyString(literal)}`;
    }
    default:
      return undefined;
  }
}

// ---------------------------------------------------------------------------
// Relations
// ---------------------------------------------------------------------------

function buildRelationCall(
  context: EmitContext,
  model: IrModel,
  relation: IrRelation
): string {
  const targetLiteral: string = pyString(relation.targetModel);
  const args: string[] = [targetLiteral];

  if (relation.kind === 'manyToMany') {
    if (
      relation.relatedName !== undefined &&
      IDENTIFIER_PATTERN.test(relation.relatedName)
    ) {
      args.push(`related_name=${pyString(relation.relatedName)}`);
    }
    args.push('blank=True');
    return `models.ManyToManyField(${args.join(', ')})`;
  }

  let onDelete: IrOnDelete = relation.onDelete;
  if (onDelete === 'setNull' && !relation.isNullable) {
    context.warnings.push(
      `${model.name}.${relation.name}: onDelete SetNull requires a nullable relation in Django; it was converted to PROTECT.`
    );
    onDelete = 'restrict';
  }
  if (onDelete === 'setDefault') {
    context.warnings.push(
      `${model.name}.${relation.name}: Django's SET_DEFAULT needs a default= value on the field; add one manually.`
    );
  }
  args.push(`on_delete=${ON_DELETE_NAMES[onDelete]}`);

  if (relation.isNullable) {
    args.push('null=True', 'blank=True');
  }
  if (
    relation.relatedName !== undefined &&
    IDENTIFIER_PATTERN.test(relation.relatedName)
  ) {
    args.push(`related_name=${pyString(relation.relatedName)}`);
  }
  if (relation.columnName !== `${relation.name}_id`) {
    args.push(`db_column=${pyString(relation.columnName)}`);
  }
  if (relation.toField !== undefined) {
    args.push(`to_field=${pyString(relation.toField)}`);
  }
  if (relation.isPrimaryKey === true) {
    args.push('primary_key=True');
  }
  const className: string =
    relation.kind === 'oneToOne' ? 'OneToOneField' : 'ForeignKey';
  return `models.${className}(${args.join(', ')})`;
}
