import { prismaOnlyWarnings } from '../prismaOnlyConstructs.js';
import type {
  IrEnum,
  IrEnumValue,
  IrField,
  IrModel,
  IrRelation,
  IrSchema,
} from '../ir.js';
import { findModel } from '../ir.js';
import { toCamelCase, toSnakeCase } from '../naming.js';
import type { EmitOutput } from './prisma.js';

/**
 * Zod emitter (Zod 4).
 *
 * The output is one `schemas.ts`-style file. Property names, enum names and the
 * handling of relations follow the TypeScript interfaces emitter, so both can
 * be generated from the same IR and used together. For every model it writes:
 *
 * - `<Model>Schema` / `<Model>`: the row as stored. Relation fields are not part of it;
 *   foreign-key scalars are.
 * - `<Model>CreateSchema` / `<Model>Create`: the row without database-generated columns;
 *   columns with a default, and nullable columns, become optional.
 * - `<Model>UpdateSchema` / `<Model>Update`: every property of the create schema, optional.
 * - `<Model>WithRelationsSchema` / `<Model>WithRelations` (only for models that take part in
 *   a relation): the row plus optional, lazily resolved related rows.
 */

/**
 * How date and date-time columns are validated. `coerce` (the default) writes
 * `z.coerce.date()`, which accepts a `Date` or anything `new Date(value)` understands and
 * produces a `Date`; it also accepts `null` and numbers, so a null in a required date column
 * is not rejected. `string` keeps ISO 8601 text (`z.iso.datetime` / `z.iso.date`) and rejects
 * everything else, which matches the TypeScript interfaces emitter's default.
 */
export type ZodDateMode = 'coerce' | 'string';

/**
 * How 64-bit integers are validated. `string` (the default) accepts a string of digits, like
 * the TypeScript interfaces emitter, because JSON cannot carry a bigint. `bigint` writes
 * `z.coerce.bigint()`, which produces a native `bigint`.
 */
export type ZodBigIntMode = 'string' | 'bigint';

export interface ZodEmitOptions {
  /** Use camelCase property names (the `normalize` naming mode). */
  camelFields: boolean;
  /** Validation of DateTime and Date columns. Defaults to "coerce". */
  dates?: ZodDateMode;
  /** Validation of BigInt columns. Defaults to "string". */
  bigints?: ZodBigIntMode;
}

interface ModelNames {
  fields: Map<string, string>;
  relations: Map<string, string>;
  /** Foreign-key scalar property per relation (absent when a field already provides it). */
  scalars: Map<string, string>;
  used: Set<string>;
}

/** A scalar property of a row. */
interface Scalar {
  name: string;
  /** Schema expression without `.nullable()`. */
  schema: string;
  nullable: boolean;
  /** True when the create schema leaves the property out (generated by the database). */
  omitOnCreate: boolean;
  /** True when the create schema allows the property to be missing. */
  optionalOnCreate: boolean;
}

/** A related row, only part of the `WithRelations` schema. */
interface RelationMember {
  name: string;
  /** The related model's TypeScript type name, without `WithRelations`. */
  target: string;
  list: boolean;
  nullable: boolean;
}

interface EmitContext {
  schema: IrSchema;
  options: ZodEmitOptions;
  dates: ZodDateMode;
  bigints: ZodBigIntMode;
  warnings: string[];
  names: Map<string, ModelNames>;
  /** "Model.relation" -> property name of the reverse side on the target model. */
  inverseNames: Map<string, string>;
  /** Type names that were actually written (after sanitizing), per enum and model. */
  typeNames: Map<string, string>;
}

const IDENTIFIER_PATTERN: RegExp = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const MAX_KEY_DEPTH: number = 5;

/** Prisma default functions that the database fills in from a counter. */
const COUNTER_FUNCTIONS: ReadonlySet<string> = new Set([
  'auto()',
  'sequence()',
]);

/** Suffixes of the names written for a model, besides the model's own type name. */
const MODEL_SUFFIXES: readonly string[] = [
  'Schema',
  'Create',
  'CreateSchema',
  'Update',
  'UpdateSchema',
  'WithRelations',
  'WithRelationsSchema',
];

export function emitZod(schema: IrSchema, options: ZodEmitOptions): EmitOutput {
  const context: EmitContext = {
    schema,
    options,
    dates: options.dates ?? 'coerce',
    bigints: options.bigints ?? 'string',
    warnings: prismaOnlyWarnings(schema, true),
    names: new Map<string, ModelNames>(),
    inverseNames: new Map<string, string>(),
    typeNames: new Map<string, string>(),
  };

  allocateTypeNames(context);
  allocateMemberNames(context);

  const reverseMembers: Map<string, RelationMember[]> = new Map<
    string,
    RelationMember[]
  >();
  const forward: Map<
    string,
    { scalars: Scalar[]; relations: RelationMember[] }
  > = new Map<string, { scalars: Scalar[]; relations: RelationMember[] }>();
  for (const model of schema.models) {
    forward.set(
      model.name,
      buildForwardMembers(context, model, reverseMembers)
    );
  }

  const blocks: string[] = [];
  for (const enumDefinition of schema.enums) {
    blocks.push(emitEnum(context, enumDefinition));
  }
  for (const model of schema.models) {
    const members: { scalars: Scalar[]; relations: RelationMember[] } =
      forward.get(model.name) ?? { scalars: [], relations: [] };
    blocks.push(
      emitModel(context, model, members.scalars, [
        ...members.relations,
        ...(reverseMembers.get(model.name) ?? []),
      ])
    );
  }

  if (blocks.length === 0) {
    return { text: '', warnings: context.warnings };
  }
  return {
    text: `import { z } from 'zod';\n\n${blocks.join('\n\n')}\n`,
    warnings: context.warnings,
  };
}

// ---------------------------------------------------------------------------
// Names
// ---------------------------------------------------------------------------

function quote(value: string): string {
  const escaped: string = value.replace(/\\/g, '\\\\').replace(/\n/g, '\\n');
  return `'${escaped.replace(/'/g, "\\'")}'`;
}

/** Writes a property or enum member name, quoting it when it is not a valid identifier. */
function memberKey(name: string): string {
  return IDENTIFIER_PATTERN.test(name) ? name : quote(name);
}

function typeIdentifier(
  context: EmitContext,
  description: string,
  raw: string
): string {
  if (IDENTIFIER_PATTERN.test(raw)) {
    return raw;
  }
  const replaced: string = raw.replace(/[^A-Za-z0-9_$]/g, '_');
  const safe: string = /^[0-9]/.test(replaced) ? `_${replaced}` : replaced;
  const result: string = safe === '' ? '_' : safe;
  context.warnings.push(
    `${description}: "${raw}" is not a valid TypeScript identifier; it was written as "${result}".`
  );
  return result;
}

function uniqueName(baseName: string, used: Set<string>): string {
  let candidate: string = baseName;
  let suffix: number = 2;
  while (used.has(candidate)) {
    candidate = `${baseName}${suffix}`;
    suffix += 1;
  }
  used.add(candidate);
  return candidate;
}

function propertyName(context: EmitContext, rawName: string): string {
  return context.options.camelFields ? toCamelCase(rawName) : rawName;
}

/**
 * Picks the base name of a type so that none of the names derived from it (`<Base>Schema`, ...)
 * is taken. The derived names are reserved together with the base.
 */
function reserveBase(
  base: string,
  suffixes: readonly string[],
  used: Set<string>
): string {
  let candidate: string = base;
  let counter: number = 2;
  const clashes = (name: string): boolean =>
    used.has(name) ||
    suffixes.some((suffix: string) => used.has(name + suffix));
  while (clashes(candidate)) {
    candidate = `${base}${counter}`;
    counter += 1;
  }
  used.add(candidate);
  for (const suffix of suffixes) {
    used.add(candidate + suffix);
  }
  return candidate;
}

function allocateTypeNames(context: EmitContext): void {
  // "z" is the imported namespace.
  const used: Set<string> = new Set<string>(['z']);
  for (const enumDefinition of context.schema.enums) {
    const safe: string = typeIdentifier(
      context,
      `enum ${enumDefinition.name}`,
      enumDefinition.name
    );
    const unique: string = reserveBase(safe, ['Schema'], used);
    if (unique !== safe) {
      context.warnings.push(
        `enum ${enumDefinition.name}: the name is already used by another type; it was written as "${unique}".`
      );
    }
    context.typeNames.set(`enum:${enumDefinition.name}`, unique);
  }
  for (const model of context.schema.models) {
    const safe: string = typeIdentifier(context, model.name, model.name);
    const unique: string = reserveBase(safe, MODEL_SUFFIXES, used);
    if (unique !== safe) {
      context.warnings.push(
        `${model.name}: the name is already used by an enum, another model or a name derived from one; the schema was written as "${unique}Schema".`
      );
    }
    context.typeNames.set(`model:${model.name}`, unique);
  }
}

function modelTypeName(context: EmitContext, model: IrModel): string {
  return context.typeNames.get(`model:${model.name}`) ?? model.name;
}

function enumTypeName(context: EmitContext, enumDefinition: IrEnum): string {
  return (
    context.typeNames.get(`enum:${enumDefinition.name}`) ?? enumDefinition.name
  );
}

function namesOf(context: EmitContext, model: IrModel): ModelNames {
  return (
    context.names.get(model.name) ?? {
      fields: new Map<string, string>(),
      relations: new Map<string, string>(),
      scalars: new Map<string, string>(),
      used: new Set<string>(),
    }
  );
}

function allocateMemberNames(context: EmitContext): void {
  for (const model of context.schema.models) {
    const names: ModelNames = {
      fields: new Map<string, string>(),
      relations: new Map<string, string>(),
      scalars: new Map<string, string>(),
      used: new Set<string>(),
    };
    for (const field of model.fields) {
      names.fields.set(
        field.name,
        uniqueName(propertyName(context, field.name), names.used)
      );
    }
    for (const relation of model.relations) {
      if (relation.kind !== 'manyToMany') {
        // The foreign-key scalar is written first; skip it when a field already provides it.
        const scalarName: string = propertyName(context, relation.columnName);
        if (!names.used.has(scalarName)) {
          names.used.add(scalarName);
          names.scalars.set(relation.name, scalarName);
        }
      }
      names.relations.set(
        relation.name,
        uniqueName(propertyName(context, relation.name), names.used)
      );
    }
    context.names.set(model.name, names);
  }

  for (const model of context.schema.models) {
    for (const relation of model.relations) {
      const targetNames: ModelNames | undefined = context.names.get(
        relation.targetModel
      );
      if (targetNames === undefined) {
        continue;
      }
      const defaultName: string =
        relation.kind === 'oneToOne'
          ? toSnakeCase(model.name)
          : `${toSnakeCase(model.name)}_set`;
      context.inverseNames.set(
        `${model.name}.${relation.name}`,
        uniqueName(
          propertyName(context, relation.relatedName ?? defaultName),
          targetNames.used
        )
      );
    }
  }
}

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

/**
 * Writes the enum as a const object (so `Role.ADMIN` works like the member of the interface
 * emitter's `enum Role`), the `z.enum` schema built from it and the union type.
 */
function emitEnum(context: EmitContext, enumDefinition: IrEnum): string {
  const name: string = enumTypeName(context, enumDefinition);
  const lines: string[] = [`export const ${name} = {`];
  const usedMembers: Set<string> = new Set<string>();
  for (const value of enumDefinition.values) {
    const memberName: string = enumMemberName(
      context,
      enumDefinition,
      value,
      usedMembers
    );
    if (value.label !== undefined && value.label !== '') {
      lines.push(`  /** ${escapeComment(value.label)} */`);
    }
    lines.push(`  ${memberKey(memberName)}: ${quote(value.dbValue)},`);
  }
  lines.push('} as const;');
  lines.push(`export const ${name}Schema = z.enum(${name});`);
  lines.push(`export type ${name} = z.infer<typeof ${name}Schema>;`);
  return lines.join('\n');
}

function enumMemberName(
  context: EmitContext,
  enumDefinition: IrEnum,
  value: IrEnumValue,
  used: Set<string>
): string {
  const unique: string = uniqueName(value.name, used);
  if (unique !== value.name) {
    context.warnings.push(
      `enum ${enumDefinition.name}: the member "${value.name}" is declared more than once; the repeat was written as "${unique}".`
    );
  }
  return unique;
}

function escapeComment(text: string): string {
  return text.replace(/\*\//g, '*\\/').replace(/\s*\n\s*/g, ' ');
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

function dateSchema(context: EmitContext, type: 'date' | 'dateTime'): string {
  if (context.dates === 'coerce') {
    return 'z.coerce.date()';
  }
  return type === 'date' ? 'z.iso.date()' : 'z.iso.datetime({ offset: true })';
}

function bigIntSchema(context: EmitContext): string {
  return context.bigints === 'bigint'
    ? 'z.coerce.bigint()'
    : 'z.string().regex(/^-?\\d+$/)';
}

/** A string of digits that fits `DECIMAL(maxDigits, decimalPlaces)`; any decimal number when unsized. */
function decimalSchema(field: IrField | undefined): string {
  const digits: number | undefined = field?.maxDigits;
  if (digits === undefined) {
    return 'z.string().regex(/^-?\\d+(\\.\\d+)?$/)';
  }
  const places: number = field?.decimalPlaces ?? 0;
  const integerDigits: number = Math.max(digits - places, 1);
  const fraction: string = places > 0 ? `(\\.\\d{1,${places}})?` : '';
  return `z.string().regex(/^-?\\d{1,${integerDigits}}${fraction}$/)`;
}

function rangeBoundSchema(context: EmitContext, field: IrField): string {
  switch (field.rangeOf) {
    case 'int':
      return 'z.number().int()';
    case 'bigInt':
      return bigIntSchema(context);
    case 'decimal':
      return decimalSchema(undefined);
    case 'dateTime':
      return dateSchema(context, 'dateTime');
    case 'date':
      return dateSchema(context, 'date');
    default:
      return 'z.string()';
  }
}

/**
 * Returns the Zod expression of a scalar field, without `.nullable()`. Problems are only
 * reported when `report` is true, so a type that is looked up twice produces one warning.
 */
function fieldSchema(
  context: EmitContext,
  label: string,
  field: IrField,
  report: boolean
): string {
  const element: string = elementSchema(context, label, field, report);
  let result: string = element;
  for (let level: number = 0; level < (field.arrayDepth ?? 0); level += 1) {
    result = `z.array(${result})`;
  }
  return result;
}

function elementSchema(
  context: EmitContext,
  label: string,
  field: IrField,
  report: boolean
): string {
  if (field.enumName !== undefined) {
    const enumDefinition: IrEnum | undefined = context.schema.enums.find(
      (candidate: IrEnum) => candidate.name === field.enumName
    );
    if (enumDefinition !== undefined) {
      return `${enumTypeName(context, enumDefinition)}Schema`;
    }
    if (report) {
      context.warnings.push(
        `${label}: enum "${field.enumName}" does not exist in the schema; the property is validated as a string.`
      );
    }
    return 'z.string()';
  }

  switch (field.type) {
    case 'string':
    case 'text':
      return field.maxLength === undefined
        ? 'z.string()'
        : `z.string().max(${field.maxLength})`;
    case 'uuid':
      return 'z.uuid()';
    case 'time':
    case 'duration':
      return 'z.string()';
    case 'bytes':
      // Binary data travels as base64 text.
      return 'z.base64()';
    case 'bigInt':
      return bigIntSchema(context);
    case 'decimal':
      return decimalSchema(field);
    case 'int':
      return 'z.number().int()';
    case 'float':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'dateTime':
      return dateSchema(context, 'dateTime');
    case 'date':
      return dateSchema(context, 'date');
    case 'json':
      return 'z.unknown()';
    case 'ipAddress':
      return 'z.union([z.ipv4(), z.ipv6()])';
    case 'hstore':
      return 'z.record(z.string(), z.string().nullable())';
    case 'range': {
      const bound: string = rangeBoundSchema(context, field);
      return `z.object({ lower: ${bound}.nullable(), upper: ${bound}.nullable(), bounds: z.string().optional() })`;
    }
    default:
      if (report) {
        context.warnings.push(
          `${label}: unknown field type "${String(field.type)}"; the property is validated as unknown.`
        );
      }
      return 'z.unknown()';
  }
}

/** Resolves the schema of the column a relation points at (an explicit to_field, else the primary key). */
function referencedSchema(
  context: EmitContext,
  target: IrModel,
  toField: string | undefined,
  depth: number = 0
): string | undefined {
  if (depth > MAX_KEY_DEPTH) {
    return undefined;
  }
  const explicit: IrField | undefined =
    toField === undefined
      ? undefined
      : target.fields.find((field: IrField) => field.name === toField);
  const column: IrField | undefined =
    explicit ?? target.fields.find((field: IrField) => field.isPrimaryKey);
  if (column !== undefined) {
    return fieldSchema(context, `${target.name}.${column.name}`, column, false);
  }
  const primaryRelation: IrRelation | undefined = target.relations.find(
    (relation: IrRelation) => relation.isPrimaryKey === true
  );
  if (primaryRelation === undefined) {
    return undefined;
  }
  const chained: IrModel | undefined = findModel(
    context.schema,
    primaryRelation.targetModel
  );
  return chained === undefined
    ? undefined
    : referencedSchema(context, chained, primaryRelation.toField, depth + 1);
}

// ---------------------------------------------------------------------------
// Members
// ---------------------------------------------------------------------------

/** True when the database fills the column in itself, so a create payload must not carry it. */
function isGeneratedByDatabase(field: IrField): boolean {
  if (field.generated !== undefined || field.isAutoUpdated) {
    return true;
  }
  const fallback: IrField['default'] = field.default;
  if (fallback === undefined) {
    return false;
  }
  return (
    fallback.kind === 'autoIncrement' ||
    (fallback.kind === 'dbExpression' &&
      fallback.isFunction === true &&
      COUNTER_FUNCTIONS.has(fallback.expression))
  );
}

function buildForwardMembers(
  context: EmitContext,
  model: IrModel,
  reverseMembers: Map<string, RelationMember[]>
): { scalars: Scalar[]; relations: RelationMember[] } {
  const scalars: Scalar[] = [];
  const relations: RelationMember[] = [];
  const names: ModelNames = namesOf(context, model);

  for (const field of model.fields) {
    const label: string = `${model.name}.${field.name}`;
    const omitOnCreate: boolean = isGeneratedByDatabase(field);
    scalars.push({
      name: names.fields.get(field.name) ?? field.name,
      schema: fieldSchema(context, label, field, true),
      nullable: field.isNullable,
      omitOnCreate,
      optionalOnCreate:
        !omitOnCreate &&
        (field.isNullable ||
          field.default !== undefined ||
          field.isDbDefault === true),
    });
  }

  for (const relation of model.relations) {
    const label: string = `${model.name}.${relation.name}`;
    const target: IrModel | undefined = findModel(
      context.schema,
      relation.targetModel
    );
    if (target === undefined) {
      context.warnings.push(
        `${label}: target model "${relation.targetModel}" does not exist in the schema; the relation was skipped.`
      );
      continue;
    }
    const targetName: string = modelTypeName(context, target);
    const relationProp: string =
      names.relations.get(relation.name) ?? relation.name;
    const inverseProp: string =
      context.inverseNames.get(label) ?? toSnakeCase(model.name);

    if (relation.kind === 'manyToMany') {
      relations.push({
        name: relationProp,
        target: targetName,
        list: true,
        nullable: false,
      });
      addReverse(reverseMembers, target.name, {
        name: inverseProp,
        target: modelTypeName(context, model),
        list: true,
        nullable: false,
      });
      continue;
    }

    const scalarProp: string | undefined = names.scalars.get(relation.name);
    if (scalarProp !== undefined) {
      let keySchema: string | undefined = referencedSchema(
        context,
        target,
        relation.toField
      );
      if (keySchema === undefined) {
        context.warnings.push(
          `${label}: target model "${target.name}" has no single-column primary key to reference; the foreign key "${scalarProp}" is validated as unknown.`
        );
        keySchema = 'z.unknown()';
      }
      scalars.push({
        name: scalarProp,
        schema: keySchema,
        nullable: relation.isNullable && keySchema !== 'z.unknown()',
        omitOnCreate: false,
        optionalOnCreate: relation.isNullable,
      });
    }
    relations.push({
      name: relationProp,
      target: targetName,
      list: false,
      nullable: relation.isNullable,
    });
    addReverse(reverseMembers, target.name, {
      name: inverseProp,
      target: modelTypeName(context, model),
      list: relation.kind !== 'oneToOne',
      nullable: relation.kind === 'oneToOne',
    });
  }
  return { scalars, relations };
}

function addReverse(
  reverseMembers: Map<string, RelationMember[]>,
  targetName: string,
  member: RelationMember
): void {
  const existing: RelationMember[] = reverseMembers.get(targetName) ?? [];
  existing.push(member);
  reverseMembers.set(targetName, existing);
}

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

function scalarLine(scalar: Scalar): string {
  return `  ${memberKey(scalar.name)}: ${scalar.schema}${scalar.nullable ? '.nullable()' : ''},`;
}

/** Writes `{ a: true, b: true }` for the given property names. */
function mask(names: string[]): string {
  return `{ ${names.map((name: string) => `${memberKey(name)}: true`).join(', ')} }`;
}

function emitModel(
  context: EmitContext,
  model: IrModel,
  scalars: Scalar[],
  relations: RelationMember[]
): string {
  const name: string = modelTypeName(context, model);
  const lines: string[] = [`export const ${name}Schema = z.object({`];
  for (const scalar of scalars) {
    lines.push(scalarLine(scalar));
  }
  lines.push('});', `export type ${name} = z.infer<typeof ${name}Schema>;`);

  if (model.isView !== true) {
    const omitted: string[] = scalars
      .filter((scalar: Scalar) => scalar.omitOnCreate)
      .map((scalar: Scalar) => scalar.name);
    const optional: string[] = scalars
      .filter((scalar: Scalar) => scalar.optionalOnCreate)
      .map((scalar: Scalar) => scalar.name);
    const create: string = `${name}Schema${omitted.length === 0 ? '' : `.omit(${mask(omitted)})`}${optional.length === 0 ? '' : `.partial(${mask(optional)})`}`;
    lines.push(
      '',
      `export const ${name}CreateSchema = ${create};`,
      `export type ${name}Create = z.infer<typeof ${name}CreateSchema>;`,
      '',
      `export const ${name}UpdateSchema = ${name}CreateSchema.partial();`,
      `export type ${name}Update = z.infer<typeof ${name}UpdateSchema>;`
    );
  }

  if (relations.length > 0) {
    lines.push('', ...relationLines(name, relations));
  }
  return lines.join('\n');
}

/**
 * The `WithRelations` type is written out by hand and annotates the schema, because the
 * schemas refer to each other and TypeScript cannot infer a type that depends on itself.
 */
function relationLines(name: string, relations: RelationMember[]): string[] {
  const typeLines: string[] = [];
  const schemaLines: string[] = [];
  for (const relation of relations) {
    const key: string = memberKey(relation.name);
    const related: string = `${relation.target}WithRelations`;
    const typeText: string = `${related}${relation.list ? '[]' : ''}${relation.nullable ? ' | null' : ''}`;
    typeLines.push(`  ${key}?: ${typeText};`);
    const lazy: string = relation.list
      ? `z.array(z.lazy(() => ${related}Schema))`
      : `z.lazy(() => ${related}Schema)`;
    schemaLines.push(
      `  ${key}: ${lazy}${relation.nullable ? '.nullable()' : ''}.optional(),`
    );
  }
  return [
    `export type ${name}WithRelations = ${name} & {`,
    ...typeLines,
    '};',
    `export const ${name}WithRelationsSchema: z.ZodType<${name}WithRelations> = ${name}Schema.extend({`,
    ...schemaLines,
    '});',
  ];
}
