# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    DateTime,
    Enum,
    Index,
    PrimaryKeyConstraint,
    Text,
    UniqueConstraint,
    false,
    func,
    text,
)
from sqlmodel import Field, Relationship, SQLModel


class PostStatus(enum.Enum):
    DRAFT = "draft"
    PUBLISHED = "published"


class User(SQLModel, table=True):
    __tablename__ = "user"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    posts: list["Post"] = Relationship(
        back_populates="author",
        sa_relationship_kwargs={
            "foreign_keys": "[Post.author_id]",
            "passive_deletes": True,
        },
    )
    edited_posts: list["Post"] = Relationship(
        back_populates="editor",
        sa_relationship_kwargs={
            "foreign_keys": "[Post.editor_id]",
            "passive_deletes": True,
        },
    )
    profile: Optional["Profile"] = Relationship(
        back_populates="user",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Category(SQLModel, table=True):
    __tablename__ = "category"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    name: str = Field(unique=True, max_length=100)
    slug: str = Field(max_length=50)
    parent_id: Optional[uuid.UUID] = Field(
        default=None,
        foreign_key="category.id",
        ondelete="SET NULL",
    )

    parent: Optional["Category"] = Relationship(
        back_populates="children",
        sa_relationship_kwargs={"remote_side": "Category.id"},
    )
    children: list["Category"] = Relationship(
        back_populates="parent",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    posts: list["Post"] = Relationship(back_populates="category")


class Post(SQLModel, table=True):
    __tablename__ = "post"
    __table_args__ = (
        UniqueConstraint("author_id", "title", name="uq_post_author_id_title"),
        Index("post_pub_status_idx", "published_at", "status"),
        Index("ix_post_title", "title"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    public_id: uuid.UUID = Field(default_factory=uuid.uuid4, unique=True)
    title: str = Field(max_length=200)
    body: str = Field(sa_type=Text)
    status: PostStatus = Field(
        default=PostStatus.DRAFT,
        sa_type=Enum(
            PostStatus,
            name="post_status",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "draft"},
    )
    rating: Optional[decimal.Decimal] = Field(
        default=None,
        max_digits=4,
        decimal_places=2,
    )
    view_count: int = Field(default=0, sa_column_kwargs={"server_default": text("0")})
    is_featured: bool = Field(
        default=False,
        sa_column_kwargs={"server_default": false()},
    )
    published_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    metadata_: Any = Field(
        default_factory=dict,
        sa_type=JSON,
        sa_column_kwargs={"name": "metadata", "server_default": text("'{}'")},
    )
    author_id: uuid.UUID = Field(foreign_key="user.id", ondelete="CASCADE")
    editor_id: Optional[uuid.UUID] = Field(
        default=None,
        foreign_key="user.id",
        ondelete="SET NULL",
    )
    category_id: uuid.UUID = Field(foreign_key="category.id", ondelete="RESTRICT")

    author: "User" = Relationship(
        back_populates="posts",
        sa_relationship_kwargs={"foreign_keys": "[Post.author_id]"},
    )
    editor: Optional["User"] = Relationship(
        back_populates="edited_posts",
        sa_relationship_kwargs={"foreign_keys": "[Post.editor_id]"},
    )
    category: "Category" = Relationship(back_populates="posts")
    tags: list["PostTag"] = Relationship(
        back_populates="post",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class Tag(SQLModel, table=True):
    __tablename__ = "tag"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    label: str = Field(max_length=50)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    posts: list["PostTag"] = Relationship(
        back_populates="tag",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class PostTag(SQLModel, table=True):
    __tablename__ = "post_tag"
    __table_args__ = (
        PrimaryKeyConstraint("post_id", "tag_id"),
    )

    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    post_id: uuid.UUID = Field(foreign_key="post.id", ondelete="CASCADE")
    tag_id: uuid.UUID = Field(foreign_key="tag.id", ondelete="CASCADE")

    post: "Post" = Relationship(back_populates="tags")
    tag: "Tag" = Relationship(back_populates="posts")


class Profile(SQLModel, table=True):
    __tablename__ = "profile"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    bio: Optional[str] = Field(default=None, sa_type=Text)
    avatar: Optional[str] = Field(default=None, max_length=100)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    user_id: uuid.UUID = Field(foreign_key="user.id", ondelete="CASCADE", unique=True)

    user: "User" = Relationship(back_populates="profile")
