# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Text,
    Time,
    UniqueConstraint,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Role(enum.Enum):
    ADMIN = "admin"
    USER = "user"


class Order(Base):
    __tablename__ = "order"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number", name="order_pkey"),
    )

    region: Mapped[str] = mapped_column(String)
    number: Mapped[int] = mapped_column(Integer)
    total: Mapped[decimal.Decimal] = mapped_column(Numeric)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    order_lines: Mapped[list["OrderLine"]] = relationship(
        back_populates="order",
        passive_deletes=True,
    )


class OrderLine(Base):
    __tablename__ = "order_line"
    __table_args__ = (
        ForeignKeyConstraint(
            ["order_region", "order_number"],
            ["order.region", "order.number"],
            name="fk_line_order",
            ondelete="CASCADE",
            onupdate="RESTRICT",
        ),
        Index(
            "ix_order_line_order_region_order_number",
            "order_region",
            "order_number",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    order_region: Mapped[str] = mapped_column(String)
    order_number: Mapped[int] = mapped_column(Integer)
    sku: Mapped[str] = mapped_column(String(32))
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    order: Mapped["Order"] = relationship(back_populates="order_lines")


class Tenant(Base):
    __tablename__ = "tenant"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )

    accounts: Mapped[list["Account"]] = relationship(back_populates="tenant")


class Account(Base):
    __tablename__ = "account"
    __table_args__ = (
        PrimaryKeyConstraint("id", name="account_pk"),
        UniqueConstraint("email", name="uq_account_email"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey(
            "tenant.id",
            ondelete="NO ACTION",
            onupdate="CASCADE",
            name="fk_account_tenant",
        ),
    )

    tenant: Mapped["Tenant"] = relationship(back_populates="accounts")
    profile: Mapped[Optional["Profile"]] = relationship(back_populates="account")


class Profile(Base):
    __tablename__ = "profile"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number"),
    )

    region: Mapped[str] = mapped_column(String)
    number: Mapped[int] = mapped_column(Integer)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    account_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("account.id", ondelete="RESTRICT"),
        unique=True,
    )

    account: Mapped["Account"] = relationship(back_populates="profile")


class Document(Base):
    __tablename__ = "document"
    __table_args__ = (
        UniqueConstraint("ulid", name="uq_document_ulid"),
        Index("ix_document_title", "title", "created"),
        Index("ix_document_meta", "meta"),
        UniqueConstraint("title", "day", name="uq_document_title_day"),
    )

    id: Mapped[str] = mapped_column(String, primary_key=True)
    ulid: Mapped[str] = mapped_column(String)
    short: Mapped[str] = mapped_column(String)
    uid: Mapped[uuid.UUID] = mapped_column(Uuid, default=uuid.uuid4)
    token: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        server_default=text("gen_random_uuid()"),
    )
    title: Mapped[str] = mapped_column(String)
    body: Mapped[str] = mapped_column(Text)
    role: Mapped[Role] = mapped_column(
        Enum(
            Role,
            name="role_t",
            values_callable=lambda members: [member.value for member in members],
        ),
        server_default="user",
    )
    small: Mapped[int] = mapped_column(Integer)
    ratio: Mapped[float] = mapped_column(Float)
    price: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2))
    cost: Mapped[decimal.Decimal] = mapped_column(Numeric)
    views: Mapped[int] = mapped_column(BigInteger)
    blob: Mapped[bytes] = mapped_column(LargeBinary)
    meta: Mapped[Any] = mapped_column(JSON)
    created: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    day: Mapped[datetime.date] = mapped_column(Date)
    at: Mapped[datetime.time] = mapped_column(Time)
    ip: Mapped[str] = mapped_column(INET().with_variant(String(45), "sqlite"))
    internal: Mapped[int] = mapped_column(Integer)
    legacy: Mapped[str] = mapped_column("legacy_name", String)


class Scratch(Base):
    __tablename__ = "scratch"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )


# View DocumentSummary (document_summary) is not mapped: SQLAlchemy has no declarative view construct.
# Create the view in the database, then reflect it with
#     Table("document_summary", Base.metadata, autoload_with=engine)
# Columns: id, title, created_at, updated_at
