# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    Integer,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET
from sqlmodel import Field, Relationship, SQLModel


class Role(enum.Enum):
    ADMIN = "admin"
    USER = "user"


class Order(SQLModel, table=True):
    __tablename__ = "Order"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number", name="order_pkey"),
    )

    region: str
    number: int
    total: decimal.Decimal

    order_lines: list["OrderLine"] = Relationship(
        back_populates="order",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class OrderLine(SQLModel, table=True):
    __tablename__ = "OrderLine"
    __table_args__ = (
        ForeignKeyConstraint(
            ["orderRegion", "orderNumber"],
            ["Order.region", "Order.number"],
            name="fk_line_order",
            ondelete="CASCADE",
            onupdate="RESTRICT",
        ),
        Index("ix_OrderLine_orderRegion_orderNumber", "orderRegion", "orderNumber"),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    order_region: str = Field(sa_column_kwargs={"name": "orderRegion"})
    order_number: int = Field(sa_column_kwargs={"name": "orderNumber"})
    sku: str = Field(max_length=32)

    order: "Order" = Relationship(back_populates="order_lines")


class Tenant(SQLModel, table=True):
    __tablename__ = "Tenant"

    id: Optional[int] = Field(default=None, primary_key=True)

    accounts: list["Account"] = Relationship(back_populates="tenant")


class Account(SQLModel, table=True):
    __tablename__ = "Account"
    __table_args__ = (
        PrimaryKeyConstraint("id", name="account_pk"),
        UniqueConstraint("email", name="uq_account_email"),
    )

    id: int
    email: str
    tenant_id: int = Field(
        sa_column=Column(
            "tenantId",
            Integer,
            ForeignKey(
                "Tenant.id",
                ondelete="NO ACTION",
                onupdate="CASCADE",
                name="fk_account_tenant",
            ),
            nullable=False,
        ),
    )

    tenant: "Tenant" = Relationship(back_populates="accounts")
    profile: Optional["Profile"] = Relationship(back_populates="account")


class Profile(SQLModel, table=True):
    __tablename__ = "Profile"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number"),
    )

    region: str
    number: int
    account_id: int = Field(
        foreign_key="Account.id",
        ondelete="RESTRICT",
        unique=True,
        sa_column_kwargs={"name": "accountId"},
    )

    account: "Account" = Relationship(back_populates="profile")


class Document(SQLModel, table=True):
    __tablename__ = "documents"
    __table_args__ = (
        UniqueConstraint("ulid", name="uq_document_ulid"),
        Index("ix_document_title", "title", "created"),
        Index("ix_documents_meta", "meta"),
        UniqueConstraint("title", "day", name="uq_document_title_day"),
    )

    id: str = Field(primary_key=True)
    ulid: str
    short: str
    uid: uuid.UUID = Field(default_factory=uuid.uuid4)
    token: Optional[uuid.UUID] = Field(
        default=None,
        nullable=False,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    title: str
    body: str = Field(sa_type=Text)
    role: Role = Field(
        default=Role.USER,
        sa_type=Enum(
            Role,
            name="role_t",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "user"},
    )
    small: int
    ratio: float
    price: decimal.Decimal = Field(max_digits=10, decimal_places=2)
    cost: decimal.Decimal
    views: int = Field(sa_type=BigInteger)
    blob: bytes
    meta: Any = Field(sa_type=JSON)
    created: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    day: datetime.date
    at: datetime.time
    ip: str = Field(sa_type=INET().with_variant(String(45), "sqlite"))
    internal: int
    legacy: str = Field(sa_column_kwargs={"name": "legacy_name"})


class Scratch(SQLModel, table=True):
    __tablename__ = "Scratch"

    id: int = Field(primary_key=True, sa_column_kwargs={"autoincrement": False})


# View DocumentSummary (DocumentSummary) is not mapped: SQLAlchemy has no declarative view construct.
# Create the view in the database, then reflect it with
#     Table("DocumentSummary", SQLModel.metadata, autoload_with=engine)
# Columns: id, title
