# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    PrimaryKeyConstraint,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET
from sqlmodel import Field, Relationship, SQLModel


class Role(enum.Enum):
    ADMIN = "admin"
    USER = "user"


class Order(SQLModel, table=True):
    __tablename__ = "order"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number", name="order_pkey"),
    )

    region: str
    number: int
    total: decimal.Decimal
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    order_lines: list["OrderLine"] = Relationship(
        back_populates="order",
        sa_relationship_kwargs={"passive_deletes": True},
    )


class OrderLine(SQLModel, table=True):
    __tablename__ = "order_line"
    __table_args__ = (
        ForeignKeyConstraint(
            ["order_region", "order_number"],
            ["order.region", "order.number"],
            name="fk_line_order",
            ondelete="CASCADE",
            onupdate="RESTRICT",
        ),
        Index(
            "ix_order_line_order_region_order_number",
            "order_region",
            "order_number",
        ),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    order_region: str
    order_number: int
    sku: str = Field(max_length=32)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    order: "Order" = Relationship(back_populates="order_lines")


class Tenant(SQLModel, table=True):
    __tablename__ = "tenant"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )

    accounts: list["Account"] = Relationship(back_populates="tenant")


class Account(SQLModel, table=True):
    __tablename__ = "account"
    __table_args__ = (
        PrimaryKeyConstraint("id", name="account_pk"),
        UniqueConstraint("email", name="uq_account_email"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4)
    email: str
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    tenant_id: uuid.UUID = Field(
        sa_column=Column(
            "tenant_id",
            Uuid,
            ForeignKey(
                "tenant.id",
                ondelete="NO ACTION",
                onupdate="CASCADE",
                name="fk_account_tenant",
            ),
            nullable=False,
        ),
    )

    tenant: "Tenant" = Relationship(back_populates="accounts")
    profile: Optional["Profile"] = Relationship(back_populates="account")


class Profile(SQLModel, table=True):
    __tablename__ = "profile"
    __table_args__ = (
        PrimaryKeyConstraint("region", "number"),
    )

    region: str
    number: int
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    account_id: uuid.UUID = Field(
        foreign_key="account.id",
        ondelete="RESTRICT",
        unique=True,
    )

    account: "Account" = Relationship(back_populates="profile")


class Document(SQLModel, table=True):
    __tablename__ = "document"
    __table_args__ = (
        UniqueConstraint("ulid", name="uq_document_ulid"),
        Index("ix_document_title", "title", "created"),
        Index("ix_document_meta", "meta"),
        UniqueConstraint("title", "day", name="uq_document_title_day"),
    )

    id: str = Field(primary_key=True)
    ulid: str
    short: str
    uid: uuid.UUID = Field(default_factory=uuid.uuid4)
    token: Optional[uuid.UUID] = Field(
        default=None,
        nullable=False,
        sa_column_kwargs={"server_default": text("gen_random_uuid()")},
    )
    title: str
    body: str = Field(sa_type=Text)
    role: Role = Field(
        default=Role.USER,
        sa_type=Enum(
            Role,
            name="role_t",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "user"},
    )
    small: int
    ratio: float
    price: decimal.Decimal = Field(max_digits=10, decimal_places=2)
    cost: decimal.Decimal
    views: int = Field(sa_type=BigInteger)
    blob: bytes
    meta: Any = Field(sa_type=JSON)
    created: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    day: datetime.date
    at: datetime.time
    ip: str = Field(sa_type=INET().with_variant(String(45), "sqlite"))
    internal: int
    legacy: str = Field(sa_column_kwargs={"name": "legacy_name"})


class Scratch(SQLModel, table=True):
    __tablename__ = "scratch"

    id: int = Field(primary_key=True, sa_column_kwargs={"autoincrement": False})
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )


# View DocumentSummary (document_summary) is not mapped: SQLAlchemy has no declarative view construct.
# Create the view in the database, then reflect it with
#     Table("document_summary", SQLModel.metadata, autoload_with=engine)
# Columns: id, title, created_at, updated_at
