-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE "user" (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE category (
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(50) NOT NULL,
  parent_id CHAR(36),
  CONSTRAINT category_pkey PRIMARY KEY (id),
  CONSTRAINT category_name_key UNIQUE (name),
  CONSTRAINT category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES category (id) ON DELETE SET NULL
);

CREATE TABLE post (
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  public_id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL,
  status VARCHAR(9) NOT NULL DEFAULT 'draft',
  rating DECIMAL(4, 2),
  view_count INTEGER NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT 0,
  published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata TEXT NOT NULL DEFAULT '{}',
  author_id CHAR(36) NOT NULL,
  editor_id CHAR(36),
  category_id CHAR(36) NOT NULL,
  CONSTRAINT post_pkey PRIMARY KEY (id),
  CONSTRAINT post_public_id_key UNIQUE (public_id),
  CONSTRAINT post_status_check CHECK (status IN ('draft', 'published')),
  CONSTRAINT post_metadata_check CHECK (json_valid(metadata)),
  CONSTRAINT post_author_id_fkey FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE,
  CONSTRAINT post_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES "user" (id) ON DELETE SET NULL,
  CONSTRAINT post_category_id_fkey FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT
);
CREATE INDEX post_title_idx ON post (title);
CREATE UNIQUE INDEX post_author_id_title_key ON post (author_id, title);
CREATE INDEX post_pub_status_idx ON post (published_at, status);

CREATE TABLE tag (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  label VARCHAR(50) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT tag_pkey PRIMARY KEY (id)
);

CREATE TABLE profile (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  bio TEXT,
  avatar VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  user_id CHAR(36) NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_user_id_key UNIQUE (user_id),
  CONSTRAINT profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE
);

CREATE TABLE post_tag (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  post_id CHAR(36) NOT NULL,
  tag_id CHAR(36) NOT NULL,
  CONSTRAINT post_tag_pkey PRIMARY KEY (id),
  CONSTRAINT post_tag_post_id_fkey FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
  CONSTRAINT post_tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX post_tag_post_id_tag_id_key ON post_tag (post_id, tag_id);
