-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME,
  email VARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score REAL,
  avatar BLOB,
  payload TEXT,
  labels TEXT NOT NULL, -- an array stored as JSON
  ttl INTEGER, -- duration in microseconds
  ip TEXT,
  homepage_url TEXT,
  born DATE,
  alarm TIME,
  status VARCHAR(5) NOT NULL DEFAULT 'draft',
  note TEXT NOT NULL DEFAULT 'it''s; fine',
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email),
  CONSTRAINT account_payload_check CHECK (json_valid(payload)),
  CONSTRAINT account_labels_check CHECK (json_valid(labels)),
  CONSTRAINT account_status_check CHECK (status IN ('draft', 'live'))
);
CREATE INDEX account_deleted_at_idx ON account (deleted_at);
CREATE INDEX account_email_status_idx ON account (email, status);

CREATE TABLE session (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  token CHAR(36) DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  deleted_at DATETIME,
  opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  account_id CHAR(36),
  CONSTRAINT session_pkey PRIMARY KEY (id),
  CONSTRAINT session_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX session_account_id_opened_at_key ON session (account_id, opened_at);

CREATE TABLE "group" (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  name VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT group_pkey PRIMARY KEY (id)
);

CREATE TABLE membership (
  role VARCHAR(6) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  account_id CHAR(36) NOT NULL,
  group_id CHAR(36) NOT NULL,
  CONSTRAINT membership_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT membership_role_check CHECK (role IN ('owner', 'member')),
  CONSTRAINT membership_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE,
  CONSTRAINT membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE RESTRICT
);

CREATE TABLE profile (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  bio TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  owner_account_id CHAR(36) NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profile_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE legacy_order (
  order_no INTEGER NOT NULL,
  kind TEXT NOT NULL,
  http_code INTEGER NOT NULL,
  first_name TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  acct CHAR(36),
  CONSTRAINT legacy_order_pkey PRIMARY KEY (order_no),
  CONSTRAINT legacy_order_acct_fkey FOREIGN KEY (acct) REFERENCES account (id)
);

CREATE TABLE group_friend (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  from_group_id CHAR(36) NOT NULL,
  to_group_id CHAR(36) NOT NULL,
  CONSTRAINT group_friend_pkey PRIMARY KEY (id),
  CONSTRAINT group_friend_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES "group" (id) ON DELETE CASCADE,
  CONSTRAINT group_friend_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES "group" (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX group_friend_from_group_id_to_group_id_key ON group_friend (from_group_id, to_group_id);
