-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME,
  email VARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score REAL,
  avatar BLOB,
  payload TEXT,
  labels TEXT NOT NULL, -- an array stored as JSON
  ttl INTEGER, -- duration in microseconds
  ip TEXT,
  homepage_url TEXT,
  born DATE,
  alarm TIME,
  status VARCHAR(5) NOT NULL DEFAULT 'draft',
  note TEXT NOT NULL DEFAULT 'it''s; fine',
  CONSTRAINT accounts_email_key UNIQUE (email),
  CONSTRAINT accounts_payload_check CHECK (json_valid(payload)),
  CONSTRAINT accounts_labels_check CHECK (json_valid(labels)),
  CONSTRAINT accounts_status_check CHECK (status IN ('draft', 'live'))
);
CREATE INDEX accounts_deleted_at_idx ON accounts (deleted_at);
CREATE INDEX accounts_email_status_idx ON accounts (email, status);

CREATE TABLE sessions (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  token CHAR(36) DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  deleted_at DATETIME,
  opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  account_id BIGINT,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX sessions_account_id_opened_at_key ON sessions (account_id, opened_at);

CREATE TABLE "groups" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(40) NOT NULL
);

CREATE TABLE memberships (
  role VARCHAR(6) NOT NULL,
  account_id BIGINT NOT NULL,
  group_id INTEGER NOT NULL,
  CONSTRAINT memberships_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT memberships_role_check CHECK (role IN ('owner', 'member')),
  CONSTRAINT memberships_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
  CONSTRAINT memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES "groups" (id) ON DELETE RESTRICT
);

CREATE TABLE profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bio TEXT,
  owner_account_id BIGINT NOT NULL,
  CONSTRAINT profiles_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profiles_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE "LEGACY_ORDER" (
  "OrderNo" INTEGER NOT NULL,
  kind TEXT NOT NULL,
  http_code INTEGER NOT NULL,
  "first name" TEXT,
  acct BIGINT,
  CONSTRAINT "LEGACY_ORDER_pkey" PRIMARY KEY ("OrderNo"),
  CONSTRAINT "LEGACY_ORDER_acct_fkey" FOREIGN KEY (acct) REFERENCES accounts (id)
);

CREATE TABLE groups_friends (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  from_group_id INTEGER NOT NULL,
  to_group_id INTEGER NOT NULL,
  CONSTRAINT groups_friends_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES "groups" (id) ON DELETE CASCADE,
  CONSTRAINT groups_friends_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES "groups" (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX groups_friends_from_group_id_to_group_id_key ON groups_friends (from_group_id, to_group_id);
