-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE other (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT other_pkey PRIMARY KEY (id)
);

CREATE TABLE weird (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  a_b TEXT NOT NULL DEFAULT 'x;y',
  quote TEXT NOT NULL DEFAULT 'say "hi"',
  tick TEXT NOT NULL DEFAULT 'a`b',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  self_id CHAR(36),
  other_id CHAR(36) NOT NULL,
  CONSTRAINT weird_pkey PRIMARY KEY (id),
  CONSTRAINT weird_self_id_fkey FOREIGN KEY (self_id) REFERENCES weird (id) ON DELETE SET NULL,
  CONSTRAINT weird_other_id_fkey FOREIGN KEY (other_id) REFERENCES other (id) ON DELETE CASCADE
);
