-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE "others" (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE weird (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  "a;b" TEXT NOT NULL DEFAULT 'x;y',
  quote TEXT NOT NULL DEFAULT 'say "hi"',
  tick TEXT NOT NULL DEFAULT 'a`b',
  self_id INTEGER,
  other_id INTEGER NOT NULL,
  CONSTRAINT weird_self_id_fkey FOREIGN KEY (self_id) REFERENCES weird (id) ON DELETE SET NULL,
  CONSTRAINT weird_other_id_fkey FOREIGN KEY (other_id) REFERENCES "others" (id) ON DELETE CASCADE
);
