-- SQL Server: a script generated by SSMS, with GO batches and bracketed names.
USE [Inventory]
GO
SET ANSI_NULLS ON
GO

CREATE TABLE [inv].[Warehouse](
	[WarehouseId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nchar](4) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Opened] [date] NULL,
	[RowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK_Warehouse] PRIMARY KEY CLUSTERED
(
	[WarehouseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [inv].[Item](
	[ItemId] [bigint] IDENTITY(100,5) NOT NULL,
	[Sku] [varchar](20) NOT NULL,
	[Price] [money] NOT NULL,
	[Weight] [float] NULL,
	[Qty] [int] NOT NULL,
	[Total]  AS ([Qty]*[Price]) PERSISTED,
	[Guid] [uniqueidentifier] NOT NULL DEFAULT (newsequentialid()),
	[Added] [datetimeoffset](7) NOT NULL,
	[Notes] [varchar](max) NULL,
	[Photo] [varbinary](max) NULL,
	[WarehouseId] [int] NOT NULL FOREIGN KEY REFERENCES [inv].[Warehouse]([WarehouseId]) ON DELETE CASCADE,
	[Kind] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY NONCLUSTERED ([ItemId]),
 CONSTRAINT [CK_Item_Kind] CHECK  (([Kind]='part' OR [Kind]='tool' OR [Kind]='kit'))
)
GO

ALTER TABLE [inv].[Item] ADD CONSTRAINT [DF_Item_Qty] DEFAULT ((0)) FOR [Qty]
GO
ALTER TABLE [inv].[Item] ADD CONSTRAINT [DF_Item_Added] DEFAULT (sysdatetimeoffset()) FOR [Added]
GO

CREATE UNIQUE NONCLUSTERED INDEX [UX_Item_Sku] ON [inv].[Item] ([Sku] ASC) WHERE ([Sku] IS NOT NULL)
GO
CREATE NONCLUSTERED INDEX [IX_Item_Warehouse] ON [inv].[Item] ([WarehouseId] ASC, [Kind] DESC) INCLUDE ([Qty])
GO

CREATE PROCEDURE [inv].[Restock] @id int
AS
BEGIN
  UPDATE [inv].[Item] SET [Qty] = [Qty] + 1 WHERE [ItemId] = @id;
  IF @id > 0 BEGIN SELECT 1; END;
END
GO

INSERT [inv].[Warehouse] ([Code], [Name]) VALUES (N'MAIN', N'Main''s depot')
GO
