--
-- PostgreSQL: a pg_dump-like script with the awkward constructs.
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET search_path = public, pg_catalog;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE SCHEMA IF NOT EXISTS billing;

/* block comments /* nest */ in PostgreSQL */

CREATE TYPE public.order_state AS ENUM ('new', 'paid', 'shipped', 'cancelled');
ALTER TYPE public.order_state ADD VALUE 'refunded' AFTER 'paid';
CREATE TYPE public.address AS (street text, city text);

CREATE SEQUENCE public.legacy_seq START 1;

CREATE TABLE public.customers (
    customer_id bigserial PRIMARY KEY,
    email citext NOT NULL,
    full_name character varying NOT NULL,
    nickname text DEFAULT 'it''s me'::text,
    age smallint CONSTRAINT age_positive CHECK (age >= 0),
    balance numeric(12,2) NOT NULL DEFAULT 0.00,
    ratio double precision DEFAULT 1.5,
    tags text[] NOT NULL DEFAULT '{}'::text[],
    scores integer[][],
    last_ip inet,
    active_during daterange,
    attrs hstore,
    location geometry(Point, 4326),
    "Signed Up At" timestamp(3) without time zone NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    UNIQUE (email)
);

CREATE TABLE public.products (
    sku text PRIMARY KEY,
    title varchar(120) NOT NULL,
    price numeric(10, 2) NOT NULL DEFAULT 9.99,
    description text
);

CREATE TABLE public.orders (
    order_no integer NOT NULL,
    customer_id bigint NOT NULL REFERENCES public.customers (customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    state public.order_state DEFAULT 'new'::public.order_state NOT NULL,
    placed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    tax numeric(12,2) DEFAULT 0 NOT NULL,
    total numeric(12,2) GENERATED ALWAYS AS (subtotal + tax) STORED,
    CONSTRAINT orders_pkey PRIMARY KEY (order_no)
);

CREATE TABLE public.order_items (
    order_no integer NOT NULL,
    line_no integer NOT NULL,
    product_sku text NOT NULL,
    quantity integer DEFAULT 1 NOT NULL,
    PRIMARY KEY (order_no, line_no),
    FOREIGN KEY (order_no) REFERENCES public.orders (order_no) ON DELETE CASCADE
);

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES public.products (sku);

CREATE TABLE public.product_prices (
    region text NOT NULL,
    sku text NOT NULL,
    amount numeric(10,2) NOT NULL,
    PRIMARY KEY (region, sku)
);

CREATE TABLE public.price_notes (
    id integer NOT NULL,
    region text NOT NULL,
    sku text,
    note text,
    CONSTRAINT fk_price FOREIGN KEY (region, sku) REFERENCES public.product_prices (region, sku) ON DELETE CASCADE ON UPDATE NO ACTION
);

ALTER TABLE ONLY public.price_notes ALTER COLUMN id SET DEFAULT nextval('public.price_notes_id_seq'::regclass);
ALTER TABLE ONLY public.price_notes ADD CONSTRAINT price_notes_pkey PRIMARY KEY (id);

CREATE TABLE public.newsletter (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_email citext NOT NULL REFERENCES public.customers (email) ON DELETE CASCADE
);

CREATE TABLE public.customer_profiles (
    customer_id bigint PRIMARY KEY REFERENCES public.customers ON DELETE CASCADE,
    bio text
);

CREATE TABLE public.customers_favourites (
    customer_id bigint NOT NULL REFERENCES public.customers (customer_id),
    product_sku text NOT NULL REFERENCES public.products (sku),
    PRIMARY KEY (customer_id, product_sku)
);

CREATE TABLE billing.invoices (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_no integer NOT NULL UNIQUE REFERENCES public.orders,
    state varchar(20) NOT NULL CHECK (state IN ('open', 'paid', 'void')),
    issued date DEFAULT CURRENT_DATE,
    notes jsonb DEFAULT '[]'
);

CREATE TABLE public.no_key (
    value text
);

CREATE INDEX customers_tags_idx ON public.customers USING gin (tags);
CREATE INDEX customers_lower_email_idx ON public.customers (lower(email));
CREATE UNIQUE INDEX customers_active_name_idx ON public.customers (full_name) WHERE age > 18;
CREATE INDEX orders_placed_idx ON public.orders (placed_at DESC NULLS LAST, customer_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS products_title_idx ON ONLY public.products USING btree (title text_pattern_ops) INCLUDE (price);

CREATE VIEW public.big_orders AS SELECT * FROM public.orders WHERE total > 100;

CREATE FUNCTION public.touch() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.placed_at := now();
    RETURN NEW; -- a ; inside a body
END;
$$;

CREATE TRIGGER orders_touch BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.touch();

INSERT INTO public.products (sku, title) VALUES ('a-1', 'Anvil');
INSERT INTO public.products (sku, title) VALUES ('b-2', 'Bellows');

COPY public.customers (customer_id, email) FROM stdin;
1	a@example.com
2	create table fake (x int);
\.

COMMENT ON TABLE public.orders IS 'Customer orders';
COMMENT ON COLUMN public.orders.state IS 'The lifecycle state';
GRANT SELECT ON public.orders TO PUBLIC;
