# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    LargeBinary,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    Uuid,
    func,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Role(enum.Enum):
    Customer = "customer"
    Staff = "staff"
    Admin = "admin"


shop_orders_labels = Table(
    "shop_orders_labels",
    Base.metadata,
    Column(
        "order_id",
        ForeignKey("shop_orders.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("label_id", ForeignKey("labels.id", ondelete="CASCADE"), primary_key=True),
)


products_similar = Table(
    "products_similar",
    Base.metadata,
    Column(
        "from_product_id",
        ForeignKey("products.sku", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "to_product_id",
        ForeignKey("products.sku", ondelete="CASCADE"),
        primary_key=True,
    ),
)


class Customer(Base):
    __tablename__ = "customers"
    __table_args__ = (
        Index("ix_customers_deleted_at", "deleted_at"),
    )

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True)
    name: Mapped[Optional[str]] = mapped_column(String(100))
    role: Mapped[Role] = mapped_column(
        Enum(
            Role,
            name="Role",
            values_callable=lambda members: [member.value for member in members],
        ),
        server_default="customer",
    )
    billing_street: Mapped[str] = mapped_column(String(120))
    billing_city: Mapped[str] = mapped_column(String(60))
    billing_postal: Mapped[Optional[str]] = mapped_column("billing_zip", String(12))
    shipping_street: Mapped[str] = mapped_column(String(120))
    shipping_city: Mapped[str] = mapped_column(String(60))
    shipping_postal: Mapped[Optional[str]] = mapped_column("shipping_zip", String(12))
    balance: Mapped[decimal.Decimal] = mapped_column(
        Numeric(12, 2),
        server_default=text("0"),
    )
    rank: Mapped[int] = mapped_column(BigInteger)
    avatar: Mapped[bytes] = mapped_column(LargeBinary)
    settings: Mapped[Any] = mapped_column(JSON)

    orders: Mapped[list["Order"]] = relationship(back_populates="customer")


class Order(Base):
    __tablename__ = "shop_orders"
    __table_args__ = (
        Index("idx_order_customer_placed", "customer_id", "placed_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    placed_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    modified_at: Mapped[int] = mapped_column(BigInteger)
    total: Mapped[decimal.Decimal] = mapped_column(Numeric(12, 2))
    note: Mapped[str] = mapped_column(String(500))
    customer_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("customers.id", ondelete="RESTRICT", onupdate="CASCADE"),
    )

    customer: Mapped["Customer"] = relationship(back_populates="orders")
    labels: Mapped[list["Label"]] = relationship(
        back_populates="orders",
        secondary=shop_orders_labels,
    )
    items: Mapped[list["OrderItem"]] = relationship(back_populates="order")


class Product(Base):
    __tablename__ = "products"
    __table_args__ = (
        Index("ix_products_title", "title"),
        Index("idx_product_slug", "slug"),
    )

    sku: Mapped[str] = mapped_column(String(40), primary_key=True)
    title: Mapped[str] = mapped_column(String(200))
    slug: Mapped[str] = mapped_column(String(100))
    price: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2))
    stock: Mapped[int] = mapped_column("in_stock", Integer, server_default=text("0"))
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True),
    )

    similar: Mapped[list["Product"]] = relationship(
        back_populates="products",
        secondary=products_similar,
        primaryjoin=lambda: Product.sku == products_similar.c.from_product_id,
        secondaryjoin=lambda: Product.sku == products_similar.c.to_product_id,
    )
    order_items: Mapped[list["OrderItem"]] = relationship(back_populates="product")
    products: Mapped[list["Product"]] = relationship(
        back_populates="similar",
        secondary=products_similar,
        primaryjoin=lambda: Product.sku == products_similar.c.to_product_id,
        secondaryjoin=lambda: Product.sku == products_similar.c.from_product_id,
    )


class OrderItem(Base):
    __tablename__ = "order_items"
    __table_args__ = (
        PrimaryKeyConstraint("order_id", "line_no"),
    )

    line_no: Mapped[int] = mapped_column(Integer)
    quantity: Mapped[int] = mapped_column(Integer, server_default=text("1"))
    product_sku: Mapped[str] = mapped_column(
        String(40),
        ForeignKey("products.sku", ondelete="NO ACTION"),
    )
    order_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("shop_orders.id", ondelete="NO ACTION"),
    )

    product: Mapped["Product"] = relationship(back_populates="order_items")
    order: Mapped["Order"] = relationship(back_populates="items")


class Label(Base):
    __tablename__ = "labels"

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    name: Mapped[str] = mapped_column(String(40), unique=True)

    orders: Mapped[list["Order"]] = relationship(
        back_populates="labels",
        secondary=shop_orders_labels,
    )


class Comment(Base):
    __tablename__ = "comments"

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    body: Mapped[str] = mapped_column(Text)
    owner_id: Mapped[int] = mapped_column(BigInteger)
    owner_type: Mapped[str] = mapped_column(String(30))
