# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    Uuid,
    func,
    text,
)
from sqlmodel import Field, Relationship, SQLModel


class Role(enum.Enum):
    Customer = "customer"
    Staff = "staff"
    Admin = "admin"


shop_orders_labels = Table(
    "shop_orders_labels",
    SQLModel.metadata,
    Column(
        "order_id",
        ForeignKey("shop_orders.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column("label_id", ForeignKey("labels.id", ondelete="CASCADE"), primary_key=True),
)


products_similar = Table(
    "products_similar",
    SQLModel.metadata,
    Column(
        "from_product_id",
        ForeignKey("products.sku", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "to_product_id",
        ForeignKey("products.sku", ondelete="CASCADE"),
        primary_key=True,
    ),
)


class Customer(SQLModel, table=True):
    __tablename__ = "customers"
    __table_args__ = (
        Index("ix_customers_deleted_at", "deleted_at"),
    )

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    deleted_at: Optional[datetime.datetime] = Field(
        default=None,
        sa_type=DateTime(timezone=True),
    )
    email: str = Field(unique=True, max_length=255)
    name: Optional[str] = Field(default=None, max_length=100)
    role: Role = Field(
        default=Role.Customer,
        sa_type=Enum(
            Role,
            name="Role",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "customer"},
    )
    billing_street: str = Field(max_length=120)
    billing_city: str = Field(max_length=60)
    billing_postal: Optional[str] = Field(
        default=None,
        max_length=12,
        sa_column_kwargs={"name": "billing_zip"},
    )
    shipping_street: str = Field(max_length=120)
    shipping_city: str = Field(max_length=60)
    shipping_postal: Optional[str] = Field(
        default=None,
        max_length=12,
        sa_column_kwargs={"name": "shipping_zip"},
    )
    balance: Optional[decimal.Decimal] = Field(
        default=None,
        nullable=False,
        max_digits=12,
        decimal_places=2,
        sa_column_kwargs={"server_default": text("0")},
    )
    rank: int = Field(sa_type=BigInteger)
    avatar: bytes
    settings: Any = Field(sa_type=JSON)

    orders: list["Order"] = Relationship(back_populates="customer")


class Order(SQLModel, table=True):
    __tablename__ = "shop_orders"
    __table_args__ = (
        Index("idx_order_customer_placed", "customer_id", "placed_at"),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    placed_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    modified_at: int = Field(sa_type=BigInteger)
    total: decimal.Decimal = Field(max_digits=12, decimal_places=2)
    note: str = Field(max_length=500)
    customer_id: int = Field(
        sa_column=Column(
            "customer_id",
            BigInteger,
            ForeignKey("customers.id", ondelete="RESTRICT", onupdate="CASCADE"),
            nullable=False,
        ),
    )

    customer: "Customer" = Relationship(back_populates="orders")
    labels: list["Label"] = Relationship(
        back_populates="orders",
        sa_relationship_kwargs={"secondary": shop_orders_labels},
    )
    items: list["OrderItem"] = Relationship(back_populates="order")


class Product(SQLModel, table=True):
    __tablename__ = "products"
    __table_args__ = (
        Index("ix_products_title", "title"),
        Index("idx_product_slug", "slug"),
    )

    sku: str = Field(primary_key=True, max_length=40)
    title: str = Field(max_length=200)
    slug: str = Field(max_length=100)
    price: decimal.Decimal = Field(max_digits=10, decimal_places=2)
    stock: int = Field(
        default=0,
        sa_column_kwargs={"name": "in_stock", "server_default": text("0")},
    )
    deleted_at: Optional[datetime.datetime] = Field(
        default=None,
        sa_type=DateTime(timezone=True),
    )

    similar: list["Product"] = Relationship(
        back_populates="products",
        sa_relationship_kwargs={
            "secondary": products_similar,
            "primaryjoin": lambda: Product.sku == products_similar.c.from_product_id,
            "secondaryjoin": lambda: Product.sku == products_similar.c.to_product_id,
        },
    )
    order_items: list["OrderItem"] = Relationship(back_populates="product")
    products: list["Product"] = Relationship(
        back_populates="similar",
        sa_relationship_kwargs={
            "secondary": products_similar,
            "primaryjoin": lambda: Product.sku == products_similar.c.to_product_id,
            "secondaryjoin": lambda: Product.sku == products_similar.c.from_product_id,
        },
    )


class OrderItem(SQLModel, table=True):
    __tablename__ = "order_items"
    __table_args__ = (
        PrimaryKeyConstraint("order_id", "line_no"),
    )

    line_no: int
    quantity: int = Field(default=1, sa_column_kwargs={"server_default": text("1")})
    product_sku: str = Field(
        sa_column=Column(
            "product_sku",
            String(40),
            ForeignKey("products.sku", ondelete="NO ACTION"),
            nullable=False,
        ),
    )
    order_id: uuid.UUID = Field(
        sa_column=Column(
            "order_id",
            Uuid,
            ForeignKey("shop_orders.id", ondelete="NO ACTION"),
            nullable=False,
        ),
    )

    product: "Product" = Relationship(back_populates="order_items")
    order: "Order" = Relationship(back_populates="items")


class Label(SQLModel, table=True):
    __tablename__ = "labels"

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )
    name: str = Field(unique=True, max_length=40)

    orders: list["Order"] = Relationship(
        back_populates="labels",
        sa_relationship_kwargs={"secondary": shop_orders_labels},
    )


class Comment(SQLModel, table=True):
    __tablename__ = "comments"

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )
    body: str = Field(sa_type=Text)
    owner_id: int = Field(sa_type=BigInteger)
    owner_type: str = Field(max_length=30)
