-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE role_t AS ENUM ('admin', 'user');

CREATE TABLE "order" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  total MONEY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE order_line (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  order_region TEXT NOT NULL,
  order_number INTEGER NOT NULL,
  sku VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT order_line_pkey PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY (order_region, order_number) REFERENCES "order" (region, number) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX order_line_order_region_order_number_idx ON order_line (order_region, order_number);

CREATE TABLE tenant (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  tenant_id UUID NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON UPDATE CASCADE
);

CREATE TABLE profile (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  account_id UUID NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (region, number),
  CONSTRAINT profile_account_id_key UNIQUE (account_id),
  CONSTRAINT profile_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT
);

CREATE TABLE document (
  id TEXT NOT NULL,
  ulid TEXT NOT NULL,
  short TEXT NOT NULL,
  uid UUID NOT NULL DEFAULT gen_random_uuid(),
  token UUID NOT NULL DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  role role_t NOT NULL DEFAULT 'user',
  small SMALLINT NOT NULL,
  ratio REAL NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  cost MONEY NOT NULL,
  views BIGINT NOT NULL,
  "blob" BYTEA NOT NULL,
  meta JSONB NOT NULL,
  created TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated TIMESTAMP(0) NOT NULL,
  day DATE NOT NULL,
  at TIMETZ(3) NOT NULL,
  ip INET NOT NULL,
  internal INTEGER NOT NULL,
  legacy_name TEXT NOT NULL,
  CONSTRAINT document_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid)
);
CREATE INDEX ix_document_title ON document USING btree (title DESC, created);
CREATE INDEX document_meta_idx ON document USING gin (meta jsonb_path_ops);
CREATE UNIQUE INDEX uq_document_title_day ON document (title, day);

CREATE TABLE scratch (
  id INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT scratch_pkey PRIMARY KEY (id)
);

-- View document_summary: the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title, created_at, updated_at
-- CREATE VIEW document_summary AS SELECT ... ;
