-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE role_t AS ENUM ('admin', 'user');

CREATE TABLE "Order" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  total MONEY NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE "OrderLine" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "orderRegion" TEXT NOT NULL,
  "orderNumber" INTEGER NOT NULL,
  sku VARCHAR(32) NOT NULL,
  CONSTRAINT "OrderLine_pkey" PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY ("orderRegion", "orderNumber") REFERENCES "Order" (region, number) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX "OrderLine_orderRegion_orderNumber_idx" ON "OrderLine" ("orderRegion", "orderNumber");

CREATE TABLE "Tenant" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT "Tenant_pkey" PRIMARY KEY (id)
);

CREATE TABLE "Account" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email TEXT NOT NULL,
  "tenantId" INTEGER NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY ("tenantId") REFERENCES "Tenant" (id) ON UPDATE CASCADE
);

CREATE TABLE "Profile" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  "accountId" INTEGER NOT NULL,
  CONSTRAINT "Profile_pkey" PRIMARY KEY (region, number),
  CONSTRAINT "Profile_accountId_key" UNIQUE ("accountId"),
  CONSTRAINT "Profile_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account" (id) ON DELETE RESTRICT
);

CREATE TABLE documents (
  id TEXT NOT NULL,
  ulid TEXT NOT NULL,
  short TEXT NOT NULL,
  uid UUID NOT NULL DEFAULT gen_random_uuid(),
  token UUID NOT NULL DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  role role_t NOT NULL DEFAULT 'user',
  small SMALLINT NOT NULL,
  ratio REAL NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  cost MONEY NOT NULL,
  views BIGINT NOT NULL,
  "blob" BYTEA NOT NULL,
  meta JSONB NOT NULL,
  created TIMESTAMPTZ(3) NOT NULL DEFAULT now(),
  updated TIMESTAMP(0) NOT NULL,
  day DATE NOT NULL,
  at TIMETZ(3) NOT NULL,
  ip INET NOT NULL,
  internal INTEGER NOT NULL,
  legacy_name TEXT NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid)
);
CREATE INDEX ix_document_title ON documents USING btree (title DESC, created);
CREATE INDEX documents_meta_idx ON documents USING gin (meta jsonb_path_ops);
CREATE UNIQUE INDEX uq_document_title_day ON documents (title, day);

CREATE TABLE "Scratch" (
  id INTEGER NOT NULL,
  CONSTRAINT "Scratch_pkey" PRIMARY KEY (id)
);

-- View "DocumentSummary": the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title
-- CREATE VIEW "DocumentSummary" AS SELECT ... ;
