-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE customer (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role ENUM('customer', 'staff', 'admin') NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `rank` BIGINT NOT NULL,
  avatar LONGBLOB NOT NULL,
  settings JSON NOT NULL,
  CONSTRAINT customer_pkey PRIMARY KEY (id),
  CONSTRAINT customer_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX customer_deleted_at_idx ON customer (deleted_at);

CREATE TABLE `order` (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  placed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  customer_id CHAR(36) NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id),
  CONSTRAINT order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_order_customer_placed ON `order` (customer_id, placed_at DESC);

CREATE TABLE product (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INT NOT NULL DEFAULT 0,
  deleted_at DATETIME(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT product_pkey PRIMARY KEY (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE FULLTEXT INDEX product_title_idx ON product (title);
CREATE INDEX idx_product_slug ON product (slug) USING HASH;

CREATE TABLE order_item (
  line_no INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  product_sku VARCHAR(40) NOT NULL,
  order_id CHAR(36) NOT NULL,
  CONSTRAINT order_item_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_item_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES product (sku),
  CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES `order` (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE label (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  name VARCHAR(40) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT label_pkey PRIMARY KEY (id),
  CONSTRAINT label_name_key UNIQUE (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comment (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  body LONGTEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT comment_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE order_label (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  order_id CHAR(36) NOT NULL,
  label_id CHAR(36) NOT NULL,
  CONSTRAINT order_label_pkey PRIMARY KEY (id),
  CONSTRAINT order_label_order_id_fkey FOREIGN KEY (order_id) REFERENCES `order` (id) ON DELETE CASCADE,
  CONSTRAINT order_label_label_id_fkey FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX order_label_order_id_label_id_key ON order_label (order_id, label_id);

CREATE TABLE product_similar (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT product_similar_pkey PRIMARY KEY (id),
  CONSTRAINT product_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES product (sku) ON DELETE CASCADE,
  CONSTRAINT product_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES product (sku) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX product_similar_from_product_id_to_product_id_key ON product_similar (from_product_id, to_product_id);
