-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE customers (
  id BIGINT NOT NULL AUTO_INCREMENT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role ENUM('customer', 'staff', 'admin') NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  `rank` BIGINT NOT NULL,
  avatar LONGBLOB NOT NULL,
  settings JSON NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX customers_deleted_at_idx ON customers (deleted_at);

CREATE TABLE shop_orders (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  placed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  customer_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX idx_order_customer_placed ON shop_orders (customer_id, placed_at DESC);

CREATE TABLE products (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INT NOT NULL DEFAULT 0,
  deleted_at DATETIME(6),
  CONSTRAINT products_pkey PRIMARY KEY (sku)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE FULLTEXT INDEX products_title_idx ON products (title);
CREATE INDEX idx_product_slug ON products (slug) USING HASH;

CREATE TABLE order_items (
  line_no INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  product_sku VARCHAR(40) NOT NULL,
  order_id CHAR(36) NOT NULL,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES products (sku),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE labels (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  CONSTRAINT labels_pkey PRIMARY KEY (id),
  CONSTRAINT labels_name_key UNIQUE (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comments (
  id BIGINT NOT NULL AUTO_INCREMENT,
  body LONGTEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL,
  CONSTRAINT comments_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE shop_orders_labels (
  id INT NOT NULL AUTO_INCREMENT,
  order_id CHAR(36) NOT NULL,
  label_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_labels_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_labels_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id) ON DELETE CASCADE,
  CONSTRAINT shop_orders_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX shop_orders_labels_order_id_label_id_key ON shop_orders_labels (order_id, label_id);

CREATE TABLE products_similar (
  id INT NOT NULL AUTO_INCREMENT,
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT products_similar_pkey PRIMARY KEY (id),
  CONSTRAINT products_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES products (sku) ON DELETE CASCADE,
  CONSTRAINT products_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES products (sku) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX products_similar_from_product_id_to_product_id_key ON products_similar (from_product_id, to_product_id);
