-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE account (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  deleted_at DATETIME2 NULL,
  email NVARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score FLOAT NULL,
  avatar VARBINARY(MAX) NULL,
  payload NVARCHAR(MAX) NULL,
  labels NVARCHAR(MAX) NOT NULL, -- an array stored as JSON
  ttl BIGINT NULL, -- duration in microseconds
  ip VARCHAR(45) NULL,
  homepage_url NVARCHAR(255) NULL,
  born DATE NULL,
  alarm TIME NULL,
  status NVARCHAR(50) NOT NULL DEFAULT N'draft',
  note NVARCHAR(MAX) NOT NULL DEFAULT N'it''s; fine',
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email),
  CONSTRAINT account_payload_check CHECK (ISJSON(payload) = 1),
  CONSTRAINT account_labels_check CHECK (ISJSON(labels) = 1),
  CONSTRAINT account_status_check CHECK (status IN (N'draft', N'live'))
);
CREATE INDEX account_deleted_at_idx ON account (deleted_at);
CREATE INDEX account_email_status_idx ON account (email, status);

CREATE TABLE session (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  token UNIQUEIDENTIFIER NULL DEFAULT NEWID(),
  deleted_at DATETIME2 NULL,
  opened_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  account_id UNIQUEIDENTIFIER NULL,
  CONSTRAINT session_pkey PRIMARY KEY (id),
  CONSTRAINT session_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX session_account_id_opened_at_key ON session (account_id, opened_at) WHERE account_id IS NOT NULL;

CREATE TABLE [group] (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  name NVARCHAR(40) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT group_pkey PRIMARY KEY (id)
);

CREATE TABLE membership (
  role NVARCHAR(50) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  account_id UNIQUEIDENTIFIER NOT NULL,
  group_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT membership_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT membership_role_check CHECK (role IN (N'owner', N'member')),
  CONSTRAINT membership_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE,
  CONSTRAINT membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES [group] (id)
);

CREATE TABLE profile (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  bio NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  owner_account_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profile_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE legacy_order (
  order_no INT NOT NULL,
  kind NVARCHAR(255) NOT NULL,
  http_code INT NOT NULL,
  first_name NVARCHAR(255) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  acct UNIQUEIDENTIFIER NULL,
  CONSTRAINT legacy_order_pkey PRIMARY KEY (order_no),
  CONSTRAINT legacy_order_acct_fkey FOREIGN KEY (acct) REFERENCES account (id)
);

CREATE TABLE group_friend (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  from_group_id UNIQUEIDENTIFIER NOT NULL,
  to_group_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT group_friend_pkey PRIMARY KEY (id),
  CONSTRAINT group_friend_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES [group] (id) ON DELETE CASCADE,
  CONSTRAINT group_friend_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES [group] (id)
);
CREATE UNIQUE INDEX group_friend_from_group_id_to_group_id_key ON group_friend (from_group_id, to_group_id);
