-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE accounts (
  id BIGINT IDENTITY(1,1) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  deleted_at DATETIME2 NULL,
  email NVARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score FLOAT NULL,
  avatar VARBINARY(MAX) NULL,
  payload NVARCHAR(MAX) NULL,
  labels NVARCHAR(MAX) NOT NULL, -- an array stored as JSON
  ttl BIGINT NULL, -- duration in microseconds
  ip VARCHAR(45) NULL,
  homepage_url NVARCHAR(255) NULL,
  born DATE NULL,
  alarm TIME NULL,
  status NVARCHAR(50) NOT NULL DEFAULT N'draft',
  note NVARCHAR(MAX) NOT NULL DEFAULT N'it''s; fine',
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_email_key UNIQUE (email),
  CONSTRAINT accounts_payload_check CHECK (ISJSON(payload) = 1),
  CONSTRAINT accounts_labels_check CHECK (ISJSON(labels) = 1),
  CONSTRAINT accounts_status_check CHECK (status IN (N'draft', N'live'))
);
CREATE INDEX accounts_deleted_at_idx ON accounts (deleted_at);
CREATE INDEX accounts_email_status_idx ON accounts (email, status);

CREATE TABLE sessions (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  token UNIQUEIDENTIFIER NULL DEFAULT NEWID(),
  deleted_at DATETIME2 NULL,
  opened_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  account_id BIGINT NULL,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX sessions_account_id_opened_at_key ON sessions (account_id, opened_at) WHERE account_id IS NOT NULL;

CREATE TABLE [groups] (
  id INT IDENTITY(1,1) NOT NULL,
  name NVARCHAR(40) NOT NULL,
  CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE memberships (
  role NVARCHAR(50) NOT NULL,
  account_id BIGINT NOT NULL,
  group_id INT NOT NULL,
  CONSTRAINT memberships_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT memberships_role_check CHECK (role IN (N'owner', N'member')),
  CONSTRAINT memberships_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
  CONSTRAINT memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES [groups] (id)
);

CREATE TABLE profiles (
  id INT IDENTITY(1,1) NOT NULL,
  bio NVARCHAR(MAX) NULL,
  owner_account_id BIGINT NOT NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profiles_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE [LEGACY_ORDER] (
  [OrderNo] INT NOT NULL,
  kind NVARCHAR(255) NOT NULL,
  http_code INT NOT NULL,
  [first name] NVARCHAR(255) NULL,
  acct BIGINT NULL,
  CONSTRAINT [LEGACY_ORDER_pkey] PRIMARY KEY ([OrderNo]),
  CONSTRAINT [LEGACY_ORDER_acct_fkey] FOREIGN KEY (acct) REFERENCES accounts (id)
);

CREATE TABLE groups_friends (
  id INT IDENTITY(1,1) NOT NULL,
  from_group_id INT NOT NULL,
  to_group_id INT NOT NULL,
  CONSTRAINT groups_friends_pkey PRIMARY KEY (id),
  CONSTRAINT groups_friends_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES [groups] (id) ON DELETE CASCADE,
  CONSTRAINT groups_friends_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES [groups] (id)
);
CREATE UNIQUE INDEX groups_friends_from_group_id_to_group_id_key ON groups_friends (from_group_id, to_group_id);
