-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE auth_user (
  id INT NOT NULL AUTO_INCREMENT,
  CONSTRAINT auth_user_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_category (
  id INT NOT NULL AUTO_INCREMENT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(50) NOT NULL,
  parent_id INT,
  CONSTRAINT blog_category_pkey PRIMARY KEY (id),
  CONSTRAINT blog_category_name_key UNIQUE (name),
  CONSTRAINT blog_category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES blog_category (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_post (
  id INT NOT NULL AUTO_INCREMENT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  public_id CHAR(36) NOT NULL DEFAULT (UUID()),
  title VARCHAR(200) NOT NULL,
  body LONGTEXT NOT NULL,
  status ENUM('draft', 'published') NOT NULL DEFAULT 'draft',
  rating DECIMAL(4, 2),
  view_count INT NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  published_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  metadata JSON NOT NULL DEFAULT ('{}'),
  author_id INT NOT NULL,
  editor_id INT,
  category_id INT NOT NULL,
  CONSTRAINT blog_post_pkey PRIMARY KEY (id),
  CONSTRAINT blog_post_public_id_key UNIQUE (public_id),
  CONSTRAINT blog_post_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth_user (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES auth_user (id) ON DELETE SET NULL,
  CONSTRAINT blog_post_category_id_fkey FOREIGN KEY (category_id) REFERENCES blog_category (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX blog_post_author_id_title_key ON blog_post (author_id, title);
CREATE INDEX post_pub_status_idx ON blog_post (published_at, status);
CREATE INDEX blog_post_title_idx ON blog_post (title);

CREATE TABLE blog_tag (
  id INT NOT NULL AUTO_INCREMENT,
  label VARCHAR(50) NOT NULL,
  CONSTRAINT blog_tag_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_post_tags (
  post_id INT NOT NULL,
  tag_id INT NOT NULL,
  CONSTRAINT blog_post_tags_pkey PRIMARY KEY (post_id, tag_id),
  CONSTRAINT blog_post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES blog_tag (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_profile (
  id INT NOT NULL AUTO_INCREMENT,
  bio LONGTEXT,
  avatar VARCHAR(100),
  user_id INT NOT NULL,
  CONSTRAINT blog_profile_pkey PRIMARY KEY (id),
  CONSTRAINT blog_profile_user_id_key UNIQUE (user_id),
  CONSTRAINT blog_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
