-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE series (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  handle VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  parent_id CHAR(36),
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
);

CREATE TABLE book (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  title VARCHAR(120) NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  grid TEXT, -- an array stored as JSON
  colors TEXT, -- an array stored as JSON
  color VARCHAR(5) NOT NULL DEFAULT 'red',
  price DECIMAL(8, 2) NOT NULL DEFAULT 9.99,
  settings TEXT NOT NULL DEFAULT '{"theme":"dark","tabs":[1,2]}',
  published_on DATE NOT NULL DEFAULT CURRENT_DATE,
  opens_at TIME,
  released_at DATETIME DEFAULT '2020-01-02 03:04:05',
  pages INTEGER NOT NULL DEFAULT 100,
  ratio REAL NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT 1,
  notes TEXT,
  "window" TEXT, -- range stored as text
  extra TEXT, -- hstore stored as JSON
  read_time INTEGER, -- duration in microseconds
  cover BLOB,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  author_id CHAR(36) NOT NULL,
  editor_id CHAR(36),
  series_handle VARCHAR(20),
  CONSTRAINT book_pkey PRIMARY KEY (id),
  CONSTRAINT book_tags_check CHECK (json_valid(tags)),
  CONSTRAINT book_grid_check CHECK (json_valid(grid)),
  CONSTRAINT book_colors_check CHECK (json_valid(colors)),
  CONSTRAINT book_color_check CHECK (color IN ('red', 'green')),
  CONSTRAINT book_settings_check CHECK (json_valid(settings)),
  CONSTRAINT book_extra_check CHECK (json_valid(extra)),
  CONSTRAINT book_author_id_fkey FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT book_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES author (id) ON DELETE SET NULL,
  CONSTRAINT book_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
);
CREATE UNIQUE INDEX book_title_author_id_key ON book (title, author_id);
CREATE INDEX books_published_idx ON book (published_on);

CREATE TABLE author (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INTEGER,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  latest_book_id CHAR(36),
  CONSTRAINT author_pkey PRIMARY KEY (id),
  CONSTRAINT author_handle_key UNIQUE (handle),
  CONSTRAINT author_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES book (id) ON DELETE SET NULL
);

CREATE TABLE audiobook (
  minutes INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  book_ptr_id CHAR(36) NOT NULL,
  CONSTRAINT audiobook_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobook_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES book (id) ON DELETE CASCADE
);

CREATE TABLE "index" (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  "sql" TEXT,
  class TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  "table" CHAR(36),
  CONSTRAINT index_pkey PRIMARY KEY (id),
  CONSTRAINT index_table_fkey FOREIGN KEY ("table") REFERENCES series (id)
);

CREATE TABLE tagged (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
);

CREATE TABLE tagged_book (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  tagged_id CHAR(36) NOT NULL,
  book_id CHAR(36) NOT NULL,
  CONSTRAINT tagged_book_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_book_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_book_book_id_fkey FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX tagged_book_tagged_id_book_id_key ON tagged_book (tagged_id, book_id);
