-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE series (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  handle VARCHAR(20) NOT NULL,
  parent_id INTEGER,
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id) ON DELETE SET NULL
);

CREATE TABLE books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(120) NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  grid TEXT, -- an array stored as JSON
  colors TEXT, -- an array stored as JSON
  color VARCHAR(5) NOT NULL DEFAULT 'red',
  price DECIMAL(8, 2) NOT NULL DEFAULT 9.99,
  settings TEXT NOT NULL DEFAULT '{"theme":"dark","tabs":[1,2]}',
  published_on DATE NOT NULL DEFAULT CURRENT_DATE,
  opens_at TIME,
  released_at DATETIME DEFAULT '2020-01-02 03:04:05',
  pages INTEGER NOT NULL DEFAULT 100,
  ratio REAL NOT NULL DEFAULT 0.5,
  in_print BOOLEAN NOT NULL DEFAULT 1,
  notes TEXT,
  "window" TEXT, -- range stored as text
  extra TEXT, -- hstore stored as JSON
  read_time INTEGER, -- duration in microseconds
  cover BLOB,
  author_id CHAR(36) NOT NULL,
  editor_id CHAR(36),
  series_handle VARCHAR(20),
  CONSTRAINT books_tags_check CHECK (json_valid(tags)),
  CONSTRAINT books_grid_check CHECK (json_valid(grid)),
  CONSTRAINT books_colors_check CHECK (json_valid(colors)),
  CONSTRAINT books_color_check CHECK (color IN ('red', 'green')),
  CONSTRAINT books_settings_check CHECK (json_valid(settings)),
  CONSTRAINT books_extra_check CHECK (json_valid(extra)),
  CONSTRAINT books_author_id_fkey FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT books_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES authors (id) ON DELETE SET NULL,
  CONSTRAINT books_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
);
CREATE UNIQUE INDEX books_title_author_id_key ON books (title, author_id);
CREATE INDEX books_published_idx ON books (published_on);

CREATE TABLE authors (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  handle VARCHAR(30) NOT NULL,
  favourite_book_id INTEGER,
  latest_book_id BIGINT,
  CONSTRAINT authors_pkey PRIMARY KEY (id),
  CONSTRAINT authors_handle_key UNIQUE (handle),
  CONSTRAINT authors_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES books (id) ON DELETE SET NULL
);

CREATE TABLE audiobooks (
  minutes INTEGER NOT NULL,
  book_ptr_id BIGINT NOT NULL,
  CONSTRAINT audiobooks_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobooks_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES books (id) ON DELETE CASCADE
);

CREATE TABLE index_rows (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  "sql" TEXT,
  class TEXT,
  "table" INTEGER,
  CONSTRAINT index_rows_table_fkey FOREIGN KEY ("table") REFERENCES series (id)
);

CREATE TABLE tagged (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE tagged_books (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tagged_id BIGINT NOT NULL,
  book_id BIGINT NOT NULL,
  CONSTRAINT tagged_books_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_books_book_id_fkey FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX tagged_books_tagged_id_book_id_key ON tagged_books (tagged_id, book_id);
