-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE item (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INT NOT NULL DEFAULT 1,
  total_cents INT NOT NULL, -- generated column written as a regular column
  tags JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  grid JSON, -- an array stored as JSON
  kinds JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  attributes JSON NOT NULL DEFAULT ('{}'), -- hstore stored as JSON
  stock_range VARCHAR(255), -- range stored as text
  big_range VARCHAR(255), -- range stored as text
  price_range VARCHAR(255), -- range stored as text
  available VARCHAR(255), -- range stored as text
  valid_during VARCHAR(255), -- range stored as text
  last_ip VARCHAR(45),
  legacy_ip VARCHAR(45),
  shelf_life BIGINT, -- duration in microseconds
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INT NOT NULL DEFAULT 0,
  tiny_count INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  stocked_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  priority INT NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT item_pkey PRIMARY KEY (id),
  CONSTRAINT item_legacy_ip_key UNIQUE (legacy_ip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE counter (
  small_id CHAR(36) NOT NULL DEFAULT (UUID()),
  label VARCHAR(20) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT counter_pkey PRIMARY KEY (small_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE content_type (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT content_type_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  email VARCHAR(254) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE shipment (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  object_id INT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  item_id CHAR(36) NOT NULL,
  other_id CHAR(36) NOT NULL,
  content_type_id CHAR(36) NOT NULL,
  created_by_id CHAR(36) NOT NULL,
  CONSTRAINT shipment_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES content_type (id) ON DELETE CASCADE,
  CONSTRAINT shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE assignment (
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  item_id CHAR(36) NOT NULL,
  account_id CHAR(36) NOT NULL,
  CONSTRAINT assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
