-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE blog_item (
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INT NOT NULL DEFAULT 1,
  total_cents INT NOT NULL, -- generated column written as a regular column
  tags JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  grid JSON, -- an array stored as JSON
  kinds JSON NOT NULL DEFAULT ('[]'), -- an array stored as JSON
  attributes JSON NOT NULL DEFAULT ('{}'), -- hstore stored as JSON
  stock_range VARCHAR(255), -- range stored as text
  big_range VARCHAR(255), -- range stored as text
  price_range VARCHAR(255), -- range stored as text
  available VARCHAR(255), -- range stored as text
  valid_during VARCHAR(255), -- range stored as text
  last_ip VARCHAR(45),
  legacy_ip VARCHAR(45),
  shelf_life BIGINT, -- duration in microseconds
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INT NOT NULL DEFAULT 0,
  tiny_count INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  stocked_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  priority INT NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  CONSTRAINT blog_item_pkey PRIMARY KEY (id),
  CONSTRAINT blog_item_legacy_ip_key UNIQUE (legacy_ip)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_counter (
  small_id INT NOT NULL AUTO_INCREMENT,
  label VARCHAR(20) NOT NULL,
  CONSTRAINT blog_counter_pkey PRIMARY KEY (small_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_contenttype (
  id INT NOT NULL AUTO_INCREMENT,
  CONSTRAINT blog_contenttype_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_account (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT blog_account_pkey PRIMARY KEY (id),
  CONSTRAINT blog_account_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_shipment (
  id INT NOT NULL AUTO_INCREMENT,
  object_id INT NOT NULL,
  item_id INT NOT NULL,
  other_id INT NOT NULL,
  content_type_id INT NOT NULL,
  created_by_id INT NOT NULL,
  CONSTRAINT blog_shipment_pkey PRIMARY KEY (id),
  CONSTRAINT blog_shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES blog_contenttype (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES blog_account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE blog_assignment (
  item_id INT NOT NULL,
  account_id INT NOT NULL,
  CONSTRAINT blog_assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT blog_assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES blog_account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
