-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE customer (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role VARCHAR(8) NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  "rank" BIGINT NOT NULL,
  avatar BLOB NOT NULL,
  settings TEXT NOT NULL,
  CONSTRAINT customer_pkey PRIMARY KEY (id),
  CONSTRAINT customer_email_key UNIQUE (email),
  CONSTRAINT customer_role_check CHECK (role IN ('customer', 'staff', 'admin')),
  CONSTRAINT customer_settings_check CHECK (json_valid(settings))
);
CREATE INDEX customer_deleted_at_idx ON customer (deleted_at);

CREATE TABLE "order" (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  customer_id CHAR(36) NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id),
  CONSTRAINT order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON "order" (customer_id, placed_at DESC);

CREATE TABLE product (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INTEGER NOT NULL DEFAULT 0,
  deleted_at DATETIME,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT product_pkey PRIMARY KEY (sku)
);
CREATE INDEX product_title_idx ON product (title);
CREATE INDEX idx_product_slug ON product (slug);

CREATE TABLE order_item (
  line_no INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  product_sku VARCHAR(40) NOT NULL,
  order_id CHAR(36) NOT NULL,
  CONSTRAINT order_item_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_item_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES product (sku),
  CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (id)
);

CREATE TABLE label (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  name VARCHAR(40) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT label_pkey PRIMARY KEY (id),
  CONSTRAINT label_name_key UNIQUE (name)
);

CREATE TABLE comment (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  body TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE order_label (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  order_id CHAR(36) NOT NULL,
  label_id CHAR(36) NOT NULL,
  CONSTRAINT order_label_pkey PRIMARY KEY (id),
  CONSTRAINT order_label_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE,
  CONSTRAINT order_label_label_id_fkey FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX order_label_order_id_label_id_key ON order_label (order_id, label_id);

CREATE TABLE product_similar (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT product_similar_pkey PRIMARY KEY (id),
  CONSTRAINT product_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES product (sku) ON DELETE CASCADE,
  CONSTRAINT product_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES product (sku) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_similar_from_product_id_to_product_id_key ON product_similar (from_product_id, to_product_id);
