-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE customers (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  deleted_at DATETIME,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role VARCHAR(8) NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  "rank" BIGINT NOT NULL,
  avatar BLOB NOT NULL,
  settings TEXT NOT NULL,
  CONSTRAINT customers_email_key UNIQUE (email),
  CONSTRAINT customers_role_check CHECK (role IN ('customer', 'staff', 'admin')),
  CONSTRAINT customers_settings_check CHECK (json_valid(settings))
);
CREATE INDEX customers_deleted_at_idx ON customers (deleted_at);

CREATE TABLE shop_orders (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  placed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  customer_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON shop_orders (customer_id, placed_at DESC);

CREATE TABLE products (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INTEGER NOT NULL DEFAULT 0,
  deleted_at DATETIME,
  CONSTRAINT products_pkey PRIMARY KEY (sku)
);
CREATE INDEX products_title_idx ON products (title);
CREATE INDEX idx_product_slug ON products (slug);

CREATE TABLE order_items (
  line_no INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  product_sku VARCHAR(40) NOT NULL,
  order_id CHAR(36) NOT NULL,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES products (sku),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id)
);

CREATE TABLE labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(40) NOT NULL,
  CONSTRAINT labels_name_key UNIQUE (name)
);

CREATE TABLE comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  body TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL
);

CREATE TABLE shop_orders_labels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  order_id CHAR(36) NOT NULL,
  label_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_labels_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id) ON DELETE CASCADE,
  CONSTRAINT shop_orders_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX shop_orders_labels_order_id_label_id_key ON shop_orders_labels (order_id, label_id);

CREATE TABLE products_similar (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT products_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES products (sku) ON DELETE CASCADE,
  CONSTRAINT products_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES products (sku) ON DELETE CASCADE
);
CREATE UNIQUE INDEX products_similar_from_product_id_to_product_id_key ON products_similar (from_product_id, to_product_id);
