-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE blog_category (
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(50) NOT NULL,
  parent_id INTEGER,
  CONSTRAINT blog_category_name_key UNIQUE (name),
  CONSTRAINT blog_category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES blog_category (id) ON DELETE SET NULL
);

CREATE TABLE auth_user (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE blog_post (
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  public_id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  status VARCHAR(9) NOT NULL DEFAULT 'draft',
  rating DECIMAL(4, 2),
  view_count INTEGER NOT NULL DEFAULT 0,
  is_featured BOOLEAN NOT NULL DEFAULT 0,
  published_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata TEXT NOT NULL DEFAULT '{}',
  author_id INTEGER NOT NULL,
  editor_id INTEGER,
  category_id INTEGER NOT NULL,
  CONSTRAINT blog_post_public_id_key UNIQUE (public_id),
  CONSTRAINT blog_post_status_check CHECK (status IN ('draft', 'published')),
  CONSTRAINT blog_post_metadata_check CHECK (json_valid(metadata)),
  CONSTRAINT blog_post_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth_user (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES auth_user (id) ON DELETE SET NULL,
  CONSTRAINT blog_post_category_id_fkey FOREIGN KEY (category_id) REFERENCES blog_category (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX blog_post_author_id_title_key ON blog_post (author_id, title);
CREATE INDEX blog_post_title_idx ON blog_post (title);
CREATE INDEX post_pub_status_idx ON blog_post (published_at, status);

CREATE TABLE blog_tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  label VARCHAR(50) NOT NULL
);

CREATE TABLE blog_profile (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bio TEXT,
  avatar VARCHAR(100),
  user_id INTEGER NOT NULL,
  CONSTRAINT blog_profile_user_id_key UNIQUE (user_id),
  CONSTRAINT blog_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);

CREATE TABLE blog_post_tags (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  post_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  CONSTRAINT blog_post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES blog_tag (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX blog_post_tags_post_id_tag_id_key ON blog_post_tags (post_id, tag_id);
