-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE [order] (
  region NVARCHAR(255) NOT NULL,
  number INT NOT NULL,
  total MONEY NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE order_line (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  order_region NVARCHAR(255) NOT NULL,
  order_number INT NOT NULL,
  sku VARCHAR(32) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT order_line_pkey PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY (order_region, order_number) REFERENCES [order] (region, number) ON DELETE CASCADE
);
CREATE INDEX order_line_order_region_order_number_idx ON order_line (order_region, order_number);

CREATE TABLE tenant (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  email NVARCHAR(255) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  tenant_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON UPDATE CASCADE
);

CREATE TABLE profile (
  region NVARCHAR(255) NOT NULL,
  number INT NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  account_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (region, number),
  CONSTRAINT profile_account_id_key UNIQUE (account_id),
  CONSTRAINT profile_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id)
);

CREATE TABLE document (
  id NVARCHAR(255) NOT NULL,
  ulid NVARCHAR(255) NOT NULL,
  short NVARCHAR(255) NOT NULL,
  uid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  token UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  title NVARCHAR(255) NOT NULL,
  body NVARCHAR(MAX) NOT NULL,
  role NVARCHAR(50) NOT NULL DEFAULT N'user',
  small SMALLINT NOT NULL,
  ratio REAL NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  cost MONEY NOT NULL,
  views BIGINT NOT NULL,
  [blob] VARBINARY(MAX) NOT NULL,
  meta NVARCHAR(MAX) NOT NULL,
  created DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated DATETIME2 NOT NULL,
  day DATE NOT NULL,
  at TIME NOT NULL,
  ip VARCHAR(45) NOT NULL,
  internal INT NOT NULL,
  legacy_name NVARCHAR(255) NOT NULL,
  CONSTRAINT document_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid),
  CONSTRAINT document_role_check CHECK (role IN (N'admin', N'user')),
  CONSTRAINT document_meta_check CHECK (ISJSON(meta) = 1)
);
CREATE INDEX ix_document_title ON document (title DESC, created);
CREATE UNIQUE INDEX uq_document_title_day ON document (title, day);

CREATE TABLE scratch (
  id INT NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT scratch_pkey PRIMARY KEY (id)
);

-- View document_summary: the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title, created_at, updated_at
-- CREATE VIEW document_summary AS SELECT ... ;
