-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE [Order] (
  region NVARCHAR(255) NOT NULL,
  number INT NOT NULL,
  total MONEY NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE [OrderLine] (
  id INT IDENTITY(1,1) NOT NULL,
  [orderRegion] NVARCHAR(255) NOT NULL,
  [orderNumber] INT NOT NULL,
  sku VARCHAR(32) NOT NULL,
  CONSTRAINT [OrderLine_pkey] PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY ([orderRegion], [orderNumber]) REFERENCES [Order] (region, number) ON DELETE CASCADE
);
CREATE INDEX [OrderLine_orderRegion_orderNumber_idx] ON [OrderLine] ([orderRegion], [orderNumber]);

CREATE TABLE [Tenant] (
  id INT IDENTITY(1,1) NOT NULL,
  CONSTRAINT [Tenant_pkey] PRIMARY KEY (id)
);

CREATE TABLE [Account] (
  id INT IDENTITY(1,1) NOT NULL,
  email NVARCHAR(255) NOT NULL,
  [tenantId] INT NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY ([tenantId]) REFERENCES [Tenant] (id) ON UPDATE CASCADE
);

CREATE TABLE [Profile] (
  region NVARCHAR(255) NOT NULL,
  number INT NOT NULL,
  [accountId] INT NOT NULL,
  CONSTRAINT [Profile_pkey] PRIMARY KEY (region, number),
  CONSTRAINT [Profile_accountId_key] UNIQUE ([accountId]),
  CONSTRAINT [Profile_accountId_fkey] FOREIGN KEY ([accountId]) REFERENCES [Account] (id)
);

CREATE TABLE documents (
  id NVARCHAR(255) NOT NULL,
  ulid NVARCHAR(255) NOT NULL,
  short NVARCHAR(255) NOT NULL,
  uid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  token UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  title NVARCHAR(255) NOT NULL,
  body NVARCHAR(MAX) NOT NULL,
  role NVARCHAR(50) NOT NULL DEFAULT N'user',
  small SMALLINT NOT NULL,
  ratio REAL NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  cost MONEY NOT NULL,
  views BIGINT NOT NULL,
  [blob] VARBINARY(MAX) NOT NULL,
  meta NVARCHAR(MAX) NOT NULL,
  created DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated DATETIME2 NOT NULL,
  day DATE NOT NULL,
  at TIME NOT NULL,
  ip VARCHAR(45) NOT NULL,
  internal INT NOT NULL,
  legacy_name NVARCHAR(255) NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid),
  CONSTRAINT documents_role_check CHECK (role IN (N'admin', N'user')),
  CONSTRAINT documents_meta_check CHECK (ISJSON(meta) = 1)
);
CREATE INDEX ix_document_title ON documents (title DESC, created);
CREATE UNIQUE INDEX uq_document_title_day ON documents (title, day);

CREATE TABLE [Scratch] (
  id INT NOT NULL,
  CONSTRAINT [Scratch_pkey] PRIMARY KEY (id)
);

-- View [DocumentSummary]: the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title
-- CREATE VIEW [DocumentSummary] AS SELECT ... ;
