-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE [others] (
  id INT IDENTITY(1,1) NOT NULL,
  CONSTRAINT others_pkey PRIMARY KEY (id)
);

CREATE TABLE weird (
  id INT IDENTITY(1,1) NOT NULL,
  [a;b] NVARCHAR(255) NOT NULL DEFAULT N'x;y',
  quote NVARCHAR(255) NOT NULL DEFAULT N'say "hi"',
  tick NVARCHAR(255) NOT NULL DEFAULT N'a`b',
  self_id INT NULL,
  other_id INT NOT NULL,
  CONSTRAINT weird_pkey PRIMARY KEY (id),
  CONSTRAINT weird_self_id_fkey FOREIGN KEY (self_id) REFERENCES weird (id),
  CONSTRAINT weird_other_id_fkey FOREIGN KEY (other_id) REFERENCES [others] (id) ON DELETE CASCADE
);
