-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE "order" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  total NUMERIC NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE order_line (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  order_region TEXT NOT NULL,
  order_number INTEGER NOT NULL,
  sku VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT order_line_pkey PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY (order_region, order_number) REFERENCES "order" (region, number) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX order_line_order_region_order_number_idx ON order_line (order_region, order_number);

CREATE TABLE tenant (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT tenant_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  email TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  tenant_id CHAR(36) NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON UPDATE CASCADE
);

CREATE TABLE profile (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  account_id CHAR(36) NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (region, number),
  CONSTRAINT profile_account_id_key UNIQUE (account_id),
  CONSTRAINT profile_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT
);

CREATE TABLE document (
  id TEXT NOT NULL,
  ulid TEXT NOT NULL,
  short TEXT NOT NULL,
  uid CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  token CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  role VARCHAR(5) NOT NULL DEFAULT 'user',
  small INTEGER NOT NULL,
  ratio REAL NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  cost NUMERIC NOT NULL,
  views BIGINT NOT NULL,
  "blob" BLOB NOT NULL,
  meta TEXT NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL,
  day DATE NOT NULL,
  at TIME NOT NULL,
  ip TEXT NOT NULL,
  internal INTEGER NOT NULL,
  legacy_name TEXT NOT NULL,
  CONSTRAINT document_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid),
  CONSTRAINT document_role_check CHECK (role IN ('admin', 'user')),
  CONSTRAINT document_meta_check CHECK (json_valid(meta))
);
CREATE INDEX ix_document_title ON document (title DESC, created);
CREATE INDEX document_meta_idx ON document (meta);
CREATE UNIQUE INDEX uq_document_title_day ON document (title, day);

CREATE TABLE scratch (
  id INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT scratch_pkey PRIMARY KEY (id)
);

-- View document_summary: the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title, created_at, updated_at
-- CREATE VIEW document_summary AS SELECT ... ;
