-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE "Order" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  total NUMERIC NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
);

CREATE TABLE "OrderLine" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  "orderRegion" TEXT NOT NULL,
  "orderNumber" INTEGER NOT NULL,
  sku VARCHAR(32) NOT NULL,
  CONSTRAINT fk_line_order FOREIGN KEY ("orderRegion", "orderNumber") REFERENCES "Order" (region, number) ON DELETE CASCADE ON UPDATE RESTRICT
);
CREATE INDEX "OrderLine_orderRegion_orderNumber_idx" ON "OrderLine" ("orderRegion", "orderNumber");

CREATE TABLE "Tenant" (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE "Account" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL,
  "tenantId" INTEGER NOT NULL,
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY ("tenantId") REFERENCES "Tenant" (id) ON UPDATE CASCADE
);

CREATE TABLE "Profile" (
  region TEXT NOT NULL,
  number INTEGER NOT NULL,
  "accountId" INTEGER NOT NULL,
  CONSTRAINT "Profile_pkey" PRIMARY KEY (region, number),
  CONSTRAINT "Profile_accountId_key" UNIQUE ("accountId"),
  CONSTRAINT "Profile_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "Account" (id) ON DELETE RESTRICT
);

CREATE TABLE documents (
  id TEXT NOT NULL,
  ulid TEXT NOT NULL,
  short TEXT NOT NULL,
  uid CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  token CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  role VARCHAR(5) NOT NULL DEFAULT 'user',
  small INTEGER NOT NULL,
  ratio REAL NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  cost NUMERIC NOT NULL,
  views BIGINT NOT NULL,
  "blob" BLOB NOT NULL,
  meta TEXT NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME NOT NULL,
  day DATE NOT NULL,
  at TIME NOT NULL,
  ip TEXT NOT NULL,
  internal INTEGER NOT NULL,
  legacy_name TEXT NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid),
  CONSTRAINT documents_role_check CHECK (role IN ('admin', 'user')),
  CONSTRAINT documents_meta_check CHECK (json_valid(meta))
);
CREATE INDEX ix_document_title ON documents (title DESC, created);
CREATE INDEX documents_meta_idx ON documents (meta);
CREATE UNIQUE INDEX uq_document_title_day ON documents (title, day);

CREATE TABLE "Scratch" (
  id INTEGER NOT NULL,
  CONSTRAINT "Scratch_pkey" PRIMARY KEY (id)
);

-- View "DocumentSummary": the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title
-- CREATE VIEW "DocumentSummary" AS SELECT ... ;
