-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE series (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  handle NVARCHAR(20) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  parent_id UNIQUEIDENTIFIER NULL,
  CONSTRAINT series_pkey PRIMARY KEY (id),
  CONSTRAINT series_handle_uq UNIQUE (handle),
  CONSTRAINT series_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES series (id)
);

CREATE TABLE book (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  title NVARCHAR(120) NOT NULL,
  tags NVARCHAR(MAX) NOT NULL DEFAULT N'[]', -- an array stored as JSON
  grid NVARCHAR(MAX) NULL, -- an array stored as JSON
  colors NVARCHAR(MAX) NULL, -- an array stored as JSON
  color NVARCHAR(50) NOT NULL DEFAULT N'red',
  price DECIMAL(8, 2) NOT NULL DEFAULT 9.99,
  settings NVARCHAR(MAX) NOT NULL DEFAULT N'{"theme":"dark","tabs":[1,2]}',
  published_on DATE NOT NULL DEFAULT (CAST(SYSUTCDATETIME() AS DATE)),
  opens_at TIME NULL,
  released_at DATETIME2 NULL DEFAULT '2020-01-02T03:04:05.000',
  pages INT NOT NULL DEFAULT 100,
  ratio FLOAT NOT NULL DEFAULT 0.5,
  in_print BIT NOT NULL DEFAULT 1,
  notes NVARCHAR(MAX) NULL,
  [window] NVARCHAR(255) NULL, -- range stored as text
  extra NVARCHAR(MAX) NULL, -- hstore stored as JSON
  read_time BIGINT NULL, -- duration in microseconds
  cover VARBINARY(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  author_id UNIQUEIDENTIFIER NOT NULL,
  editor_id UNIQUEIDENTIFIER NULL,
  series_handle NVARCHAR(20) NULL,
  CONSTRAINT book_pkey PRIMARY KEY (id),
  CONSTRAINT book_tags_check CHECK (ISJSON(tags) = 1),
  CONSTRAINT book_grid_check CHECK (ISJSON(grid) = 1),
  CONSTRAINT book_colors_check CHECK (ISJSON(colors) = 1),
  CONSTRAINT book_color_check CHECK (color IN (N'red', N'green')),
  CONSTRAINT book_settings_check CHECK (ISJSON(settings) = 1),
  CONSTRAINT book_extra_check CHECK (ISJSON(extra) = 1),
  CONSTRAINT book_series_handle_fkey FOREIGN KEY (series_handle) REFERENCES series (handle) ON DELETE SET NULL
);
CREATE UNIQUE INDEX book_title_author_id_key ON book (title, author_id);
CREATE INDEX books_published_idx ON book (published_on);

CREATE TABLE author (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  handle NVARCHAR(30) NOT NULL,
  favourite_book_id INT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  latest_book_id UNIQUEIDENTIFIER NULL,
  CONSTRAINT author_pkey PRIMARY KEY (id),
  CONSTRAINT author_handle_key UNIQUE (handle),
  CONSTRAINT author_latest_book_id_fkey FOREIGN KEY (latest_book_id) REFERENCES book (id)
);

CREATE TABLE audiobook (
  minutes INT NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  book_ptr_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT audiobook_pkey PRIMARY KEY (book_ptr_id),
  CONSTRAINT audiobook_book_ptr_id_fkey FOREIGN KEY (book_ptr_id) REFERENCES book (id) ON DELETE CASCADE
);

CREATE TABLE [index] (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  [sql] NVARCHAR(255) NULL,
  class NVARCHAR(255) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  [table] UNIQUEIDENTIFIER NULL,
  CONSTRAINT index_pkey PRIMARY KEY (id),
  CONSTRAINT index_table_fkey FOREIGN KEY ([table]) REFERENCES series (id)
);

CREATE TABLE tagged (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT tagged_pkey PRIMARY KEY (id)
);

CREATE TABLE tagged_book (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  tagged_id UNIQUEIDENTIFIER NOT NULL,
  book_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT tagged_book_pkey PRIMARY KEY (id),
  CONSTRAINT tagged_book_tagged_id_fkey FOREIGN KEY (tagged_id) REFERENCES tagged (id) ON DELETE CASCADE,
  CONSTRAINT tagged_book_book_id_fkey FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX tagged_book_tagged_id_book_id_key ON tagged_book (tagged_id, book_id);

-- These foreign keys close a reference cycle, so they are added once every table exists.

ALTER TABLE book ADD CONSTRAINT book_author_id_fkey FOREIGN KEY (author_id) REFERENCES author (id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE book ADD CONSTRAINT book_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES author (id);
