# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Column,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    Interval,
    LargeBinary,
    Numeric,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    Time,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.dialects.postgresql import INET
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


class Role(enum.Enum):
    owner = "owner"
    member = "member"


groups_friends = Table(
    "groups_friends",
    Base.metadata,
    Column(
        "from_group_id",
        ForeignKey("groups.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "to_group_id",
        ForeignKey("groups.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)


class Account(Base):
    __tablename__ = "accounts"
    __table_args__ = (
        Index("ix_accounts_deleted_at", "deleted_at"),
        Index("ix_accounts_email_status", "email", "status"),
    )

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        default=func.now(),
        onupdate=func.now(),
    )
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True),
    )
    email: Mapped[str] = mapped_column(String(255), unique=True)
    balance: Mapped[decimal.Decimal] = mapped_column(Numeric(10, 2))
    score: Mapped[Optional[float]] = mapped_column(Float)
    avatar: Mapped[Optional[bytes]] = mapped_column(LargeBinary)
    payload: Mapped[Optional[Any]] = mapped_column(JSON(none_as_null=True))
    labels: Mapped[list[str]] = mapped_column(
        ARRAY(String).with_variant(JSON(), "sqlite"),
    )
    ttl: Mapped[Optional[datetime.timedelta]] = mapped_column(Interval)
    ip: Mapped[Optional[str]] = mapped_column(
        INET().with_variant(String(45), "sqlite"),
    )
    homepage_url: Mapped[Optional[str]] = mapped_column(String)
    born: Mapped[Optional[datetime.date]] = mapped_column(Date)
    alarm: Mapped[Optional[datetime.time]] = mapped_column(Time)
    status: Mapped[Status] = mapped_column(
        Enum(
            Status,
            name="Status",
            values_callable=lambda members: [member.value for member in members],
        ),
        server_default="draft",
    )
    note: Mapped[str] = mapped_column(Text, server_default="it's; fine")

    sessions: Mapped[list["Session"]] = relationship(
        back_populates="account",
        passive_deletes=True,
    )
    memberships: Mapped[list["Membership"]] = relationship(
        back_populates="account",
        passive_deletes=True,
    )
    profile: Mapped[Optional["Profile"]] = relationship(
        back_populates="owner",
        passive_deletes=True,
    )
    legacy_orders: Mapped[list["legacy_order"]] = relationship(back_populates="owner")


class Session(Base):
    __tablename__ = "sessions"
    __table_args__ = (
        UniqueConstraint(
            "account_id",
            "opened_at",
            name="uq_sessions_account_id_opened_at",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    token: Mapped[Optional[uuid.UUID]] = mapped_column(Uuid, default=uuid.uuid4)
    deleted_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True),
    )
    opened_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
    )
    account_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("accounts.id", ondelete="SET NULL", onupdate="CASCADE"),
    )

    account: Mapped[Optional["Account"]] = relationship(back_populates="sessions")


class Group(Base):
    __tablename__ = "groups"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(40))

    friends: Mapped[list["Group"]] = relationship(
        back_populates="friend_of",
        secondary=groups_friends,
        primaryjoin=lambda: Group.id == groups_friends.c.from_group_id,
        secondaryjoin=lambda: Group.id == groups_friends.c.to_group_id,
    )
    friend_of: Mapped[list["Group"]] = relationship(
        back_populates="friends",
        secondary=groups_friends,
        primaryjoin=lambda: Group.id == groups_friends.c.to_group_id,
        secondaryjoin=lambda: Group.id == groups_friends.c.from_group_id,
    )
    memberships: Mapped[list["Membership"]] = relationship(back_populates="group")


class Membership(Base):
    __tablename__ = "memberships"
    __table_args__ = (
        PrimaryKeyConstraint("account_id", "group_id"),
    )

    role: Mapped[Role] = mapped_column(
        Enum(
            Role,
            name="Role",
            values_callable=lambda members: [member.value for member in members],
        ),
    )
    account_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("accounts.id", ondelete="CASCADE"),
    )
    group_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("groups.id", ondelete="RESTRICT"),
    )

    account: Mapped["Account"] = relationship(back_populates="memberships")
    group: Mapped["Group"] = relationship(back_populates="memberships")


class Profile(Base):
    __tablename__ = "profiles"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    bio: Mapped[Optional[str]] = mapped_column(Text)
    owner_account_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("accounts.id", ondelete="CASCADE"),
        unique=True,
    )

    owner: Mapped["Account"] = relationship(back_populates="profile")


class legacy_order(Base):
    __tablename__ = "LEGACY_ORDER"

    order_no: Mapped[int] = mapped_column(
        "OrderNo",
        Integer,
        primary_key=True,
        autoincrement=False,
    )
    type: Mapped[str] = mapped_column("kind", String)
    http_code: Mapped[int] = mapped_column(Integer)
    first_name: Mapped[Optional[str]] = mapped_column("first name", String)
    acct: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("accounts.id", ondelete="NO ACTION"),
    )

    owner: Mapped[Optional["Account"]] = relationship(back_populates="legacy_orders")
