# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    PrimaryKeyConstraint,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import INET
from sqlmodel import Field, Relationship, SQLModel


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


class Role(enum.Enum):
    owner = "owner"
    member = "member"


groups_friends = Table(
    "groups_friends",
    SQLModel.metadata,
    Column(
        "from_group_id",
        ForeignKey("groups.id", ondelete="CASCADE"),
        primary_key=True,
    ),
    Column(
        "to_group_id",
        ForeignKey("groups.id", ondelete="CASCADE"),
        primary_key=True,
    ),
)


class Account(SQLModel, table=True):
    __tablename__ = "accounts"
    __table_args__ = (
        Index("ix_accounts_deleted_at", "deleted_at"),
        Index("ix_accounts_email_status", "email", "status"),
    )

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )
    created_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    updated_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"default": func.now(), "onupdate": func.now()},
    )
    deleted_at: Optional[datetime.datetime] = Field(
        default=None,
        sa_type=DateTime(timezone=True),
    )
    email: str = Field(unique=True, max_length=255)
    balance: decimal.Decimal = Field(max_digits=10, decimal_places=2)
    score: Optional[float] = Field(default=None)
    avatar: Optional[bytes] = Field(default=None)
    payload: Optional[Any] = Field(default=None, sa_type=JSON(none_as_null=True))
    labels: list[str] = Field(sa_type=ARRAY(String).with_variant(JSON(), "sqlite"))
    ttl: Optional[datetime.timedelta] = Field(default=None)
    ip: Optional[str] = Field(
        default=None,
        sa_type=INET().with_variant(String(45), "sqlite"),
    )
    homepage_url: Optional[str] = Field(default=None)
    born: Optional[datetime.date] = Field(default=None)
    alarm: Optional[datetime.time] = Field(default=None)
    status: Status = Field(
        default=Status.DRAFT,
        sa_type=Enum(
            Status,
            name="Status",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"server_default": "draft"},
    )
    note: str = Field(
        default="it's; fine",
        sa_type=Text,
        sa_column_kwargs={"server_default": "it's; fine"},
    )

    sessions: list["Session"] = Relationship(
        back_populates="account",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    memberships: list["Membership"] = Relationship(
        back_populates="account",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    profile: Optional["Profile"] = Relationship(
        back_populates="owner",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    legacy_orders: list["legacy_order"] = Relationship(back_populates="owner")


class Session(SQLModel, table=True):
    __tablename__ = "sessions"
    __table_args__ = (
        UniqueConstraint(
            "account_id",
            "opened_at",
            name="uq_sessions_account_id_opened_at",
        ),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    token: Optional[uuid.UUID] = Field(default_factory=uuid.uuid4, nullable=True)
    deleted_at: Optional[datetime.datetime] = Field(
        default=None,
        sa_type=DateTime(timezone=True),
    )
    opened_at: Optional[datetime.datetime] = Field(
        default=None,
        nullable=False,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": func.now()},
    )
    account_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            "account_id",
            BigInteger,
            ForeignKey("accounts.id", ondelete="SET NULL", onupdate="CASCADE"),
            nullable=True,
        ),
    )

    account: Optional["Account"] = Relationship(back_populates="sessions")


class Group(SQLModel, table=True):
    __tablename__ = "groups"

    id: Optional[int] = Field(default=None, primary_key=True)
    name: str = Field(max_length=40)

    friends: list["Group"] = Relationship(
        back_populates="friend_of",
        sa_relationship_kwargs={
            "secondary": groups_friends,
            "primaryjoin": lambda: Group.id == groups_friends.c.from_group_id,
            "secondaryjoin": lambda: Group.id == groups_friends.c.to_group_id,
        },
    )
    friend_of: list["Group"] = Relationship(
        back_populates="friends",
        sa_relationship_kwargs={
            "secondary": groups_friends,
            "primaryjoin": lambda: Group.id == groups_friends.c.to_group_id,
            "secondaryjoin": lambda: Group.id == groups_friends.c.from_group_id,
        },
    )
    memberships: list["Membership"] = Relationship(back_populates="group")


class Membership(SQLModel, table=True):
    __tablename__ = "memberships"
    __table_args__ = (
        PrimaryKeyConstraint("account_id", "group_id"),
    )

    role: Role = Field(
        sa_type=Enum(
            Role,
            name="Role",
            values_callable=lambda members: [member.value for member in members],
        ),
    )
    account_id: int = Field(
        foreign_key="accounts.id",
        ondelete="CASCADE",
        sa_type=BigInteger,
    )
    group_id: int = Field(foreign_key="groups.id", ondelete="RESTRICT")

    account: "Account" = Relationship(back_populates="memberships")
    group: "Group" = Relationship(back_populates="memberships")


class Profile(SQLModel, table=True):
    __tablename__ = "profiles"

    id: Optional[int] = Field(default=None, primary_key=True)
    bio: Optional[str] = Field(default=None, sa_type=Text)
    owner_account_id: int = Field(
        foreign_key="accounts.id",
        ondelete="CASCADE",
        unique=True,
        sa_type=BigInteger,
    )

    owner: "Account" = Relationship(back_populates="profile")


class legacy_order(SQLModel, table=True):
    __tablename__ = "LEGACY_ORDER"

    order_no: int = Field(
        primary_key=True,
        sa_column_kwargs={"name": "OrderNo", "autoincrement": False},
    )
    type: str = Field(sa_column_kwargs={"name": "kind"})
    http_code: int
    first_name: Optional[str] = Field(
        default=None,
        sa_column_kwargs={"name": "first name"},
    )
    acct: Optional[int] = Field(
        default=None,
        sa_column=Column(
            "acct",
            BigInteger,
            ForeignKey("accounts.id", ondelete="NO ACTION"),
            nullable=True,
        ),
    )

    owner: Optional["Account"] = Relationship(back_populates="legacy_orders")
