-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE blog_category (
  id INT IDENTITY(1,1) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  name NVARCHAR(100) NOT NULL,
  slug NVARCHAR(50) NOT NULL,
  parent_id INT NULL,
  CONSTRAINT blog_category_pkey PRIMARY KEY (id),
  CONSTRAINT blog_category_name_key UNIQUE (name),
  CONSTRAINT blog_category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES blog_category (id)
);

CREATE TABLE auth_user (
  id INT IDENTITY(1,1) NOT NULL,
  CONSTRAINT auth_user_pkey PRIMARY KEY (id)
);

CREATE TABLE blog_post (
  id INT IDENTITY(1,1) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  public_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  title NVARCHAR(200) NOT NULL,
  body NVARCHAR(MAX) NOT NULL,
  status NVARCHAR(50) NOT NULL DEFAULT N'draft',
  rating DECIMAL(4, 2) NULL,
  view_count INT NOT NULL DEFAULT 0,
  is_featured BIT NOT NULL DEFAULT 0,
  published_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  metadata NVARCHAR(MAX) NOT NULL DEFAULT N'{}',
  author_id INT NOT NULL,
  editor_id INT NULL,
  category_id INT NOT NULL,
  CONSTRAINT blog_post_pkey PRIMARY KEY (id),
  CONSTRAINT blog_post_public_id_key UNIQUE (public_id),
  CONSTRAINT blog_post_status_check CHECK (status IN (N'draft', N'published')),
  CONSTRAINT blog_post_metadata_check CHECK (ISJSON(metadata) = 1),
  CONSTRAINT blog_post_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth_user (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES auth_user (id),
  CONSTRAINT blog_post_category_id_fkey FOREIGN KEY (category_id) REFERENCES blog_category (id)
);
CREATE INDEX blog_post_title_idx ON blog_post (title);
CREATE UNIQUE INDEX blog_post_author_id_title_key ON blog_post (author_id, title);
CREATE INDEX post_pub_status_idx ON blog_post (published_at, status);

CREATE TABLE blog_tag (
  id INT IDENTITY(1,1) NOT NULL,
  label NVARCHAR(50) NOT NULL,
  CONSTRAINT blog_tag_pkey PRIMARY KEY (id)
);

CREATE TABLE blog_profile (
  id INT IDENTITY(1,1) NOT NULL,
  bio NVARCHAR(MAX) NULL,
  avatar NVARCHAR(100) NULL,
  user_id INT NOT NULL,
  CONSTRAINT blog_profile_pkey PRIMARY KEY (id),
  CONSTRAINT blog_profile_user_id_key UNIQUE (user_id),
  CONSTRAINT blog_profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth_user (id) ON DELETE CASCADE
);

CREATE TABLE blog_post_tags (
  id INT IDENTITY(1,1) NOT NULL,
  post_id INT NOT NULL,
  tag_id INT NOT NULL,
  CONSTRAINT blog_post_tags_pkey PRIMARY KEY (id),
  CONSTRAINT blog_post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE,
  CONSTRAINT blog_post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES blog_tag (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX blog_post_tags_post_id_tag_id_key ON blog_post_tags (post_id, tag_id);
