-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE role AS ENUM ('customer', 'staff', 'admin');

CREATE TABLE customer (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role role NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "rank" BIGINT NOT NULL,
  avatar BYTEA NOT NULL,
  settings JSONB NOT NULL,
  CONSTRAINT customer_pkey PRIMARY KEY (id),
  CONSTRAINT customer_email_key UNIQUE (email)
);
CREATE INDEX customer_deleted_at_idx ON customer (deleted_at);

CREATE TABLE "order" (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  placed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  modified_at BIGINT NOT NULL,
  total NUMERIC(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  customer_id UUID NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id),
  CONSTRAINT order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON "order" (customer_id, placed_at DESC);

CREATE TABLE product (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  in_stock INTEGER NOT NULL DEFAULT 0,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT product_pkey PRIMARY KEY (sku)
);
CREATE INDEX product_title_idx ON product USING gin (to_tsvector('simple', coalesce(title::text, '')));
CREATE INDEX idx_product_slug ON product USING hash (slug);

CREATE TABLE order_item (
  line_no INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  product_sku VARCHAR(40) NOT NULL,
  order_id UUID NOT NULL,
  CONSTRAINT order_item_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_item_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES product (sku),
  CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (id)
);

CREATE TABLE label (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  name VARCHAR(40) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT label_pkey PRIMARY KEY (id),
  CONSTRAINT label_name_key UNIQUE (name)
);

CREATE TABLE comment (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  body TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE order_label (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL,
  label_id UUID NOT NULL,
  CONSTRAINT order_label_pkey PRIMARY KEY (id),
  CONSTRAINT order_label_order_id_fkey FOREIGN KEY (order_id) REFERENCES "order" (id) ON DELETE CASCADE,
  CONSTRAINT order_label_label_id_fkey FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX order_label_order_id_label_id_key ON order_label (order_id, label_id);

CREATE TABLE product_similar (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT product_similar_pkey PRIMARY KEY (id),
  CONSTRAINT product_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES product (sku) ON DELETE CASCADE,
  CONSTRAINT product_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES product (sku) ON DELETE CASCADE
);
CREATE UNIQUE INDEX product_similar_from_product_id_to_product_id_key ON product_similar (from_product_id, to_product_id);
