-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE "Role" AS ENUM ('customer', 'staff', 'admin');

CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(100),
  role "Role" NOT NULL DEFAULT 'customer',
  billing_street VARCHAR(120) NOT NULL,
  billing_city VARCHAR(60) NOT NULL,
  billing_zip VARCHAR(12),
  shipping_street VARCHAR(120) NOT NULL,
  shipping_city VARCHAR(60) NOT NULL,
  shipping_zip VARCHAR(12),
  balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
  "rank" BIGINT NOT NULL,
  avatar BYTEA NOT NULL,
  settings JSONB NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_email_key UNIQUE (email)
);
CREATE INDEX customers_deleted_at_idx ON customers (deleted_at);

CREATE TABLE shop_orders (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  placed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  modified_at BIGINT NOT NULL,
  total NUMERIC(12, 2) NOT NULL,
  note VARCHAR(500) NOT NULL,
  customer_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON shop_orders (customer_id, placed_at DESC);

CREATE TABLE products (
  sku VARCHAR(40) NOT NULL,
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  price NUMERIC(10, 2) NOT NULL,
  in_stock INTEGER NOT NULL DEFAULT 0,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT products_pkey PRIMARY KEY (sku)
);
CREATE INDEX products_title_idx ON products USING gin (to_tsvector('simple', coalesce(title::text, '')));
CREATE INDEX idx_product_slug ON products USING hash (slug);

CREATE TABLE order_items (
  line_no INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  product_sku VARCHAR(40) NOT NULL,
  order_id UUID NOT NULL,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES products (sku),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id)
);

CREATE TABLE labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(40) NOT NULL,
  CONSTRAINT labels_pkey PRIMARY KEY (id),
  CONSTRAINT labels_name_key UNIQUE (name)
);

CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  body TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type VARCHAR(30) NOT NULL,
  CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE shop_orders_labels (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  order_id UUID NOT NULL,
  label_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_labels_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_labels_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id) ON DELETE CASCADE,
  CONSTRAINT shop_orders_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX shop_orders_labels_order_id_label_id_key ON shop_orders_labels (order_id, label_id);

CREATE TABLE products_similar (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  from_product_id VARCHAR(40) NOT NULL,
  to_product_id VARCHAR(40) NOT NULL,
  CONSTRAINT products_similar_pkey PRIMARY KEY (id),
  CONSTRAINT products_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES products (sku) ON DELETE CASCADE,
  CONSTRAINT products_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES products (sku) ON DELETE CASCADE
);
CREATE UNIQUE INDEX products_similar_from_product_id_to_product_id_key ON products_similar (from_product_id, to_product_id);
