-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE [user] (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT user_pkey PRIMARY KEY (id)
);

CREATE TABLE category (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  name NVARCHAR(100) NOT NULL,
  slug NVARCHAR(50) NOT NULL,
  parent_id UNIQUEIDENTIFIER NULL,
  CONSTRAINT category_pkey PRIMARY KEY (id),
  CONSTRAINT category_name_key UNIQUE (name),
  CONSTRAINT category_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES category (id)
);

CREATE TABLE post (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  public_id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  title NVARCHAR(200) NOT NULL,
  body NVARCHAR(MAX) NOT NULL,
  status NVARCHAR(50) NOT NULL DEFAULT N'draft',
  rating DECIMAL(4, 2) NULL,
  view_count INT NOT NULL DEFAULT 0,
  is_featured BIT NOT NULL DEFAULT 0,
  published_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  metadata NVARCHAR(MAX) NOT NULL DEFAULT N'{}',
  author_id UNIQUEIDENTIFIER NOT NULL,
  editor_id UNIQUEIDENTIFIER NULL,
  category_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT post_pkey PRIMARY KEY (id),
  CONSTRAINT post_public_id_key UNIQUE (public_id),
  CONSTRAINT post_status_check CHECK (status IN (N'draft', N'published')),
  CONSTRAINT post_metadata_check CHECK (ISJSON(metadata) = 1),
  CONSTRAINT post_author_id_fkey FOREIGN KEY (author_id) REFERENCES [user] (id) ON DELETE CASCADE,
  CONSTRAINT post_editor_id_fkey FOREIGN KEY (editor_id) REFERENCES [user] (id),
  CONSTRAINT post_category_id_fkey FOREIGN KEY (category_id) REFERENCES category (id)
);
CREATE UNIQUE INDEX post_author_id_title_key ON post (author_id, title);
CREATE INDEX post_pub_status_idx ON post (published_at, status);
CREATE INDEX post_title_idx ON post (title);

CREATE TABLE tag (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  label NVARCHAR(50) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT tag_pkey PRIMARY KEY (id)
);

CREATE TABLE post_tag (
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  post_id UNIQUEIDENTIFIER NOT NULL,
  tag_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT post_tag_pkey PRIMARY KEY (post_id, tag_id),
  CONSTRAINT post_tag_post_id_fkey FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
  CONSTRAINT post_tag_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);

CREATE TABLE profile (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  bio NVARCHAR(MAX) NULL,
  avatar NVARCHAR(100) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  user_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_user_id_key UNIQUE (user_id),
  CONSTRAINT profile_user_id_fkey FOREIGN KEY (user_id) REFERENCES [user] (id) ON DELETE CASCADE
);
