-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  email VARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score DOUBLE,
  avatar LONGBLOB,
  payload JSON,
  labels JSON NOT NULL, -- an array stored as JSON
  ttl BIGINT, -- duration in microseconds
  ip VARCHAR(45),
  homepage_url VARCHAR(255),
  born DATE,
  alarm TIME(6),
  status ENUM('draft', 'live') NOT NULL DEFAULT 'draft',
  note LONGTEXT NOT NULL DEFAULT ('it''s; fine'),
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX account_deleted_at_idx ON account (deleted_at);
CREATE INDEX account_email_status_idx ON account (email, status);

CREATE TABLE session (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  token CHAR(36) DEFAULT (UUID()),
  deleted_at DATETIME(6),
  opened_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  account_id CHAR(36),
  CONSTRAINT session_pkey PRIMARY KEY (id),
  CONSTRAINT session_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX session_account_id_opened_at_key ON session (account_id, opened_at);

CREATE TABLE `group` (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  name VARCHAR(40) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT group_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE membership (
  role ENUM('owner', 'member') NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  account_id CHAR(36) NOT NULL,
  group_id CHAR(36) NOT NULL,
  CONSTRAINT membership_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT membership_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE,
  CONSTRAINT membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE profile (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  bio LONGTEXT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  owner_account_id CHAR(36) NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profile_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES account (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE legacy_order (
  order_no INT NOT NULL,
  kind VARCHAR(255) NOT NULL,
  http_code INT NOT NULL,
  first_name VARCHAR(255),
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  acct CHAR(36),
  CONSTRAINT legacy_order_pkey PRIMARY KEY (order_no),
  CONSTRAINT legacy_order_acct_fkey FOREIGN KEY (acct) REFERENCES account (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE group_friend (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  from_group_id CHAR(36) NOT NULL,
  to_group_id CHAR(36) NOT NULL,
  CONSTRAINT group_friend_pkey PRIMARY KEY (id),
  CONSTRAINT group_friend_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES `group` (id) ON DELETE CASCADE,
  CONSTRAINT group_friend_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES `group` (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX group_friend_from_group_id_to_group_id_key ON group_friend (from_group_id, to_group_id);
