-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE accounts (
  id BIGINT NOT NULL AUTO_INCREMENT,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at DATETIME(6),
  email VARCHAR(255) NOT NULL,
  balance DECIMAL(10, 2) NOT NULL,
  score DOUBLE,
  avatar LONGBLOB,
  payload JSON,
  labels JSON NOT NULL, -- an array stored as JSON
  ttl BIGINT, -- duration in microseconds
  ip VARCHAR(45),
  homepage_url VARCHAR(255),
  born DATE,
  alarm TIME(6),
  status ENUM('draft', 'live') NOT NULL DEFAULT 'draft',
  note LONGTEXT NOT NULL DEFAULT ('it''s; fine'),
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_email_key UNIQUE (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX accounts_deleted_at_idx ON accounts (deleted_at);
CREATE INDEX accounts_email_status_idx ON accounts (email, status);

CREATE TABLE sessions (
  id CHAR(36) NOT NULL DEFAULT (UUID()),
  token CHAR(36) DEFAULT (UUID()),
  deleted_at DATETIME(6),
  opened_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  account_id BIGINT,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX sessions_account_id_opened_at_key ON sessions (account_id, opened_at);

CREATE TABLE `groups` (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(40) NOT NULL,
  CONSTRAINT groups_pkey PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE memberships (
  role ENUM('owner', 'member') NOT NULL,
  account_id BIGINT NOT NULL,
  group_id INT NOT NULL,
  CONSTRAINT memberships_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT memberships_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
  CONSTRAINT memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE profiles (
  id INT NOT NULL AUTO_INCREMENT,
  bio LONGTEXT,
  owner_account_id BIGINT NOT NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profiles_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES accounts (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `LEGACY_ORDER` (
  `OrderNo` INT NOT NULL,
  kind VARCHAR(255) NOT NULL,
  http_code INT NOT NULL,
  `first name` VARCHAR(255),
  acct BIGINT,
  CONSTRAINT `LEGACY_ORDER_pkey` PRIMARY KEY (`OrderNo`),
  CONSTRAINT `LEGACY_ORDER_acct_fkey` FOREIGN KEY (acct) REFERENCES accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE groups_friends (
  id INT NOT NULL AUTO_INCREMENT,
  from_group_id INT NOT NULL,
  to_group_id INT NOT NULL,
  CONSTRAINT groups_friends_pkey PRIMARY KEY (id),
  CONSTRAINT groups_friends_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES `groups` (id) ON DELETE CASCADE,
  CONSTRAINT groups_friends_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES `groups` (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE UNIQUE INDEX groups_friends_from_group_id_to_group_id_key ON groups_friends (from_group_id, to_group_id);
