-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE customer (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  deleted_at DATETIME2 NULL,
  email NVARCHAR(255) NOT NULL,
  name NVARCHAR(100) NULL,
  role NVARCHAR(50) NOT NULL DEFAULT N'customer',
  billing_street NVARCHAR(120) NOT NULL,
  billing_city NVARCHAR(60) NOT NULL,
  billing_zip NVARCHAR(12) NULL,
  shipping_street NVARCHAR(120) NOT NULL,
  shipping_city NVARCHAR(60) NOT NULL,
  shipping_zip NVARCHAR(12) NULL,
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  [rank] BIGINT NOT NULL,
  avatar VARBINARY(MAX) NOT NULL,
  settings NVARCHAR(MAX) NOT NULL,
  CONSTRAINT customer_pkey PRIMARY KEY (id),
  CONSTRAINT customer_email_key UNIQUE (email),
  CONSTRAINT customer_role_check CHECK (role IN (N'customer', N'staff', N'admin')),
  CONSTRAINT customer_settings_check CHECK (ISJSON(settings) = 1)
);
CREATE INDEX customer_deleted_at_idx ON customer (deleted_at);

CREATE TABLE [order] (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  placed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note NVARCHAR(500) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  customer_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (id),
  CONSTRAINT order_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON [order] (customer_id, placed_at DESC);

CREATE TABLE product (
  sku NVARCHAR(40) NOT NULL,
  title NVARCHAR(200) NOT NULL,
  slug NVARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INT NOT NULL DEFAULT 0,
  deleted_at DATETIME2 NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT product_pkey PRIMARY KEY (sku)
);
CREATE INDEX product_title_idx ON product (title);
CREATE INDEX idx_product_slug ON product (slug);

CREATE TABLE order_item (
  line_no INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  product_sku NVARCHAR(40) NOT NULL,
  order_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT order_item_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_item_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES product (sku),
  CONSTRAINT order_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES [order] (id)
);

CREATE TABLE label (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  name NVARCHAR(40) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT label_pkey PRIMARY KEY (id),
  CONSTRAINT label_name_key UNIQUE (name)
);

CREATE TABLE comment (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  body NVARCHAR(MAX) NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type NVARCHAR(30) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  CONSTRAINT comment_pkey PRIMARY KEY (id)
);

CREATE TABLE order_label (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  order_id UNIQUEIDENTIFIER NOT NULL,
  label_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT order_label_pkey PRIMARY KEY (id),
  CONSTRAINT order_label_order_id_fkey FOREIGN KEY (order_id) REFERENCES [order] (id) ON DELETE CASCADE,
  CONSTRAINT order_label_label_id_fkey FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX order_label_order_id_label_id_key ON order_label (order_id, label_id);

CREATE TABLE product_similar (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  from_product_id NVARCHAR(40) NOT NULL,
  to_product_id NVARCHAR(40) NOT NULL,
  CONSTRAINT product_similar_pkey PRIMARY KEY (id),
  CONSTRAINT product_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES product (sku) ON DELETE CASCADE,
  CONSTRAINT product_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES product (sku)
);
CREATE UNIQUE INDEX product_similar_from_product_id_to_product_id_key ON product_similar (from_product_id, to_product_id);
