-- SQL DDL for SQL Server, generated by ormbridge.

CREATE TABLE customers (
  id BIGINT IDENTITY(1,1) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  updated_at DATETIME2 NOT NULL,
  deleted_at DATETIME2 NULL,
  email NVARCHAR(255) NOT NULL,
  name NVARCHAR(100) NULL,
  role NVARCHAR(50) NOT NULL DEFAULT N'customer',
  billing_street NVARCHAR(120) NOT NULL,
  billing_city NVARCHAR(60) NOT NULL,
  billing_zip NVARCHAR(12) NULL,
  shipping_street NVARCHAR(120) NOT NULL,
  shipping_city NVARCHAR(60) NOT NULL,
  shipping_zip NVARCHAR(12) NULL,
  balance DECIMAL(12, 2) NOT NULL DEFAULT 0,
  [rank] BIGINT NOT NULL,
  avatar VARBINARY(MAX) NOT NULL,
  settings NVARCHAR(MAX) NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_email_key UNIQUE (email),
  CONSTRAINT customers_role_check CHECK (role IN (N'customer', N'staff', N'admin')),
  CONSTRAINT customers_settings_check CHECK (ISJSON(settings) = 1)
);
CREATE INDEX customers_deleted_at_idx ON customers (deleted_at);

CREATE TABLE shop_orders (
  id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  placed_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  modified_at BIGINT NOT NULL,
  total DECIMAL(12, 2) NOT NULL,
  note NVARCHAR(500) NOT NULL,
  customer_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON UPDATE CASCADE
);
CREATE INDEX idx_order_customer_placed ON shop_orders (customer_id, placed_at DESC);

CREATE TABLE products (
  sku NVARCHAR(40) NOT NULL,
  title NVARCHAR(200) NOT NULL,
  slug NVARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  in_stock INT NOT NULL DEFAULT 0,
  deleted_at DATETIME2 NULL,
  CONSTRAINT products_pkey PRIMARY KEY (sku)
);
CREATE INDEX products_title_idx ON products (title);
CREATE INDEX idx_product_slug ON products (slug);

CREATE TABLE order_items (
  line_no INT NOT NULL,
  quantity INT NOT NULL DEFAULT 1,
  product_sku NVARCHAR(40) NOT NULL,
  order_id UNIQUEIDENTIFIER NOT NULL,
  CONSTRAINT order_items_pkey PRIMARY KEY (order_id, line_no),
  CONSTRAINT order_items_product_sku_fkey FOREIGN KEY (product_sku) REFERENCES products (sku),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id)
);

CREATE TABLE labels (
  id BIGINT IDENTITY(1,1) NOT NULL,
  name NVARCHAR(40) NOT NULL,
  CONSTRAINT labels_pkey PRIMARY KEY (id),
  CONSTRAINT labels_name_key UNIQUE (name)
);

CREATE TABLE comments (
  id BIGINT IDENTITY(1,1) NOT NULL,
  body NVARCHAR(MAX) NOT NULL,
  owner_id BIGINT NOT NULL,
  owner_type NVARCHAR(30) NOT NULL,
  CONSTRAINT comments_pkey PRIMARY KEY (id)
);

CREATE TABLE shop_orders_labels (
  id INT IDENTITY(1,1) NOT NULL,
  order_id UNIQUEIDENTIFIER NOT NULL,
  label_id BIGINT NOT NULL,
  CONSTRAINT shop_orders_labels_pkey PRIMARY KEY (id),
  CONSTRAINT shop_orders_labels_order_id_fkey FOREIGN KEY (order_id) REFERENCES shop_orders (id) ON DELETE CASCADE,
  CONSTRAINT shop_orders_labels_label_id_fkey FOREIGN KEY (label_id) REFERENCES labels (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX shop_orders_labels_order_id_label_id_key ON shop_orders_labels (order_id, label_id);

CREATE TABLE products_similar (
  id INT IDENTITY(1,1) NOT NULL,
  from_product_id NVARCHAR(40) NOT NULL,
  to_product_id NVARCHAR(40) NOT NULL,
  CONSTRAINT products_similar_pkey PRIMARY KEY (id),
  CONSTRAINT products_similar_from_product_id_fkey FOREIGN KEY (from_product_id) REFERENCES products (sku) ON DELETE CASCADE,
  CONSTRAINT products_similar_to_product_id_fkey FOREIGN KEY (to_product_id) REFERENCES products (sku)
);
CREATE UNIQUE INDEX products_similar_from_product_id_to_product_id_key ON products_similar (from_product_id, to_product_id);
