/**
 * Intermediate representation (IR) shared by every parser and emitter.
 *
 * Each supported format (Django, Prisma, and later TypeORM / Graphene) only
 * needs to know how to read into and write out of this model.
 */

export type IrScalarType =
  | 'string'
  | 'text'
  | 'int'
  | 'bigInt'
  | 'float'
  | 'decimal'
  | 'boolean'
  | 'dateTime'
  | 'date'
  | 'time'
  | 'uuid'
  | 'json'
  | 'bytes'
  | 'duration'
  | 'ipAddress'
  | 'hstore'
  | 'range'
  | 'unsupported';

/** Element type of a `range` field (Django's django.contrib.postgres range fields). */
export type IrRangeSubtype = 'int' | 'bigInt' | 'decimal' | 'date' | 'dateTime';

/** A provider-specific column type attribute, e.g. Prisma `@db.VarChar(255)` as `{ name: "VarChar", args: ["255"] }`. */
export interface IrNativeType {
  name: string;
  args: string[];
}

/** A database-computed column (Django GeneratedField). */
export interface IrGenerated {
  /** Expression source as written in the input, e.g. `F("a") + F("b")`. */
  expression: string;
  /** True when the value is stored (db_persist=True), false when computed on read. */
  isStored: boolean;
}

export type IrDefault =
  | { kind: 'literal'; value: string | number | boolean }
  | { kind: 'autoIncrement' }
  | { kind: 'now' }
  | { kind: 'uuid'; version?: number }
  | { kind: 'enumValue'; value: string }
  /** Generated by the ORM client rather than the database (Prisma cuid(), ulid(), nanoid()). */
  | { kind: 'clientGenerated'; generator: string; args?: string }
  /**
   * A raw database expression, stored without the quotes (Prisma `dbgenerated("gen_random_uuid()")`).
   * With `isFunction`, the expression is a Prisma default function written as-is, e.g. `auto()` or `sequence()`.
   */
  | { kind: 'dbExpression'; expression: string; isFunction?: boolean };

export interface IrField {
  /** Field name as written in the source format. */
  name: string;
  /** Database column name. */
  columnName: string;
  type: IrScalarType;
  isPrimaryKey: boolean;
  isUnique: boolean;
  isNullable: boolean;
  default?: IrDefault;
  maxLength?: number;
  maxDigits?: number;
  decimalPlaces?: number;
  /** True when the value is refreshed on every save (Django auto_now, Prisma @updatedAt). */
  isAutoUpdated: boolean;
  /** Name of an IrEnum when the field is enum-backed. */
  enumName?: string;
  /**
   * Number of array dimensions (Django ArrayField, nested ArrayFields add one each).
   * When set, `type` (and maxLength, enumName, ...) describe the innermost element.
   */
  arrayDepth?: number;
  /** Element type of the field when `type` is "range". */
  rangeOf?: IrRangeSubtype;
  /** Set when the column is computed by the database from an expression. */
  generated?: IrGenerated;
  /** True when `default` is a database-level default (Django db_default). */
  isDbDefault?: boolean;
  /** Native column type as written in the source (Prisma `@db.*`); only valid for that provider family. */
  nativeType?: IrNativeType;
  /** Raw database type text of an `unsupported` field, e.g. `circle` for Prisma `Unsupported("circle")`. */
  unsupportedType?: string;
  /** True when the field is excluded from the generated client (Prisma @ignore). */
  isIgnored?: boolean;
  /** Database name of the unique constraint (Prisma `@unique(map: "...")`). */
  uniqueName?: string;
}

export type IrOnDelete =
  'cascade' | 'setNull' | 'restrict' | 'noAction' | 'setDefault';

export type IrRelationKind = 'foreignKey' | 'oneToOne' | 'manyToMany';

export interface IrRelation {
  /** Relation field name, e.g. "author". */
  name: string;
  kind: IrRelationKind;
  /** Target model name. */
  targetModel: string;
  /** Foreign-key column on this model (unused for manyToMany). */
  columnName: string;
  isNullable: boolean;
  onDelete: IrOnDelete;
  /** Name of the reverse accessor on the target model. */
  relatedName?: string;
  /** Target column when it is not the primary key. */
  toField?: string;
  /** True when this relation is the primary key (multi-table inheritance). */
  isPrimaryKey?: boolean;
  /** Referential action on update (Prisma onUpdate). */
  onUpdate?: IrOnDelete;
  /** Database name of the foreign-key constraint (Prisma `@relation(map: "...")`). */
  constraintName?: string;
}

/**
 * A foreign key made of several columns (Prisma `@relation(fields: [a, b], references: [x, y])`).
 * The local columns stay ordinary fields of the model; only Prisma reads and writes this.
 */
export interface IrCompositeForeignKey {
  /** Relation field name, e.g. "order". */
  name: string;
  targetModel: string;
  /** Local field names, in key order. */
  fields: string[];
  /** Referenced field names on the target model, in the same order. */
  references: string[];
  kind: 'foreignKey' | 'oneToOne';
  isNullable: boolean;
  onDelete: IrOnDelete;
  onUpdate?: IrOnDelete;
  relatedName?: string;
  /** Database name of the constraint. */
  constraintName?: string;
}

/** Per-field options of an index entry (Prisma `a(sort: Desc, length: 10, ops: ...)`). */
export interface IrIndexFieldOptions {
  sort?: 'asc' | 'desc';
  length?: number;
  /** Operator class as written, e.g. `JsonbPathOps` or `raw("gin_trgm_ops")`. */
  ops?: string;
}

export interface IrIndex {
  /** Field or relation names (IR names, not column names). */
  fields: string[];
  isUnique: boolean;
  /** Explicit database name, when the source specified one. */
  name?: string;
  /** "fulltext" for Prisma @@fulltext; absent for ordinary indexes. */
  kind?: 'fulltext';
  /** Access method as written (Prisma `type: Hash | Gin | Gist | SpGist | Brin | BTree`). */
  method?: string;
  /** SQL Server clustered / non-clustered; absent when unspecified. */
  clustered?: boolean;
  /** Options for individual entries of `fields`, keyed by field name. */
  fieldOptions?: Record<string, IrIndexFieldOptions>;
}

export interface IrModel {
  name: string;
  tableName: string;
  /** Django app label, used to build default table names. */
  appLabel: string;
  fields: IrField[];
  relations: IrRelation[];
  indexes: IrIndex[];
  /** Composite primary key made of IR field/relation names (Prisma @@id). */
  compositePrimaryKey?: string[];
  /** True for join models synthesized from a many-to-many field. */
  isJoinTable?: boolean;
  /** True for database views (Prisma `view` blocks). */
  isView?: boolean;
  /** True when the model is excluded from the generated client (Prisma @@ignore). */
  isIgnored?: boolean;
  /** Database schema the table lives in (Prisma @@schema, multiSchema). */
  schema?: string;
  /** Database name of the primary-key constraint (Prisma `@id(map:)` / `@@id(map:)`). */
  primaryKeyName?: string;
  /** Multi-column foreign keys (Prisma). Single-column keys are in `relations`. */
  compositeForeignKeys?: IrCompositeForeignKey[];
}

export interface IrEnumValue {
  /** Member name, e.g. "ADMIN". */
  name: string;
  /** Stored database value, e.g. "admin". */
  dbValue: string;
  /** Human-readable label (Django TextChoices). */
  label?: string;
}

export interface IrEnum {
  name: string;
  values: IrEnumValue[];
  /** Database type name when it differs from `name` (Prisma @@map on an enum). */
  dbName?: string;
  /** Database schema the enum lives in (Prisma @@schema). */
  schema?: string;
}

export interface IrSchema {
  models: IrModel[];
  enums: IrEnum[];
  warnings: string[];
}

export function findModel(
  schema: IrSchema,
  modelName: string
): IrModel | undefined {
  return schema.models.find((model) => model.name === modelName);
}
