import type {
  IrCompositeForeignKey,
  IrField,
  IrIndex,
  IrModel,
  IrSchema,
} from './ir.js';

/**
 * Describes the IR constructs that only the Prisma emitter can write (views, composite foreign keys,
 * `Unsupported(...)` columns, full-text indexes, database schemas, ...). Every other emitter starts
 * its warning list with this (an emitter that has a view construct of its own passes `viewsSupported`), so a conversion never drops one of them silently.
 */
export function prismaOnlyWarnings(
  schema: IrSchema,
  viewsSupported: boolean = false
): string[] {
  const warnings: string[] = [];
  for (const enumDefinition of schema.enums) {
    if (enumDefinition.schema !== undefined) {
      warnings.push(
        `enum ${enumDefinition.name}: the database schema "${enumDefinition.schema}" (@@schema) was ignored.`
      );
    }
  }
  for (const model of schema.models) {
    describeModel(model, warnings, viewsSupported);
  }
  return warnings;
}

function describeModel(
  model: IrModel,
  warnings: string[],
  viewsSupported: boolean
): void {
  if (model.isView === true && !viewsSupported) {
    warnings.push(
      `${model.name}: this is a database view; it was written like a regular table model, so migrations would try to create a table.`
    );
  }
  if (model.isIgnored === true) {
    warnings.push(
      `${model.name}: @@ignore has no equivalent here; the model was written as a normal model.`
    );
  }
  if (model.schema !== undefined) {
    warnings.push(
      `${model.name}: the database schema "${model.schema}" (@@schema) was ignored.`
    );
  }
  for (const key of model.compositeForeignKeys ?? []) {
    warnings.push(describeCompositeKey(model, key));
  }
  for (const field of model.fields) {
    describeField(model, field, warnings);
  }
  for (const index of model.indexes) {
    describeIndex(model, index, warnings);
  }
  for (const relation of model.relations) {
    if (relation.onUpdate !== undefined) {
      warnings.push(
        `${model.name}.${relation.name}: the onUpdate action "${relation.onUpdate}" is not supported by this format and was ignored.`
      );
    }
  }
}

function describeCompositeKey(
  model: IrModel,
  key: IrCompositeForeignKey
): string {
  return (
    `${model.name}.${key.name}: the composite foreign key (${key.fields.join(', ')}) to ` +
    `${key.targetModel}(${key.references.join(', ')}) has no equivalent here; the relation was dropped and the columns kept as plain fields.`
  );
}

function describeField(
  model: IrModel,
  field: IrField,
  warnings: string[]
): void {
  const label: string = `${model.name}.${field.name}`;
  if (field.type === 'unsupported') {
    warnings.push(
      `${label}: the database type "${field.unsupportedType ?? 'unknown'}" (Prisma Unsupported) has no equivalent here; the column was written as a plain string.`
    );
  }
  if (field.isIgnored === true) {
    warnings.push(
      `${label}: @ignore has no equivalent here; the field was written as a normal field.`
    );
  }
  const defaultValue: IrField['default'] = field.default;
  if (defaultValue?.kind === 'clientGenerated') {
    warnings.push(
      `${label}: the ${defaultValue.generator}() default is generated by Prisma Client and was dropped.`
    );
  }
  if (defaultValue?.kind === 'dbExpression') {
    warnings.push(
      `${label}: the database default expression ${defaultValue.expression} was dropped.`
    );
  }
}

function describeIndex(
  model: IrModel,
  index: IrIndex,
  warnings: string[]
): void {
  const label: string = `${model.name} index (${index.fields.join(', ')})`;
  if (index.kind === 'fulltext') {
    warnings.push(
      `${label}: full-text indexes are not supported here; it was written as an ordinary index.`
    );
  }
  const hasFieldOptions: boolean =
    index.fieldOptions !== undefined &&
    Object.keys(index.fieldOptions).length > 0;
  if (
    index.method !== undefined ||
    index.clustered !== undefined ||
    hasFieldOptions
  ) {
    warnings.push(
      `${label}: the index type, clustering, sort order, prefix length and operator class options were dropped.`
    );
  }
}
