-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TYPE item_kind AS ENUM ('tool', 'toy');

CREATE TABLE item (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INTEGER NOT NULL DEFAULT 1,
  total_cents INTEGER NOT NULL, -- generated column written as a regular column
  tags VARCHAR(20)[] NOT NULL DEFAULT '{}',
  grid INTEGER[][],
  kinds item_kind[] NOT NULL DEFAULT '{}',
  attributes HSTORE NOT NULL DEFAULT ''::hstore,
  stock_range INT4RANGE,
  big_range INT8RANGE,
  price_range NUMRANGE,
  available DATERANGE,
  valid_during TSTZRANGE,
  last_ip INET,
  legacy_ip INET,
  shelf_life INTERVAL,
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INTEGER NOT NULL DEFAULT 0,
  tiny_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  stocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  priority INTEGER NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT item_pkey PRIMARY KEY (id),
  CONSTRAINT item_legacy_ip_key UNIQUE (legacy_ip)
);

CREATE TABLE counter (
  small_id UUID NOT NULL DEFAULT gen_random_uuid(),
  label VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT counter_pkey PRIMARY KEY (small_id)
);

CREATE TABLE content_type (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(254) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
);

CREATE TABLE shipment (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  object_id INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  item_id UUID NOT NULL,
  other_id UUID NOT NULL,
  content_type_id UUID NOT NULL,
  created_by_id UUID NOT NULL,
  CONSTRAINT shipment_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES content_type (id) ON DELETE CASCADE,
  CONSTRAINT shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE assignment (
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  item_id UUID NOT NULL,
  account_id UUID NOT NULL,
  CONSTRAINT assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
