-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TYPE "ItemKind" AS ENUM ('tool', 'toy');

CREATE TABLE blog_item (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INTEGER NOT NULL DEFAULT 1,
  total_cents INTEGER NOT NULL, -- generated column written as a regular column
  tags VARCHAR(20)[] NOT NULL DEFAULT '{}',
  grid INTEGER[][],
  kinds "ItemKind"[] NOT NULL DEFAULT '{}',
  attributes HSTORE NOT NULL DEFAULT ''::hstore,
  stock_range INT4RANGE,
  big_range INT8RANGE,
  price_range NUMRANGE,
  available DATERANGE,
  valid_during TSTZRANGE,
  last_ip INET,
  legacy_ip INET,
  shelf_life INTERVAL,
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INTEGER NOT NULL DEFAULT 0,
  tiny_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  stocked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  priority INTEGER NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  CONSTRAINT blog_item_pkey PRIMARY KEY (id),
  CONSTRAINT blog_item_legacy_ip_key UNIQUE (legacy_ip)
);

CREATE TABLE blog_counter (
  small_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  label VARCHAR(20) NOT NULL,
  CONSTRAINT blog_counter_pkey PRIMARY KEY (small_id)
);

CREATE TABLE blog_contenttype (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  CONSTRAINT blog_contenttype_pkey PRIMARY KEY (id)
);

CREATE TABLE blog_account (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT blog_account_pkey PRIMARY KEY (id),
  CONSTRAINT blog_account_email_key UNIQUE (email)
);

CREATE TABLE blog_shipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  object_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  other_id INTEGER NOT NULL,
  content_type_id INTEGER NOT NULL,
  created_by_id INTEGER NOT NULL,
  CONSTRAINT blog_shipment_pkey PRIMARY KEY (id),
  CONSTRAINT blog_shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES blog_contenttype (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES blog_account (id) ON DELETE CASCADE
);

CREATE TABLE blog_assignment (
  item_id INTEGER NOT NULL,
  account_id INTEGER NOT NULL,
  CONSTRAINT blog_assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT blog_assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES blog_account (id) ON DELETE CASCADE
);
