-- SQL DDL for MySQL, generated by ormbridge.

CREATE TABLE `Order` (
  region VARCHAR(255) NOT NULL,
  number INT NOT NULL,
  total DECIMAL(65, 30) NOT NULL,
  CONSTRAINT order_pkey PRIMARY KEY (region, number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `OrderLine` (
  id INT NOT NULL AUTO_INCREMENT,
  `orderRegion` VARCHAR(255) NOT NULL,
  `orderNumber` INT NOT NULL,
  sku VARCHAR(32) NOT NULL,
  CONSTRAINT `OrderLine_pkey` PRIMARY KEY (id),
  CONSTRAINT fk_line_order FOREIGN KEY (`orderRegion`, `orderNumber`) REFERENCES `Order` (region, number) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX `OrderLine_orderRegion_orderNumber_idx` ON `OrderLine` (`orderRegion`, `orderNumber`);

CREATE TABLE `Tenant` (
  id INT NOT NULL AUTO_INCREMENT,
  CONSTRAINT `Tenant_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Account` (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  `tenantId` INT NOT NULL,
  CONSTRAINT account_pk PRIMARY KEY (id),
  CONSTRAINT uq_account_email UNIQUE (email),
  CONSTRAINT fk_account_tenant FOREIGN KEY (`tenantId`) REFERENCES `Tenant` (id) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `Profile` (
  region VARCHAR(255) NOT NULL,
  number INT NOT NULL,
  `accountId` INT NOT NULL,
  CONSTRAINT `Profile_pkey` PRIMARY KEY (region, number),
  CONSTRAINT `Profile_accountId_key` UNIQUE (`accountId`),
  CONSTRAINT `Profile_accountId_fkey` FOREIGN KEY (`accountId`) REFERENCES `Account` (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE documents (
  id VARCHAR(255) NOT NULL,
  ulid VARCHAR(255) NOT NULL,
  short VARCHAR(255) NOT NULL,
  uid CHAR(36) NOT NULL DEFAULT (UUID()),
  token CHAR(36) NOT NULL DEFAULT (UUID()),
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  role ENUM('admin', 'user') NOT NULL DEFAULT 'user',
  small SMALLINT NOT NULL,
  ratio DOUBLE NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  cost DECIMAL(65, 30) NOT NULL,
  views BIGINT NOT NULL,
  `blob` LONGBLOB NOT NULL,
  meta JSON NOT NULL,
  created DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  day DATE NOT NULL,
  at TIME(6) NOT NULL,
  ip VARCHAR(45) NOT NULL,
  internal INT NOT NULL,
  legacy_name VARCHAR(255) NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id),
  CONSTRAINT uq_document_ulid UNIQUE (ulid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE INDEX ix_document_title ON documents (title DESC, created) USING BTREE;
CREATE UNIQUE INDEX uq_document_title_day ON documents (title, day);

CREATE TABLE `Scratch` (
  id INT NOT NULL,
  CONSTRAINT `Scratch_pkey` PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- View `DocumentSummary`: the schema has no SQL definition for it, so no statement was written.
-- Columns: id, title
-- CREATE VIEW `DocumentSummary` AS SELECT ... ;
