# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Boolean,
    Column,
    Date,
    DateTime,
    Enum,
    Float,
    ForeignKey,
    Index,
    Integer,
    Interval,
    LargeBinary,
    Numeric,
    String,
    Table,
    Text,
    Time,
    UniqueConstraint,
    Uuid,
    func,
    text,
    true,
)
from sqlalchemy.dialects.postgresql import HSTORE, INT4RANGE, Range
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class color(enum.Enum):
    RED = "red"
    GREEN = "green"


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


tagged_books = Table(
    "tagged_books",
    Base.metadata,
    Column("tagged_id", ForeignKey("tagged.id", ondelete="CASCADE"), primary_key=True),
    Column("book_id", ForeignKey("books.id", ondelete="CASCADE"), primary_key=True),
)


class Series(Base):
    __tablename__ = "series"
    __table_args__ = (
        UniqueConstraint("handle", name="series_handle_uq"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    handle: Mapped[str] = mapped_column(String(20))
    parent_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("series.id", ondelete="SET NULL"),
    )

    parent: Mapped[Optional["Series"]] = relationship(
        back_populates="children",
        remote_side="Series.id",
    )
    books: Mapped[list["Book"]] = relationship(
        back_populates="series",
        passive_deletes=True,
    )
    children: Mapped[list["Series"]] = relationship(
        back_populates="parent",
        passive_deletes=True,
    )
    indexes: Mapped[list["index"]] = relationship(back_populates="table")


class Book(Base):
    __tablename__ = "books"
    __table_args__ = (
        UniqueConstraint("title", "author_id", name="uq_books_title_author_id"),
        Index("books_published_idx", "published_on"),
    )

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )
    title: Mapped[str] = mapped_column(String(120))
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(String).with_variant(JSON(), "sqlite"),
        default=list,
    )
    grid: Mapped[Optional[list[list[int]]]] = mapped_column(
        ARRAY(Integer, dimensions=2).with_variant(JSON(), "sqlite"),
    )
    colors: Mapped[Optional[list[color]]] = mapped_column(
        ARRAY(Enum(color, name="color_t", values_callable=lambda members: [member.value for member in members])).with_variant(
            JSON(),
            "sqlite",
        ),
    )
    color_: Mapped[color] = mapped_column(
        "color",
        Enum(
            color,
            name="color_t",
            values_callable=lambda members: [member.value for member in members],
        ),
        server_default="red",
    )
    price: Mapped[decimal.Decimal] = mapped_column(
        Numeric(8, 2),
        server_default=text("9.99"),
    )
    settings: Mapped[Any] = mapped_column(
        JSON,
        server_default=text("'{\"theme\": \"dark\", \"tabs\": [1, 2]}'"),
    )
    published_on: Mapped[datetime.date] = mapped_column(
        Date,
        server_default=func.current_date(),
    )
    opens_at: Mapped[Optional[datetime.time]] = mapped_column(Time)
    released_at: Mapped[Optional[datetime.datetime]] = mapped_column(
        DateTime(timezone=True),
        server_default="2020-01-02T03:04:05Z",
    )
    pages: Mapped[int] = mapped_column(Integer, server_default=text("100"))
    ratio: Mapped[float] = mapped_column(Float, server_default=text("0.5"))
    in_print: Mapped[bool] = mapped_column(Boolean, server_default=true())
    notes: Mapped[Optional[str]] = mapped_column(Text)
    window: Mapped[Optional[Range[int]]] = mapped_column(
        INT4RANGE().with_variant(JSON(), "sqlite"),
    )
    extra: Mapped[Optional[dict[str, str]]] = mapped_column(
        HSTORE().with_variant(JSON(), "sqlite"),
    )
    read_time: Mapped[Optional[datetime.timedelta]] = mapped_column(Interval)
    cover: Mapped[Optional[bytes]] = mapped_column(LargeBinary)
    author_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("authors.id", ondelete="CASCADE", onupdate="CASCADE"),
    )
    editor_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        Uuid,
        ForeignKey("authors.id", ondelete="SET NULL"),
    )
    series_handle: Mapped[Optional[str]] = mapped_column(
        String(20),
        ForeignKey("series.handle", ondelete="SET NULL"),
    )

    author: Mapped["Author"] = relationship(
        back_populates="books",
        foreign_keys="[Book.author_id]",
    )
    editor: Mapped[Optional["Author"]] = relationship(
        back_populates="edited_books",
        foreign_keys="[Book.editor_id]",
    )
    series: Mapped[Optional["Series"]] = relationship(back_populates="books")
    latest_for: Mapped[list["Author"]] = relationship(
        back_populates="latest_book",
        foreign_keys="[Author.latest_book_id]",
        passive_deletes=True,
    )
    audiobook: Mapped[Optional["Audiobook"]] = relationship(
        back_populates="book",
        passive_deletes=True,
    )
    taggeds: Mapped[list["Tagged"]] = relationship(
        back_populates="books",
        secondary=tagged_books,
    )


class Author(Base):
    __tablename__ = "authors"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    handle: Mapped[str] = mapped_column(String(30), unique=True)
    favourite_book_id: Mapped[Optional[int]] = mapped_column(Integer)
    latest_book_id: Mapped[Optional[int]] = mapped_column(
        BigInteger,
        ForeignKey("books.id", ondelete="SET NULL"),
    )

    latest_book: Mapped[Optional["Book"]] = relationship(
        back_populates="latest_for",
        foreign_keys="[Author.latest_book_id]",
    )
    books: Mapped[list["Book"]] = relationship(
        back_populates="author",
        foreign_keys="[Book.author_id]",
        passive_deletes=True,
    )
    edited_books: Mapped[list["Book"]] = relationship(
        back_populates="editor",
        foreign_keys="[Book.editor_id]",
        passive_deletes=True,
    )


class Audiobook(Base):
    __tablename__ = "audiobooks"

    minutes: Mapped[int] = mapped_column(Integer)
    book_ptr_id: Mapped[int] = mapped_column(
        BigInteger,
        ForeignKey("books.id", ondelete="CASCADE"),
        primary_key=True,
    )

    book: Mapped["Book"] = relationship(back_populates="audiobook")


class index(Base):
    __tablename__ = "index_rows"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    sql: Mapped[Optional[str]] = mapped_column(String)
    class_: Mapped[Optional[str]] = mapped_column("class", String)
    table_id: Mapped[Optional[int]] = mapped_column(
        "table",
        Integer,
        ForeignKey("series.id", ondelete="NO ACTION"),
    )

    table: Mapped[Optional["Series"]] = relationship(back_populates="indexes")


class Tagged(Base):
    __tablename__ = "tagged"

    id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        primary_key=True,
        autoincrement=True,
    )

    books: Mapped[list["Book"]] = relationship(
        back_populates="taggeds",
        secondary=tagged_books,
    )
