# Generated by ormbridge. Review the output before creating tables or migrations.

import datetime
import decimal
import enum
import uuid
from typing import Any, Optional

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    func,
    text,
    true,
)
from sqlalchemy.dialects.postgresql import HSTORE, INT4RANGE, Range
from sqlmodel import Field, Relationship, SQLModel


class color(enum.Enum):
    RED = "red"
    GREEN = "green"


class Status(enum.Enum):
    DRAFT = "draft"
    LIVE = "live"


tagged_books = Table(
    "tagged_books",
    SQLModel.metadata,
    Column("tagged_id", ForeignKey("tagged.id", ondelete="CASCADE"), primary_key=True),
    Column("book_id", ForeignKey("books.id", ondelete="CASCADE"), primary_key=True),
)


class Series(SQLModel, table=True):
    __tablename__ = "series"
    __table_args__ = (
        UniqueConstraint("handle", name="series_handle_uq"),
    )

    id: Optional[int] = Field(default=None, primary_key=True)
    handle: str = Field(max_length=20)
    parent_id: Optional[int] = Field(
        default=None,
        foreign_key="series.id",
        ondelete="SET NULL",
    )

    parent: Optional["Series"] = Relationship(
        back_populates="children",
        sa_relationship_kwargs={"remote_side": "Series.id"},
    )
    books: list["Book"] = Relationship(
        back_populates="series",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    children: list["Series"] = Relationship(
        back_populates="parent",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    indexes: list["index"] = Relationship(back_populates="table")


class Book(SQLModel, table=True):
    __tablename__ = "books"
    __table_args__ = (
        UniqueConstraint("title", "author_id", name="uq_books_title_author_id"),
        Index("books_published_idx", "published_on"),
    )

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )
    title: str = Field(max_length=120)
    tags: list[str] = Field(
        default_factory=list,
        sa_type=ARRAY(String).with_variant(JSON(), "sqlite"),
    )
    grid: Optional[list[list[int]]] = Field(
        default=None,
        sa_type=ARRAY(Integer, dimensions=2).with_variant(JSON(), "sqlite"),
    )
    colors: Optional[list[color]] = Field(
        default=None,
        sa_type=ARRAY(Enum(color, name="color_t", values_callable=lambda members: [member.value for member in members])).with_variant(
            JSON(),
            "sqlite",
        ),
    )
    color_: color = Field(
        default=color.RED,
        sa_type=Enum(
            color,
            name="color_t",
            values_callable=lambda members: [member.value for member in members],
        ),
        sa_column_kwargs={"name": "color", "server_default": "red"},
    )
    price: Optional[decimal.Decimal] = Field(
        default=None,
        nullable=False,
        max_digits=8,
        decimal_places=2,
        sa_column_kwargs={"server_default": text("9.99")},
    )
    settings: Any = Field(
        default_factory=lambda: {"theme": "dark", "tabs": [1, 2]},
        sa_type=JSON,
        sa_column_kwargs={
            "server_default": text("'{\"theme\": \"dark\", \"tabs\": [1, 2]}'"),
        },
    )
    published_on: Optional[datetime.date] = Field(
        default=None,
        nullable=False,
        sa_column_kwargs={"server_default": func.current_date()},
    )
    opens_at: Optional[datetime.time] = Field(default=None)
    released_at: Optional[datetime.datetime] = Field(
        default=None,
        sa_type=DateTime(timezone=True),
        sa_column_kwargs={"server_default": "2020-01-02T03:04:05Z"},
    )
    pages: int = Field(default=100, sa_column_kwargs={"server_default": text("100")})
    ratio: float = Field(default=0.5, sa_column_kwargs={"server_default": text("0.5")})
    in_print: bool = Field(default=True, sa_column_kwargs={"server_default": true()})
    notes: Optional[str] = Field(default=None, sa_type=Text)
    window: Optional[Range[int]] = Field(
        default=None,
        sa_type=INT4RANGE().with_variant(JSON(), "sqlite"),
    )
    extra: Optional[dict[str, str]] = Field(
        default=None,
        sa_type=HSTORE().with_variant(JSON(), "sqlite"),
    )
    read_time: Optional[datetime.timedelta] = Field(default=None)
    cover: Optional[bytes] = Field(default=None)
    author_id: uuid.UUID = Field(
        sa_column=Column(
            "author_id",
            Uuid,
            ForeignKey("authors.id", ondelete="CASCADE", onupdate="CASCADE"),
            nullable=False,
        ),
    )
    editor_id: Optional[uuid.UUID] = Field(
        default=None,
        foreign_key="authors.id",
        ondelete="SET NULL",
    )
    series_handle: Optional[str] = Field(
        default=None,
        foreign_key="series.handle",
        ondelete="SET NULL",
        max_length=20,
    )

    author: "Author" = Relationship(
        back_populates="books",
        sa_relationship_kwargs={"foreign_keys": "[Book.author_id]"},
    )
    editor: Optional["Author"] = Relationship(
        back_populates="edited_books",
        sa_relationship_kwargs={"foreign_keys": "[Book.editor_id]"},
    )
    series: Optional["Series"] = Relationship(back_populates="books")
    latest_for: list["Author"] = Relationship(
        back_populates="latest_book",
        sa_relationship_kwargs={
            "foreign_keys": "[Author.latest_book_id]",
            "passive_deletes": True,
        },
    )
    audiobook: Optional["Audiobook"] = Relationship(
        back_populates="book",
        sa_relationship_kwargs={"passive_deletes": True},
    )
    taggeds: list["Tagged"] = Relationship(
        back_populates="books",
        sa_relationship_kwargs={"secondary": tagged_books},
    )


class Author(SQLModel, table=True):
    __tablename__ = "authors"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    handle: str = Field(unique=True, max_length=30)
    favourite_book_id: Optional[int] = Field(default=None)
    latest_book_id: Optional[int] = Field(
        default=None,
        foreign_key="books.id",
        ondelete="SET NULL",
        sa_type=BigInteger,
    )

    latest_book: Optional["Book"] = Relationship(
        back_populates="latest_for",
        sa_relationship_kwargs={"foreign_keys": "[Author.latest_book_id]"},
    )
    books: list["Book"] = Relationship(
        back_populates="author",
        sa_relationship_kwargs={
            "foreign_keys": "[Book.author_id]",
            "passive_deletes": True,
        },
    )
    edited_books: list["Book"] = Relationship(
        back_populates="editor",
        sa_relationship_kwargs={
            "foreign_keys": "[Book.editor_id]",
            "passive_deletes": True,
        },
    )


class Audiobook(SQLModel, table=True):
    __tablename__ = "audiobooks"

    minutes: int
    book_ptr_id: int = Field(
        primary_key=True,
        foreign_key="books.id",
        ondelete="CASCADE",
        sa_type=BigInteger,
    )

    book: "Book" = Relationship(back_populates="audiobook")


class index(SQLModel, table=True):
    __tablename__ = "index_rows"

    id: Optional[int] = Field(default=None, primary_key=True)
    sql: Optional[str] = Field(default=None)
    class_: Optional[str] = Field(default=None, sa_column_kwargs={"name": "class"})
    table_id: Optional[int] = Field(
        default=None,
        sa_column=Column(
            "table",
            Integer,
            ForeignKey("series.id", ondelete="NO ACTION"),
            nullable=True,
        ),
    )

    table: Optional["Series"] = Relationship(back_populates="indexes")


class Tagged(SQLModel, table=True):
    __tablename__ = "tagged"

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        sa_type=BigInteger().with_variant(Integer, "sqlite"),
    )

    books: list["Book"] = Relationship(
        back_populates="taggeds",
        sa_relationship_kwargs={"secondary": tagged_books},
    )
