-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE status AS ENUM ('draft', 'live');

CREATE TYPE role AS ENUM ('owner', 'member');

CREATE TABLE account (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  email VARCHAR(255) NOT NULL,
  balance NUMERIC(10, 2) NOT NULL,
  score DOUBLE PRECISION,
  avatar BYTEA,
  payload JSONB,
  labels TEXT[] NOT NULL,
  ttl INTERVAL,
  ip INET,
  homepage_url TEXT,
  born DATE,
  alarm TIME,
  status status NOT NULL DEFAULT 'draft',
  note TEXT NOT NULL DEFAULT 'it''s; fine',
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
);
CREATE INDEX account_deleted_at_idx ON account (deleted_at);
CREATE INDEX account_email_status_idx ON account (email, status);

CREATE TABLE session (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  token UUID DEFAULT gen_random_uuid(),
  deleted_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  account_id UUID,
  CONSTRAINT session_pkey PRIMARY KEY (id),
  CONSTRAINT session_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX session_account_id_opened_at_key ON session (account_id, opened_at);

CREATE TABLE "group" (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  name VARCHAR(40) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT group_pkey PRIMARY KEY (id)
);

CREATE TABLE membership (
  role role NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  account_id UUID NOT NULL,
  group_id UUID NOT NULL,
  CONSTRAINT membership_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT membership_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE,
  CONSTRAINT membership_group_id_fkey FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE RESTRICT
);

CREATE TABLE profile (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  bio TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  owner_account_id UUID NOT NULL,
  CONSTRAINT profile_pkey PRIMARY KEY (id),
  CONSTRAINT profile_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profile_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE legacy_order (
  order_no INTEGER NOT NULL,
  kind TEXT NOT NULL,
  http_code INTEGER NOT NULL,
  first_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  acct UUID,
  CONSTRAINT legacy_order_pkey PRIMARY KEY (order_no),
  CONSTRAINT legacy_order_acct_fkey FOREIGN KEY (acct) REFERENCES account (id)
);

CREATE TABLE group_friend (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  from_group_id UUID NOT NULL,
  to_group_id UUID NOT NULL,
  CONSTRAINT group_friend_pkey PRIMARY KEY (id),
  CONSTRAINT group_friend_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES "group" (id) ON DELETE CASCADE,
  CONSTRAINT group_friend_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES "group" (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX group_friend_from_group_id_to_group_id_key ON group_friend (from_group_id, to_group_id);
