-- SQL DDL for PostgreSQL, generated by ormbridge.

CREATE TYPE "Status" AS ENUM ('draft', 'live');

CREATE TYPE "Role" AS ENUM ('owner', 'member');

CREATE TABLE accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ,
  email VARCHAR(255) NOT NULL,
  balance NUMERIC(10, 2) NOT NULL,
  score DOUBLE PRECISION,
  avatar BYTEA,
  payload JSONB,
  labels TEXT[] NOT NULL,
  ttl INTERVAL,
  ip INET,
  homepage_url TEXT,
  born DATE,
  alarm TIME,
  status "Status" NOT NULL DEFAULT 'draft',
  note TEXT NOT NULL DEFAULT 'it''s; fine',
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_email_key UNIQUE (email)
);
CREATE INDEX accounts_deleted_at_idx ON accounts (deleted_at);
CREATE INDEX accounts_email_status_idx ON accounts (email, status);

CREATE TABLE sessions (
  id UUID NOT NULL DEFAULT gen_random_uuid(),
  token UUID DEFAULT gen_random_uuid(),
  deleted_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  account_id BIGINT,
  CONSTRAINT sessions_pkey PRIMARY KEY (id),
  CONSTRAINT sessions_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX sessions_account_id_opened_at_key ON sessions (account_id, opened_at);

CREATE TABLE "groups" (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(40) NOT NULL,
  CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE memberships (
  role "Role" NOT NULL,
  account_id BIGINT NOT NULL,
  group_id INTEGER NOT NULL,
  CONSTRAINT memberships_pkey PRIMARY KEY (account_id, group_id),
  CONSTRAINT memberships_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE CASCADE,
  CONSTRAINT memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES "groups" (id) ON DELETE RESTRICT
);

CREATE TABLE profiles (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  bio TEXT,
  owner_account_id BIGINT NOT NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_owner_account_id_key UNIQUE (owner_account_id),
  CONSTRAINT profiles_owner_account_id_fkey FOREIGN KEY (owner_account_id) REFERENCES accounts (id) ON DELETE CASCADE
);

CREATE TABLE "LEGACY_ORDER" (
  "OrderNo" INTEGER NOT NULL,
  kind TEXT NOT NULL,
  http_code INTEGER NOT NULL,
  "first name" TEXT,
  acct BIGINT,
  CONSTRAINT "LEGACY_ORDER_pkey" PRIMARY KEY ("OrderNo"),
  CONSTRAINT "LEGACY_ORDER_acct_fkey" FOREIGN KEY (acct) REFERENCES accounts (id)
);

CREATE TABLE groups_friends (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  from_group_id INTEGER NOT NULL,
  to_group_id INTEGER NOT NULL,
  CONSTRAINT groups_friends_pkey PRIMARY KEY (id),
  CONSTRAINT groups_friends_from_group_id_fkey FOREIGN KEY (from_group_id) REFERENCES "groups" (id) ON DELETE CASCADE,
  CONSTRAINT groups_friends_to_group_id_fkey FOREIGN KEY (to_group_id) REFERENCES "groups" (id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX groups_friends_from_group_id_to_group_id_key ON groups_friends (from_group_id, to_group_id);
