-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE item (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INTEGER NOT NULL DEFAULT 1,
  total_cents INTEGER NOT NULL, -- generated column written as a regular column
  tags TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  grid TEXT, -- an array stored as JSON
  kinds TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  attributes TEXT NOT NULL DEFAULT '{}', -- hstore stored as JSON
  stock_range TEXT, -- range stored as text
  big_range TEXT, -- range stored as text
  price_range TEXT, -- range stored as text
  available TEXT, -- range stored as text
  valid_during TEXT, -- range stored as text
  last_ip TEXT,
  legacy_ip TEXT,
  shelf_life INTEGER, -- duration in microseconds
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INTEGER NOT NULL DEFAULT 0,
  tiny_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT 1,
  stocked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority INTEGER NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT item_pkey PRIMARY KEY (id),
  CONSTRAINT item_legacy_ip_key UNIQUE (legacy_ip),
  CONSTRAINT item_tags_check CHECK (json_valid(tags)),
  CONSTRAINT item_grid_check CHECK (json_valid(grid)),
  CONSTRAINT item_kinds_check CHECK (json_valid(kinds)),
  CONSTRAINT item_attributes_check CHECK (json_valid(attributes))
);

CREATE TABLE counter (
  small_id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  label VARCHAR(20) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT counter_pkey PRIMARY KEY (small_id)
);

CREATE TABLE content_type (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT content_type_pkey PRIMARY KEY (id)
);

CREATE TABLE account (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  email VARCHAR(254) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  CONSTRAINT account_pkey PRIMARY KEY (id),
  CONSTRAINT account_email_key UNIQUE (email)
);

CREATE TABLE shipment (
  id CHAR(36) NOT NULL DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))), 2) || '-' || substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' || lower(hex(randomblob(6)))),
  object_id INTEGER NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  item_id CHAR(36) NOT NULL,
  other_id CHAR(36) NOT NULL,
  content_type_id CHAR(36) NOT NULL,
  created_by_id CHAR(36) NOT NULL,
  CONSTRAINT shipment_pkey PRIMARY KEY (id),
  CONSTRAINT shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES content_type (id) ON DELETE CASCADE,
  CONSTRAINT shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES account (id) ON DELETE CASCADE
);

CREATE TABLE assignment (
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL,
  item_id CHAR(36) NOT NULL,
  account_id CHAR(36) NOT NULL,
  CONSTRAINT assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE,
  CONSTRAINT assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE
);
