-- SQL DDL for SQLite, generated by ormbridge.

PRAGMA foreign_keys = ON;

CREATE TABLE blog_item (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  full_name VARCHAR(81) NOT NULL, -- generated column written as a regular column
  quantity INTEGER NOT NULL DEFAULT 1,
  total_cents INTEGER NOT NULL, -- generated column written as a regular column
  tags TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  grid TEXT, -- an array stored as JSON
  kinds TEXT NOT NULL DEFAULT '[]', -- an array stored as JSON
  attributes TEXT NOT NULL DEFAULT '{}', -- hstore stored as JSON
  stock_range TEXT, -- range stored as text
  big_range TEXT, -- range stored as text
  price_range TEXT, -- range stored as text
  available TEXT, -- range stored as text
  valid_during TEXT, -- range stored as text
  last_ip TEXT,
  legacy_ip TEXT,
  shelf_life INTEGER, -- duration in microseconds
  source_path VARCHAR(100),
  manual VARCHAR(100),
  photo VARCHAR(100),
  small_count INTEGER NOT NULL DEFAULT 0,
  tiny_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT 1,
  stocked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority INTEGER NOT NULL DEFAULT 5,
  note VARCHAR(20) NOT NULL DEFAULT 'none',
  CONSTRAINT blog_item_legacy_ip_key UNIQUE (legacy_ip),
  CONSTRAINT blog_item_tags_check CHECK (json_valid(tags)),
  CONSTRAINT blog_item_grid_check CHECK (json_valid(grid)),
  CONSTRAINT blog_item_kinds_check CHECK (json_valid(kinds)),
  CONSTRAINT blog_item_attributes_check CHECK (json_valid(attributes))
);

CREATE TABLE blog_counter (
  small_id INTEGER PRIMARY KEY AUTOINCREMENT,
  label VARCHAR(20) NOT NULL
);

CREATE TABLE blog_contenttype (
  id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE blog_account (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT blog_account_email_key UNIQUE (email)
);

CREATE TABLE blog_shipment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  object_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  other_id INTEGER NOT NULL,
  content_type_id INTEGER NOT NULL,
  created_by_id INTEGER NOT NULL,
  CONSTRAINT blog_shipment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_other_id_fkey FOREIGN KEY (other_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_content_type_id_fkey FOREIGN KEY (content_type_id) REFERENCES blog_contenttype (id) ON DELETE CASCADE,
  CONSTRAINT blog_shipment_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES blog_account (id) ON DELETE CASCADE
);

CREATE TABLE blog_assignment (
  item_id INTEGER NOT NULL,
  account_id INTEGER NOT NULL,
  CONSTRAINT blog_assignment_pkey PRIMARY KEY (item_id, account_id),
  CONSTRAINT blog_assignment_item_id_fkey FOREIGN KEY (item_id) REFERENCES blog_item (id) ON DELETE CASCADE,
  CONSTRAINT blog_assignment_account_id_fkey FOREIGN KEY (account_id) REFERENCES blog_account (id) ON DELETE CASCADE
);
